immutable/ts-immutable-sdk

packages/checkout/widgets-lib/src/components/Status/StatusBox.tsx, packages/checkout/widgets-lib/src/context/view-context/XBridgeViewContextTypes.ts, packages/checkout/widgets-lib/src/widgets/x-bridge/XBridgeWidget.tsx, packages/checkout/widgets-lib/src/widgets/x-bridge/components/BridgeReviewSummary.tsx, packages/checkout/widgets-lib/src/widgets/x-bridge/views/ApproveTransaction.tsx
https://immutable.atlassian.net/browse/WT-1988
=> WT-1988 - fix bridge failure state

packages/checkout/widgets-lib/src/components/Hero/RocketHero.tsx
https://immutable.atlassian.net/browse/WT-1994
Defined `stateMachines` in rive component which plays the state machine timeline on component instantiation.
https://github.com/immutable/ts-immutable-sdk/assets/37326128/1db043d4-cd14-478e-b341-5169aa5accd0
=> feat: WT-1994 Update state machine for the rocket rive component

packages/game-bridge/src/index.ts
Game bridge set provider to invalid field
=> fix: game bridge set provider

packages/checkout/widgets-lib/src/resources/text/textConfig.ts
https://immutable.atlassian.net/browse/WT-1581
=> feat: WT-1581 Copy change for switch network screen

packages/checkout/sdk/src/env/constants.ts
Patch the blockscout mainnet URL
=> WT-2011 - Patch the mainnet blockscout

packages/checkout/widgets-lib/src/components/CoinSelector/CoinSelector.tsx, packages/checkout/widgets-lib/src/components/CoinSelector/CoinSelectorStyles.tsx, packages/checkout/widgets-lib/src/components/FormComponents/SelectForm/SelectForm.tsx, packages/checkout/widgets-lib/src/resources/text/textConfig.ts, packages/checkout/widgets-lib/src/widgets/bridge/BridgeWidget.cy.tsx, packages/checkout/widgets-lib/src/widgets/bridge/components/BridgeForm.tsx, packages/checkout/widgets-lib/src/widgets/bridge/components/BridgeFormStyles.ts, packages/checkout/widgets-lib/src/widgets/bridge/components/BridgeReviewSummary.tsx, packages/checkout/widgets-lib/src/widgets/bridge/components/BridgeReviewSummaryStyles.ts, packages/checkout/widgets-sample-app/src/components/ui/marketplace-orchestrator/MainPage.tsx
https://immutable.atlassian.net/browse/WT-1970
=> fix: WT-1970 Bridge widget design feedback 

packages/checkout/sdk/src/types/config.ts, packages/checkout/widgets-lib/src/context/analytics-provider/SetupAnalytics.tsx
=> [WT-2010] update telemetry prop name

packages/checkout/widgets-lib/src/widgets/wallet/components/BalanceItem/BalanceItem.cy.tsx, packages/checkout/widgets-lib/src/widgets/wallet/components/BalanceItem/BalanceItem.tsx
https://immutable.atlassian.net/browse/WT-1991
=> feat: WT-1991 enable move option for balance item on L2

tests/func-tests/package.json, tests/func-tests/yarn.lock
[Dependabot fix](https://github.com/immutable/ts-immutable-sdk/security/dependabot/86)
- Patch insecure OpenZeppelin contracts version in the `func-tests` folder
=> chore: update OZ contracts version

packages/checkout/widgets-lib/src/components/Transak/useTransakEvents.ts, packages/checkout/widgets-lib/src/widgets/on-ramp/views/OnRampMain.tsx
Fix for:
https://github.com/immutable/ts-immutable-sdk/security/code-scanning/2
https://github.com/immutable/ts-immutable-sdk/security/code-scanning/3
=> [WT-2027] Sanitize url check

packages/checkout/widgets-lib/src/views/error/ErrorView.tsx, packages/checkout/widgets-lib/src/widgets/bridge/BridgeWidget.tsx, packages/checkout/widgets-lib/src/widgets/bridge/components/BridgeForm.tsx, packages/checkout/widgets-lib/src/widgets/connect/views/ReadyToConnect.tsx, packages/checkout/widgets-lib/src/widgets/connect/views/SwitchNetworkEth.tsx, packages/checkout/widgets-lib/src/widgets/connect/views/SwitchNetworkZkEVM.tsx
This PR fixes the following:
- `views.SWITCH_NETWORK.zkEVM.button.text`
https://imtbl.slack.com/archives/C0414KQ5162/p1704675148465449
- remove `views.` from `views.drawers.feesBreakdown.fees.gas.label` https://imtbl.slack.com/archives/C0414KQ5162/p1704678792805569
- remove `.errorText` from `views.ERROR_VIEW.errorText.heading`
This PR also adds console.error to further debug [this reported issue](https://imtbl.slack.com/archives/C02UK3GC2N4/p1704674338238379)
=> Fix: Locale keys

packages/blockchain-data/sdk/package.json, packages/checkout/sdk/package.json, packages/checkout/sdk/test/__mocks__/window.ts, packages/config/package.json, packages/economy/playground/package.json, packages/economy/sdk/package.json, packages/internal/bridge/sdk/package.json, packages/internal/cryptofiat/package.json, packages/internal/guardian/package.json, packages/internal/toolkit/package.json, packages/internal/version-check/package.json, packages/orderbook/package.json, packages/passport/sdk/package.json, packages/provider/package.json, sdk/package.json, yarn.lock
[DX-2483](https://immutable.atlassian.net/browse/DX-2483)
- Patch Axios cross-site request forgery vulnerability
- `checkout` Jest test environment needed a `navigator` object to work after the version bump.
[DX-2483]: https://immutable.atlassian.net/browse/DX-2483?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore: Patch Axios Cross-Site Request Forgery Vulnerability

packages/checkout/widgets-lib/src/components/Transactions/Transactions.tsx
Improvements
`src/components/Transactions/Transactions.tsx` should use `checkout.getTokenAllowList({ type: TokenFilterTypes.BRIDGE, chainId: rootChainId })` without having the need to reach into the remote configs.
none
=> WT-2036 - improved allow token fetch

packages/checkout/widgets-lib/src/widgets/bridge/components/WalletNetworkButton.tsx
Network name was hardcoded to only handle Testnet networks.
UX confusion
=> WT-2035 - dynamic network name

packages/internal/bridge/sdk/src/config/index.ts
Bridge SDK configuration for Mainnet are incomplete. This PR allows to run the Bridge SDK on Mainnet.
Supported `BridgeInstance` for Mainnet.
=> fix: WT-2039 - enable bridge instance for mainnet

packages/checkout/sdk/src/api/blockscout/blockscout.test.ts, packages/checkout/sdk/src/env/constants.ts, packages/checkout/sdk/src/network/network.test.ts, packages/checkout/sdk/src/smartCheckout/balanceCheck/balanceCheck.test.ts, packages/checkout/sdk/src/smartCheckout/balanceCheck/balanceRequirement.ts, packages/checkout/sdk/src/smartCheckout/routing/onRamp/onRampRoute.ts
=> fix: WT-2045 - fixing smartcheckout routing

tests/func-tests/imx/yarn.lock, tests/func-tests/zkevm/package.json, tests/func-tests/zkevm/yarn.lock
Bump the insecure OpenZeppelin contracts version in the function test projects.
- Bump insecure contract version
=> chore: upgrade OZ contracts version

packages/checkout/widgets-lib/src/components/Transactions/TransactionItem.tsx, packages/checkout/widgets-lib/src/components/Transactions/TransactionsInProgress.tsx
Enable action button for withdrawal claim with action message
https://github.com/immutable/ts-immutable-sdk/assets/109640446/ae9b7036-ce76-4c37-a489-5098626c33ca
=> [wt-2007] Enable action button for claim

package.json, packages/checkout/sdk-sample-app/package.json, packages/checkout/widgets-lib/package.json, packages/checkout/widgets-sample-app/package.json, packages/passport/sdk-sample-app/package.json, packages/provider/src/sample-app/package.json, sdk/package.json, yarn.lock
Upate biome version for new npm release
=> feat: WT-2046 update biome version

packages/checkout/sdk/src/widgets/definitions/events/sale.ts, packages/checkout/widgets-lib/src/resources/text/textConfig.ts, packages/checkout/widgets-lib/src/widgets/sale/SaleWidgetEvents.ts, packages/checkout/widgets-lib/src/widgets/sale/components/PaymentOption.tsx, packages/checkout/widgets-lib/src/widgets/sale/components/PaymentOptions.tsx, packages/checkout/widgets-lib/src/widgets/sale/context/SaleContextProvider.tsx, packages/checkout/widgets-lib/src/widgets/sale/hooks/useSaleEvents.ts, packages/checkout/widgets-lib/src/widgets/sale/hooks/useSignOrder.ts, packages/checkout/widgets-lib/src/widgets/sale/types.ts, packages/checkout/widgets-lib/src/widgets/sale/views/PaymentMethods.tsx, packages/checkout/widgets-lib/src/widgets/sale/views/SaleErrorView.tsx
Exporting `SalePaymentTypes` from sdk.
=> Export SalePaymentTypes from sdk

packages/checkout/sdk/src/widgets/definitions/parameters/sale.ts, packages/checkout/widgets-lib/src/components/Transak/useTransakIframe.ts, packages/checkout/widgets-lib/src/widgets/sale/SaleWidget.tsx, packages/checkout/widgets-lib/src/widgets/sale/SaleWidgetRoot.tsx, packages/checkout/widgets-lib/src/widgets/sale/components/FundingRouteSelect/FundingRouteSelect.cy.tsx, packages/checkout/widgets-lib/src/widgets/sale/components/FundingRouteSelect/FundingRouteSelect.tsx, packages/checkout/widgets-lib/src/widgets/sale/components/PurchaseMenuItem/PurchaseMenuItem.tsx, packages/checkout/widgets-lib/src/widgets/sale/context/SaleContextProvider.tsx, packages/checkout/widgets-lib/src/widgets/sale/views/FundWithSmartCheckout.tsx, packages/checkout/widgets-sample-app/src/App.tsx, packages/checkout/widgets-sample-app/src/components/ui/sale/sale.tsx
Accept collection name as param, this is needed on one of smart checkout flow views
=> [GPR-258] Sale Widget | Add collection name

packages/checkout/sdk-sample-app/src/components/Listings.tsx, packages/checkout/sdk-sample-app/src/components/Sell.tsx, packages/checkout/sdk/src/smartCheckout/sell/sell.test.ts, packages/checkout/sdk/src/smartCheckout/sell/sell.ts, packages/checkout/sdk/src/types/smartCheckout.ts
Add the [expiry time](https://docs.immutable.com/sdk-references/ts-immutable-sdk/0.39.5/interfaces/_imtbl_sdk.orderbook.preparelistingparams#orderExpiry) in the `sell()` endpoint.
Ability to set the expiry time for any sell order via Checkout (SmartCheckout)
New prop in the `SellParams` type.
=> feat: WT-2044 orderExpiry in SmartCheckout

packages/checkout/widgets-sample-app/src/components/ui/sale/sale.tsx
=> [Sale Widget] Revert demo app sample qty

packages/checkout/sdk-sample-app/package.json, packages/checkout/widgets-lib/package.json, packages/checkout/widgets-sample-app/package.json, packages/passport/sdk-sample-app/package.json, packages/provider/src/sample-app/package.json, sdk/package.json, yarn.lock
updates biome, to fix a small z-layer issue inside of the AppHeaderBar
none. 
biome/react and biome/design-tokens package versions
https://immutable.atlassian.net/browse/DS-691
https://github.com/immutable/ts-immutable-sdk/assets/1452237/f6531e06-eca8-40bf-9059-c4b4881cbb8f
=> fix: DS-691 update biome

package.json, packages/checkout/widgets-lib/package.json, packages/config/src/index.ts, packages/internal/metrics/.eslintrc, packages/internal/metrics/.gitignore, packages/internal/metrics/README.md, packages/internal/metrics/jest.config.ts, packages/internal/metrics/package.json, packages/internal/metrics/rollup.config.js, packages/internal/metrics/src/details.ts, packages/internal/metrics/src/identify.ts, packages/internal/metrics/src/index.ts, packages/internal/metrics/src/initialise.ts, packages/internal/metrics/src/track.ts, packages/internal/metrics/src/utils/browser.ts, packages/internal/metrics/src/utils/checkEnv.ts, packages/internal/metrics/src/utils/constants.ts, packages/internal/metrics/src/utils/errorBoundary.test.ts, packages/internal/metrics/src/utils/errorBoundary.ts, packages/internal/metrics/src/utils/localStorage.test.ts, packages/internal/metrics/src/utils/localStorage.ts, packages/internal/metrics/src/utils/request.ts, packages/internal/metrics/src/utils/state.ts, packages/internal/metrics/tsconfig.json, yarn.lock
Adds some metric tracking functions to the SDK to get some feedback.
No external facing changes.
=> chore: adding metrics

packages/checkout/widgets-lib/src/components/Transactions/TransactionList.tsx, packages/checkout/widgets-lib/src/components/Transactions/Transactions.tsx
NOJIRA
fixing up the wallet address in the bridge transactions screen to come from the connected provider
=> fix wallet address in bridge transactions

packages/config/src/index.ts, packages/game-bridge/.eslintrc, packages/game-bridge/package.json, packages/game-bridge/src/index.ts, packages/game-bridge/tsconfig.json, packages/internal/metrics/src/identify.ts, packages/internal/metrics/src/index.ts, packages/internal/metrics/src/track.ts, packages/internal/metrics/src/utils/state.ts, packages/passport/sdk/package.json, packages/passport/sdk/src/Passport.ts, yarn.lock
Gathering some more metrics for SDK version and usage.
=> gathering more metrics

packages/checkout/sdk/package.json, packages/checkout/sdk/src/sdk.ts, packages/internal/metrics/src/index.ts, packages/internal/metrics/src/initialise.ts, packages/internal/metrics/src/utils/checkEnv.ts, packages/internal/metrics/src/utils/constants.ts, yarn.lock
Adds the SDK version as a detail to get more information about what version of SDK is being used.
None to customer.
=> note SDK version as a detail

packages/checkout/widgets-lib/src/lib/hooks/useBalance.ts
Increase the REFRESH_BALANCE_INTERVAL_MS value to make Checkout less chatty and reduce load on backend services
Balance refresh frequency
=> fix: [NOJIRA] increase REFRESH_BALANCE_INTERVAL_MS

packages/checkout/widgets-lib/src/lib/testUtils.ts, packages/checkout/widgets-lib/src/locales/en.json, packages/checkout/widgets-lib/src/locales/ja.json, packages/checkout/widgets-lib/src/locales/ko.json, packages/checkout/widgets-lib/src/locales/zh.json, packages/checkout/widgets-lib/src/views/error/ServiceUnavailableErrorView.tsx, packages/checkout/widgets-lib/src/views/top-up/TopUpView.cy.tsx, packages/checkout/widgets-lib/src/views/top-up/TopUpView.tsx, packages/checkout/widgets-lib/src/widgets/swap/SwapWidgetRoot.tsx
Updated Checkout copy for the Top Up view and Service Unavailable view.
Copy for the Checkout screens in English, Japanse, Korean, and Chinese
=> fix: [NOJIRA] Change Checkout copy

packages/passport/sdk-sample-app/scripts/updateSdkVersion.sh
script change to work with build pipeline
=> fixed build tool failing

packages/orderbook/src/openapi/sdk/models/FulfillmentDataRequest.ts, packages/orderbook/src/openapi/sdk/services/OrdersService.ts
=> Generate new orderbook openapi client with additional filter param

packages/checkout/sdk/src/balances/balances.test.ts, packages/checkout/sdk/src/tokens/tokens.test.ts
=> [No jira] Fix: unit tests

packages/game-bridge/src/index.ts
Analytics tracking to the game bridge
- Moved around the order of functions
- Analytics to game bridge
- Analytics event names from snake case to camel case
- Order of functions
=> feat: game bridge analytics [DX-2646]

packages/game-bridge/src/index.ts
Added the time it takes to finish each game bridge call to the analytics event
=> chore: [DX-2671] add time to game bridge track function call events

packages/checkout/sdk/src/config/remoteConfigFetcher.test.ts, packages/checkout/sdk/src/config/remoteConfigFetcher.ts, packages/checkout/sdk/src/types/config.ts
=> feat: WT-2151 Add connect to RemoteConfiguration type

packages/passport/sdk/src/zkEvm/user/registerZkEvmUser.ts
This PR parallelizes the async calls in `registerZkEvmUser` for the sake of performance.
- Passport: Some async calls within the zkEvm registration logic have now been parallelized. Consumers should see slight performance improvements.
=> feat: ID-1422 Parallelize async calls in registerZkEvmUser

packages/checkout/sdk/src/widgets/definitions/configurations/widget.ts
https://immutable.atlassian.net/browse/WT-2165
=> feat: WT-2165 Add projectId and metadata options for walletConnect

packages/checkout/widgets-lib/src/components/ConnectLoader/ConnectLoader.tsx
Fix infinite loading for Swap/onRamp/Wallet widgets when wallet-provider-name is provided as input parameter
Fix infinite loading for Swap/onRamp/Wallet widgets when wallet-provider-name is provided as input parameter
=> fix: [wt-2107] Update connection status state

packages/checkout/widgets-lib/src/factory.ts, packages/checkout/widgets-lib/src/lib/walletConnect.ts, packages/checkout/widgets-sample-app/src/components/ui/marketplace-orchestrator/MainPage.tsx
https://immutable.atlassian.net/browse/WT-2159
=> feat: WT-2159 Sync SDK theme with WalletConnect theme

packages/checkout/widgets-lib/src/widgets/swap/GeoblockLoader.cy.tsx, packages/checkout/widgets-lib/src/widgets/swap/GeoblockLoader.tsx, packages/checkout/widgets-lib/src/widgets/swap/SwapWidgetRoot.tsx
Moves the call to isSwapAvailable inside the render to show a loader instead of nothing while waiting for the call to resolve.
=> refactor: WT-1875 Move fetching swap availability logic within render

packages/passport/sdk-sample-app/src/components/zkevm/EthSendTransactionExamples/NFTApproval.tsx, packages/passport/sdk-sample-app/src/components/zkevm/EthSendTransactionExamples/index.ts
https://github.com/immutable/ts-immutable-sdk/assets/3668156/42b9fe99-da17-4a00-b280-2070061759bd
* Passport Sample App- Add the NFT approve example\
=> [ID-1438] passport sample app - NFT approve example

packages/config/src/index.ts
Remove type level complexity on setting api keys.
Remove type level complexity on setting api keys
=> chore: remove type level complexities on api keys

packages/checkout/sdk/src/smartCheckout/sell/sell.ts
Hotfix for Passport Listings through Checkout
=> fix: Smart Checkout Passport Listings

packages/checkout/widgets-lib/src/widgets/bridge/components/WalletItem.tsx, packages/checkout/widgets-lib/src/widgets/connect/components/WalletItem.tsx
Visual fixes for wallet listings
Fixes to wallet icon listing alignments
=> fix: [NO-JIRA] Updates to addess wallet listing icon alignments

packages/checkout/widgets-lib/src/components/NetworkSwitchDrawer/NetworkSwitchDrawer.tsx
Updating the switch network images in the drawer.
=> feat: update network images

packages/passport/sdk/src/Passport.int.test.ts, packages/passport/sdk/src/mocks/zkEvm/msw.ts, packages/passport/sdk/src/zkEvm/relayerClient.test.ts, packages/passport/sdk/src/zkEvm/relayerClient.ts, packages/passport/sdk/src/zkEvm/sendTransaction.test.ts, packages/passport/sdk/src/zkEvm/sendTransaction.ts, packages/passport/sdk/src/zkEvm/signTypedDataV4.test.ts, packages/passport/sdk/src/zkEvm/signTypedDataV4.ts, packages/passport/sdk/src/zkEvm/user/registerZkEvmUser.test.ts, packages/passport/sdk/src/zkEvm/user/registerZkEvmUser.ts, packages/passport/sdk/src/zkEvm/walletHelpers.test.ts, packages/passport/sdk/src/zkEvm/walletHelpers.ts, packages/passport/sdk/src/zkEvm/zkEvmProvider.test.ts, packages/passport/sdk/src/zkEvm/zkEvmProvider.ts
https://immutable.atlassian.net/wiki/spaces/PA/pages/2451111964/Passport+eth+chainId
- Cache layer for `eth_chainId`
- `ZkEvmProvider` instance of `StaticJsonRpcProvider`
=> feat: cache eth_chainId

packages/checkout/widgets-lib/src/widgets/sale/functions/smartCheckoutUtils.test.ts, packages/checkout/widgets-lib/src/widgets/sale/functions/smartCheckoutUtils.ts
Fix failure to allow payments without gas when using a passport wallet
=> fix: [Sale Widget] Unable to purchase without gas using a passport wallet

packages/checkout/widgets-lib/src/widgets/sale/functions/utils.ts, packages/checkout/widgets-lib/src/widgets/sale/hooks/useSignOrder.ts
- Decode transaction ID from hex to string
=> fix: [GASBT-7][Sale Widget] Fix transaction end events details

packages/x-provider/src/signable-actions/deposit-actions/depositERC721.test.ts, packages/x-provider/src/signable-actions/deposit-actions/depositEth.test.ts, packages/x-provider/src/signable-actions/deposit.test.ts, packages/x-provider/src/signable-actions/exchanges.test.ts, packages/x-provider/src/signable-actions/trades.test.ts, packages/x-provider/src/signable-actions/withdrawal-actions/getEncodeAssetInfo.test.ts, packages/x-provider/src/signable-actions/withdrawal-actions/prepareWithdrawal.test.ts, packages/x-provider/src/signable-actions/withdrawal.test.ts
Remove core SDK mocks from tests
No other code changes
=> chore: Remove core SDK mocks from tests

packages/passport/sdk-sample-app/package.json, packages/passport/sdk-sample-app/src/components/imx/BulkTransfer.tsx, packages/passport/sdk-sample-app/src/components/imx/MakeOfferModal.tsx, packages/passport/sdk-sample-app/src/components/imx/Order.tsx, packages/passport/sdk-sample-app/src/components/imx/Trade.tsx, packages/passport/sdk-sample-app/src/components/imx/Transfer.tsx, packages/passport/sdk-sample-app/src/components/imx/ViewOffersModal.tsx, packages/passport/sdk-sample-app/src/context/ImmutableProvider.tsx, packages/passport/sdk-sample-app/src/types/index.ts, packages/passport/sdk/package.json, packages/passport/sdk/src/errors/passportError.ts, packages/passport/sdk/src/starkEx/getStarkSigner.test.ts, packages/passport/sdk/src/starkEx/getStarkSigner.ts, packages/passport/sdk/src/starkEx/passportImxProvider.test.ts, packages/passport/sdk/src/starkEx/passportImxProvider.ts, packages/passport/sdk/src/types.ts, packages/x-client/src/config/index.ts, yarn.lock
Reverts immutable/ts-immutable-sdk#1583
=> Revert "chore: [DX-2714]: remove core sdk from passport"

.github/workflows/build-lint-typecheck-test.yaml, packages/passport/sdk-sample-app/src/components/imx/BulkTransfer.tsx, packages/passport/sdk-sample-app/src/components/imx/EthBalance.tsx, packages/passport/sdk-sample-app/src/components/imx/Order.tsx, packages/passport/sdk-sample-app/src/components/imx/Trade.tsx, packages/passport/sdk-sample-app/src/components/imx/Transfer.tsx, packages/passport/sdk-sample-app/src/components/imx/ViewOffersModal.tsx, packages/passport/sdk-sample-app/src/context/ImmutableProvider.tsx, packages/x-client/src/config/index.ts
Remove core SDK as a dependency of passport
This is a redo of #1583 , which [broke CI on main](https://github.com/immutable/ts-immutable-sdk/actions/runs/8335713670/job/22811682194), because the passport sample app build broke.
This PR also adds the passport sample app build to PR CI to prevent future recurrences.
=> chore: [DX-2714] remove core sdk from passport

packages/game-bridge/src/index.ts
Added Passport ID function to the game bridge so Game SDK users no longer need to decode it from the access or ID token.
=> feat: [DX-2756] add get passport id to game bridge

packages/passport/sdk-sample-app/src/components/zkevm/EthSendTransactionExamples/SeaportFulfillAvailableAdvancedOrders.tsx, packages/passport/sdk-sample-app/src/components/zkevm/EthSendTransactionExamples/index.ts, packages/passport/sdk-sample-app/src/context/ImmutableProvider.tsx
This PR adds a Seaport `fulfillAvailableAdvancedOrders` example to the Passport sample application.
- Passport: Added Seaport `fulfillAvailableAdvancedOrders` example to sample application
https://github.com/immutable/ts-immutable-sdk/assets/9940216/80eac540-b7a4-480f-b1d4-6f0c17a25e70
=> chore: ID-1495 Added fulfillAvailableAdvancedOrders example to Passport sample app

packages/passport/sdk-sample-app/src/context/ImmutableProvider.tsx
Fixed issue with orderbook calling sandbox when using dev
actions from using orderbook is propagated  correctly
api  route config for dev
=> chore: ID-1514 Fixed issue with orderbook calling sandbox when using dev

.github/workflows/build-lint-typecheck-test.yaml, .github/workflows/functional-tests-imx.yml, .github/workflows/functional-tests-zkevm.yml, .github/workflows/playwright.yml, .github/workflows/secret-scan.yaml
This updates all workflows that run on pull requests to also run as part of a merge queue to main.
No other changes to code
=> chore: [DX-2681] add support for merge queues to CI workflows

packages/checkout/widgets-lib/src/widgets/swap/components/SwapForm.tsx
Swap widget fix when clicking max button twice in a row the to amount resets to zero.
[GASBT-15](https://immutable.atlassian.net/browse/GASBT-15)
Clicking swap widget max button consecutively will now trigger a quote refetch and set the correct to amount.
[GASBT-15]: https://immutable.atlassian.net/browse/GASBT-15?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: [GASBT-15] Swap widget max button consecutive clicks zero to amount

packages/passport/sdk-sample-app/src/components/zkevm/EthSendTransactionExamples/DefaultTransaction.tsx, packages/passport/sdk-sample-app/src/components/zkevm/EthSendTransactionExamples/NFTApproval.tsx, packages/passport/sdk-sample-app/src/components/zkevm/EthSendTransactionExamples/SeaportFulfillAvailableAdvancedOrders.tsx, packages/passport/sdk-sample-app/src/components/zkevm/EthSendTransactionExamples/SpendingCapApproval.tsx, packages/passport/sdk-sample-app/src/components/zkevm/EthSendTransactionExamples/TransferERC20.tsx, packages/passport/sdk-sample-app/src/components/zkevm/EthSendTransactionExamples/index.ts
Adds both the ERC20 `transfer` and the `transferFrom` methods to the sample-app for testing
https://github.com/immutable/ts-immutable-sdk/assets/122326421/89611bbb-1910-432e-a7e3-0b7178189645
https://github.com/immutable/ts-immutable-sdk/assets/122326421/cc2ac0c1-47de-4073-bf83-4dec186d308d
=> feat: ID-1563 Add ERC20 transfer methods to the sample app

packages/checkout/widgets-lib/src/context/view-context/SaleViewContextTypes.ts, packages/checkout/widgets-lib/src/widgets/sale/SaleWidget.tsx, packages/checkout/widgets-lib/src/widgets/sale/context/SaleContextProvider.tsx, packages/checkout/widgets-lib/src/widgets/sale/views/FundWithSmartCheckout.tsx, packages/checkout/widgets-lib/src/widgets/sale/views/PaymentMethods.tsx
Show order summary view if `multicurrency=true` from config
=> feat: [Sale Widget] Show order summary if multicurrency

packages/passport/sdk-sample-app/src/components/zkevm/EthSendTransactionExamples/SeaportCreateListing.tsx, packages/passport/sdk-sample-app/src/components/zkevm/EthSendTransactionExamples/SeaportCreateListingDefault.tsx, packages/passport/sdk-sample-app/src/components/zkevm/EthSendTransactionExamples/SeaportCreateListingExample.ts, packages/passport/sdk-sample-app/src/components/zkevm/EthSignTypedDataV4Examples/index.ts
Additional examples for the SDK sample app for creating seaport listing message signings
=> feat: ID-1502: sample app examples for create seaport listing

packages/checkout/widgets-lib/src/components/SimpleLayout/SimpleLayout.tsx
Changes to simple layout to allow body styles to be extended
=> feat: [GPR-544][Sale Widget] Add body style overrides

packages/checkout/widgets-lib/src/widgets/sale/components/PaymentOption.tsx, packages/checkout/widgets-lib/src/widgets/sale/components/PaymentOptions.tsx
Add animation to payment options list
=> feat: [GPR-544][Sale Widget] Add animation to payment options list

packages/checkout/widgets-lib/src/widgets/sale/context/SaleContextProvider.tsx, packages/checkout/widgets-lib/src/widgets/sale/views/PaymentMethods.tsx
Can provide token address to sign when invoking `sign` method
=> feat: [GPR-544][Sale Widget]  Add optional token address on sign method

packages/checkout/widgets-lib/src/widgets/sale/functions/getTopUpViewData.test.ts, packages/checkout/widgets-lib/src/widgets/sale/functions/getTopUpViewData.ts
Add utility to get top up view attributes for an insufficient transaction requirement
=> feat: [GPR-544][Sale Widget] Utility to get top up view data from requirements

packages/checkout/sdk/src/sdk.test.ts, packages/checkout/sdk/src/sdk.ts, packages/checkout/sdk/src/smartCheckout/smartCheckout.test.ts, packages/checkout/sdk/src/smartCheckout/smartCheckout.ts, packages/checkout/sdk/src/types/smartCheckout.ts
Add `fundingRouteFullAmount` flag to override fractional balance check.
=> [feat] Add fundingRouteFullAmount flag to SM

packages/checkout/widgets-lib/src/widgets/connect/ConnectWidget.tsx, packages/checkout/widgets-lib/src/widgets/connect/connectWidgetEvents.ts
Fix to address the Connect widget WalletConnect success event types.
Updated connect success event walletProviderInfo for WalletConnect.
=> fix: Connect widget success event walletconnect types

packages/checkout/widgets-lib/src/locales/en.json, packages/checkout/widgets-lib/src/widgets/sale/components/CoinsDrawer.tsx, packages/checkout/widgets-lib/src/widgets/sale/components/CoinsDrawerItem.tsx, packages/checkout/widgets-lib/src/widgets/sale/components/OrderReview.tsx, packages/checkout/widgets-lib/src/widgets/sale/components/SelectCoinDropdown.tsx, packages/checkout/widgets-lib/src/widgets/sale/functions/fetchFundingBalances.ts, packages/checkout/widgets-lib/src/widgets/sale/hooks/useFundingBalances.ts, packages/checkout/widgets-lib/src/widgets/sale/views/OrderSummary.tsx
- Filter out settlement coins which required amount can't be confirm from received config
- Fix price display formatting
- Remove footer logo on summary screen
=> fix: [GPR-544][Sale Widget] Multicurrency balance check fixes

packages/passport/sdk-sample-app/src/components/zkevm/EthSendTransactionExamples/NFTTransfer.tsx, packages/passport/sdk-sample-app/src/components/zkevm/EthSendTransactionExamples/SeaportFulfillAvailableAdvancedOrders.tsx, packages/passport/sdk-sample-app/src/components/zkevm/EthSendTransactionExamples/index.ts, packages/passport/sdk-sample-app/src/context/ImmutableProvider.tsx
Signal Transfer: 
https://github.com/immutable/ts-immutable-sdk/assets/3668156/ed687747-3204-4d83-a074-93b525042318
Batch Transfer:
https://github.com/immutable/ts-immutable-sdk/assets/3668156/0db96318-1dc3-48de-8110-ddb800c11a35
=> [ID-11569]NFT Transfer

packages/checkout/widgets-lib/src/context/analytics-provider/SetupAnalytics.tsx
Remove hardcoded analytics key
=> chore: Remove hardcoded analytics key

packages/game-bridge/src/index.ts
Adding `getTransactionReceipt` function to the game bridge to be used in the Game SDKs.
Should not impact TS SDK users as the game bridge is not included in the standard build.
- `getTransactionReceipt` function from zkEVM provider to game bridge.
=> feat: [DX-2781] add getTransactionReceipt function to game bridge

packages/checkout/widgets-lib/src/lib/constants.ts
Fix the URLs for IMAGE_RESIZER_URL for checkout/widgets-lib
=> fix: IMAGE_RESIZER_URL for checkout/widgets-lib

packages/game-bridge/src/index.ts
Isolated getTransactionReceipt response from generic results due to Unity json parsing implementation
=> refactor: [DX-2784] modified getTransactionReceipt response output

packages/checkout/sdk-sample-app/package.json, packages/checkout/widgets-lib/package.json, packages/checkout/widgets-sample-app/package.json, packages/passport/sdk-sample-app/package.json, packages/x-provider/src/sample-app/package.json, sdk/package.json, yarn.lock
Update Biome to the latest to get the fix for CloudImage widths (DS-838).
=> TP-2312: Update Biome

packages/checkout/widgets-lib/src/components/Fees/Fees.tsx, packages/checkout/widgets-lib/src/components/FeesBreakdown/FeesBreakdown.tsx, packages/checkout/widgets-lib/src/components/FeesBreakdown/FeesBreakdownStyles.tsx, packages/checkout/widgets-lib/src/locales/en.json, packages/checkout/widgets-lib/src/locales/ja.json, packages/checkout/widgets-lib/src/locales/ko.json, packages/checkout/widgets-lib/src/locales/zh.json, packages/checkout/widgets-lib/src/widgets/bridge/functions/BridgeFees.ts, packages/checkout/widgets-lib/src/widgets/swap/components/SwapForm.tsx, packages/checkout/widgets-lib/src/widgets/swap/functions/swapFees.test.ts, packages/checkout/widgets-lib/src/widgets/swap/functions/swapFees.ts
Processes the swap fees by converting a swap quote into formatted fee line items.
[CM-521](https://immutable.atlassian.net/browse/CM-521)
[CM-521]: https://immutable.atlassian.net/browse/CM-521?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: [CM-521] Implementation to process swap fees

packages/checkout/widgets-lib/src/widgets/swap/functions/processGasFree.test.ts, packages/checkout/widgets-lib/src/widgets/swap/functions/processGasFree.ts
Clears the swap quote gas fees for Passport gas free users.
[CM-521](https://immutable.atlassian.net/browse/CM-521)
[CM-521]: https://immutable.atlassian.net/browse/CM-521?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: [CM-521] Clears the swap quote gas fees for Passport gas free users

packages/passport/sdk/src/authManager.test.ts, packages/passport/sdk/src/authManager.ts
Further reverts changes to logout
=> fix: AuthManager logout

packages/internal/bridge/sdk/src/lib/axelar.test.ts, packages/internal/bridge/sdk/src/lib/axelarUtils.ts, packages/internal/bridge/sdk/src/lib/utils.ts, packages/internal/bridge/sdk/src/tokenBridge.ts
Refactor some of the functionality in `getDynamicWithdrawGas`.
- New file `lib/axelarUtils.ts`
- Made a few functions that aim to clarify some parts of the `getDynamicWithdrawGas` function
=> refactor:[SMR-2723] generate destination execute call

packages/passport/sdk/src/zkEvm/sendTransaction.test.ts, packages/passport/sdk/src/zkEvm/sendTransaction.ts, packages/passport/sdk/src/zkEvm/walletHelpers.ts
Strictly speaking encoding of the message subdigest appears not to be required, so we removed it.
=> refactor: Feature/id id 1598 fee option optimisation alt

packages/checkout/sdk-sample-app/package.json, packages/checkout/widgets-lib/package.json, packages/checkout/widgets-sample-app/package.json, packages/passport/sdk-sample-app/package.json, packages/x-provider/src/sample-app/package.json, sdk/package.json, yarn.lock
Upgrade biome to v0.23.3 to address build issue with `sdk-sample-app`.
`sdk-sample-app` build issue.
=> fix: Upgrade biome to v0.23.3 in `sdk-sample-app`

packages/orderbook/src/config/config.ts
=> TD1332 Add ImmutableSignedZoneV2 to default zone used in sandbox and prod

packages/checkout/widgets-lib/src/widgets/sale/context/SaleContextProvider.tsx
Remove showing loading screen when CC option is chosen from the balance drawer.
=> [fix][sale widget] Fix loading screen for cc warning

packages/checkout/widgets-lib/src/components/Fees/Fees.tsx, packages/checkout/widgets-lib/src/components/FeesBreakdown/FeesBreakdown.tsx, packages/checkout/widgets-lib/src/lib/utils.ts, packages/checkout/widgets-lib/src/widgets/swap/functions/swapFees.ts
Improvements to fee display
- Update symbols and extend token info type
- Improve utils to allow defaults to be set via arguments. Increases the utils reusability in different app scenarios.
=> chore: [CM-638][Swap Widget] Misc improvements to fee display

packages/minting-backend/minting-sample-app/backend/package.json
Use the correct sdk version in the sample app
=> refactor: update sdk version in sample app

packages/checkout/sdk-sample-app/package.json, packages/checkout/sdk-sample-app/src/components/CheckConnection.tsx, packages/checkout/sdk-sample-app/src/components/Connect.tsx, packages/checkout/sdk-sample-app/src/components/Provider.tsx, packages/checkout/sdk-sample-app/src/passport.tsx
Small update to Checkout SDK sample app to support Passport provider
Injected providers options and Passport provider to Checkout SDK sample app
=> chore: [NO-JIRA] Updates to Checkout SDK sample app to support Passport provider

packages/passport/sdk/src/starkEx/passportImxProvider.test.ts, packages/passport/sdk/src/starkEx/passportImxProvider.ts, packages/passport/sdk/src/starkEx/workflows/order.test.ts, packages/passport/sdk/src/starkEx/workflows/order.ts, packages/passport/sdk/src/starkEx/workflows/trades.test.ts, packages/passport/sdk/src/starkEx/workflows/trades.ts, packages/passport/sdk/src/starkEx/workflows/transfer.test.ts, packages/passport/sdk/src/starkEx/workflows/transfer.ts
[Jira ticket](https://immutable.atlassian.net/browse/ID-1585)
Moved initialisation of starkex signers after the confirmation popup is initialised, in order to avoid possible popup blocking issues
=> signers now retrieved after confirmation popup is opened

packages/checkout/sdk/src/widgets/definitions/parameters/sale.ts, packages/checkout/widgets-lib/src/widgets/sale/SaleWidget.tsx, packages/checkout/widgets-lib/src/widgets/sale/SaleWidgetRoot.tsx, packages/checkout/widgets-lib/src/widgets/sale/context/SaleContextProvider.tsx, packages/checkout/widgets-lib/src/widgets/sale/hooks/useQuoteOrder.ts, packages/checkout/widgets-sample-app/src/components/ui/sale/sale.tsx
https://immutable.atlassian.net/browse/CM-661
=> feat:[CM-661][Sale Widget] Introduce a base currency override param to Primary Sales

packages/checkout/widgets-lib/src/widgets/sale/components/CoinsDrawerItem.tsx, packages/checkout/widgets-lib/src/widgets/sale/components/OrderItem.tsx, packages/checkout/widgets-lib/src/widgets/sale/components/SelectCoinDropdown.tsx
=> fix:[CM-667][Sale Widget]Remove remaining instances of image resizer usage in Primary Sales

packages/minting-backend/sdk/package.json, packages/minting-backend/sdk/src/analytics/index.ts, packages/minting-backend/sdk/src/config/index.ts, packages/minting-backend/sdk/src/index.ts, packages/minting-backend/sdk/src/minting.ts, packages/minting-backend/sdk/src/persistence/pg/postgres.ts, packages/minting-backend/sdk/src/persistence/prismaSqlite/sqlite.ts, yarn.lock
Add configuration for Minting Backend package.
=> feat: add config for minting backend

packages/internal/bridge/sdk/src/lib/tenderly.test.ts, packages/internal/bridge/sdk/src/lib/tenderly.ts, packages/internal/bridge/sdk/src/tokenBridge.ts
Move submitTenderlySimulations into separate file
- new file `lib/tenderly.ts` and new test file `lib/tenderly.test.ts`
- Tests for `submitTenderlySimulations`.
- Moved `submitTenderlySimulations` into `lib/tenderly.ts`
=> refactor:[SMR-2735] Move submitTenderlySimulations into separate file + tests

packages/checkout/sdk-sample-app/src/components/PassportLoginCallback.tsx, packages/checkout/sdk-sample-app/src/index.tsx
The Checkout sample app was recently updated to integrate with Passport but was missing the login call back function to work locally. This PR patches the missing callback component.
=> TD-1359: chore: add login callback to checkout sample app.

packages/checkout/widgets-lib/src/widgets/sale/utils/pricing.test.ts, packages/checkout/widgets-lib/src/widgets/sale/utils/pricing.ts
Fix calculation for unknown coins prices from USD conversion rate
=> fix: [Sale Widget] Price conversion calculation

packages/game-bridge/README.md
Added README to the game bridge package on how to build index files. This is to link it to the Unity FAQ page on how to reuse our index file for custom engines.
=> [DX-2774] docs: game-bridge readme

packages/checkout/widgets-lib/src/widgets/bridge/views/MoveInProgress.tsx
- Update checkout transfer success modal body
- Remove new lines when transfer
=> fix: ID-1776 Update checkout transfer success modal body

packages/checkout/widgets-lib/src/context/handover-context/HandoverContext.ts, packages/checkout/widgets-lib/src/context/handover-context/HandoverProvider.tsx, packages/checkout/widgets-lib/src/lib/hooks/useHandover.ts, packages/checkout/widgets-lib/src/widgets/bridge/BridgeWidgetRoot.tsx, packages/checkout/widgets-lib/src/widgets/connect/ConnectWidgetRoot.tsx, packages/checkout/widgets-lib/src/widgets/on-ramp/OnRampWidgetRoot.tsx, packages/checkout/widgets-lib/src/widgets/sale/SaleWidgetRoot.tsx, packages/checkout/widgets-lib/src/widgets/swap/SwapWidgetRoot.tsx, packages/checkout/widgets-lib/src/widgets/wallet/WalletWidgetRoot.tsx
Add Handover context, provider, and `useHandover` hook to facilitate handover screens.
=> [feat] cm 673 handover provider

packages/checkout/sdk/src/smartCheckout/sell/sell.ts
=> TD1453 fix type issue

.github/workflows/secret-scan.yaml
This is a temporary workaround to https://github.com/gitleaks/gitleaks-action/issues/154
No code changes. Just pin to a specific version of gitleaks until  https://github.com/gitleaks/gitleaks-action/issues/154 is resolved
=> chore: fix broken gitleaks workflow

packages/orderbook/src/openapi/sdk/models/FillStatus.ts, packages/orderbook/src/openapi/sdk/models/ProtocolData.ts, packages/orderbook/src/openapi/sdk/services/OrdersService.ts
updates open API spec to include new query param on trades endpoint
=> chore: [TD-1424] update oapi spec

sdk/package.json, sdk/scripts/updateDependencies.js
Dependency required for previous node-gyp fix was not being included in the NPM package due to the update dependency script. This manually adds the required dependency. 
Required dependency should now be added to the published SDK package.json file now.
- Build script to include missing dependency
=> fix: node-gyp dependency fix

packages/game-bridge/package.json, packages/game-bridge/src/index.ts, yarn.lock
Add send transaction with confirmation to the game bridge.
=> [DX-2789] feat: add send transaction with confirmation to game bridge

packages/minting-backend/sdk/src/analytics/index.ts, packages/minting-backend/sdk/src/index.ts, packages/minting-backend/sdk/src/minting.ts, samples/minting-backend-with-postgres/index.ts
Add error tracking in minting backend.
=> add error tracking to minting backend

packages/checkout/sdk/src/smartCheckout/buy/buy.ts, packages/checkout/sdk/src/smartCheckout/sell/sell.ts
[Jira](https://immutable.atlassian.net/browse/CM-702)
Tracking to initiation of the SmartCheckout Buy & Sell functions
=> chore: CM-702 Add tracking to Checkout SDK Buy/Sell functions

packages/checkout/widgets-lib/src/widgets/sale/components/CoinsDrawer.tsx, packages/checkout/widgets-lib/src/widgets/sale/components/CoinsDrawerItem.tsx, packages/checkout/widgets-lib/src/widgets/sale/components/OrderReview.tsx
Fix broken image fallback not displaying in coins drawer
=> fix; [Sale Widget] token image in coin drawer

packages/webhook/sdk/src/handler.ts
Fix a bug where webhook package can not parse subscription confirmation event
Fix a bug where webhook package can not parse subscription confirmation event
=> fix: webhook event parsing bug

packages/checkout/widgets-lib/src/locales/en.json
Updated swap header drawer labels to shorter mobile friendly versions.
[CM-697](https://immutable.atlassian.net/browse/CM-697)
Updated swap from and to header labels
[CM-697]: https://immutable.atlassian.net/browse/CM-697?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> refactor: [CM-697] Adjusted swap translations

packages/game-bridge/src/index.ts
Update game bridge with game engine SDK version.
No impact to SDK users.
=> [DX-2896] feat: engineSdkVersion to game bridge tracking

packages/blockchain-data/sdk/README.md, packages/blockchain-data/sdk/package.json
Add a quick start guide to the `blockchain-data` package README.
[Preview here](https://github.com/immutable/ts-immutable-sdk/blob/c53c8c3f101ad77d9fcd473f4e99b8abc1275fee/packages/blockchain-data/sdk/README.md)
=> Docs: [DX-2904] Update README of "blockchain-data" package

packages/orderbook/src/openapi/sdk/models/CancelledOrderStatus.ts
updates open API types to include changes made to order cancellation type
=> [chore][TD-1467]: update openapi spec

packages/checkout/widgets-lib/src/widgets/sale/context/SaleContextProvider.tsx, packages/checkout/widgets-lib/src/widgets/sale/hooks/useSignOrder.ts, packages/checkout/widgets-lib/src/widgets/sale/views/PayWithCoins.tsx
Better tracking of errors inside Sale Signing.
=> feat:Sale Widget Sign Errors

packages/config/README.md
Add a new README to the config package
Preview [here](https://github.com/immutable/ts-immutable-sdk/blob/e718d10e3cddc0a7e0b4d7770e0b746f0e9fad43/packages/config/README.md)
=> Docs: [DX-2915] Add new README of "config" package

packages/checkout/README.md
Updates the documentation for the Checkout SDK folder
Preview [here](https://github.com/immutable/ts-immutable-sdk/blob/faeedc9713e6c449243827d0398f6e08cc5947f9/packages/checkout/README.md)
=> Docs: [DX-2907] Update README of "checkout" package

README.md
Update root-level README.md for monorepo. 
Added the following information to the README.md:
- Getting started
- Indepth information for working with packages
- Package summaries
- Information on external samples
Readmes in each package will be fleshed out/added in following PRs.
Preview [here](https://github.com/immutable/ts-immutable-sdk/blob/ec90d137ccfeabcf1e7473d4874df133033b391c/README.md)
=> Docs: [DX-2892] Update README of Monorepo

.github/workflows/build-lint-typecheck-test.yaml, packages/minting-backend/sdk/package.json, packages/minting-backend/sdk/src/minting.ts, packages/minting-backend/sdk/src/persistence/pg/postgres.ts, packages/minting-backend/sdk/src/postgres.test.ts, yarn.lock
Add happy path tests for minting backend
add happy path tests for minting backend with a postgres persistence
=> refactor: add happy path tests for minting backend

packages/checkout/widgets-lib/src/components/FormComponents/SelectForm/SelectForm.cy.tsx, packages/checkout/widgets-lib/src/components/FormComponents/SelectForm/SelectForm.tsx, packages/checkout/widgets-lib/src/locales/en.json, packages/checkout/widgets-lib/src/locales/ja.json, packages/checkout/widgets-lib/src/locales/ko.json, packages/checkout/widgets-lib/src/locales/zh.json, packages/checkout/widgets-lib/src/widgets/swap/components/SwapForm.cy.tsx
Renaming from Coins to Tokens across multiple Widgets, see screenshots of local tests after the change
=> CM-716 - Rename Coins to Tokens in all widgets

packages/game-bridge/README.md
Update the documenation of the game-bridge to be consistent with the new style. Nothing specific added or changed
Preview [here](https://github.com/immutable/ts-immutable-sdk/blob/e4a2758b7b2a7180ac4d663fd8a802823c35e98f/packages/game-bridge/README.md)
=> Docs: [DX-2922] Update README of "game-bridge" package

packages/checkout/sdk-sample-app/package.json, packages/checkout/widgets-sample-app/package.json, packages/passport/sdk-sample-app/package.json, yarn.lock
adds biome peer deps to all sample apps.
https://immutable.atlassian.net/browse/DS-879
=> add biome peer deps to all sample apps

README.md, packages/checkout/README.md, packages/config/README.md, packages/game-bridge/README.md
Fix relative README links to and from the root README
=> README relative link fixes

packages/minting-backend/sdk/README.md, packages/minting-backend/sdk/package.json
Add a quick start guide and link to some more information about the package
Preview [here](https://github.com/immutable/ts-immutable-sdk/blob/445f87b4b196fb8276bf0415311bbadcbaa134f8/packages/minting-backend/sdk/README.md)
=> Docs: [DX-2927] Update README of "minting-backend" package

packages/orderbook/README.md, packages/orderbook/package.json
Update the orderbook README
Preview [here](https://github.com/immutable/ts-immutable-sdk/blob/ca4e2e9fc3431e32b3750f32e172594d896ea5a9/packages/orderbook/README.md)
=> Docs: [DX-2930] Update README of "orderbook" package

packages/game-bridge/scripts/updateSdkVersion.sh
[DX-2912](https://immutable.atlassian.net/browse/DX-2912)
Use non-alpha version tags in game bridge version update script during build.
- No impact to SDK or Game SDK users. The change only correctly tags the SDK and Game Bridge to use non-alpha tags.
[DX-2912]: https://immutable.atlassian.net/browse/DX-2912?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: game bridge version update script

packages/blockchain-data/sdk/README.md, packages/webhook/sdk/README.md
Webhooks package readme update.
Preview [here](https://github.com/immutable/ts-immutable-sdk/blob/eb8e40eb9bb74512bd42128e0dcf47039485f8f2/packages/webhook/sdk/README.md)
=> Docs: [DX-2933] Update README of "webhook" package

packages/checkout/widgets-lib/src/hooks/useMount.ts, packages/checkout/widgets-lib/src/views/top-up/TopUpView.tsx, packages/checkout/widgets-lib/src/widgets/sale/components/OrderReview.tsx, packages/checkout/widgets-lib/src/widgets/sale/views/OrderSummary.tsx
Trigger top up view & summary screen load events once.
=> fix: [CM-726][Sale Widget] Remove duplicated event triggers

packages/checkout/widgets-lib/src/context/crypto-fiat-context/CryptoFiat.ts
=> fix: Incorrect param name in crypto fiat context

packages/x-client/README.md
Basic README for x-client package with quick start guide for devs
Preview [here](https://github.com/immutable/ts-immutable-sdk/blob/b8a2659063919e10e0f06e5c77818e6458099b30/packages/x-client/README.md)
=> Docs: [DX-2939] Add new README for "x-client" package

packages/x-provider/README.md
Update readme of x-provider package to provide devs with quick start guide.
Preview [here](https://github.com/immutable/ts-immutable-sdk/blob/cbd6ea6f7ae46cab67425ca2b25f9bbe205ff4e7/packages/x-provider/README.md)
=> Docs: [DX-2940] Update README of "x-provider" package

packages/internal/generated-clients/README.md, packages/internal/generated-clients/openapitools.json, packages/internal/generated-clients/package.json, yarn.lock
Update README of internal generated-clients package.
Preview [here](https://github.com/immutable/ts-immutable-sdk/blob/31c0edf29b5b6e7d390a724f9444e8149a9ec1c0/packages/internal/generated-clients/README.md)
=> Docs: [DX-2943] Update README of "generated-clients" package

packages/internal/bridge/sdk/package.json, packages/internal/bridge/sdk/src/tokenBridge.ts
There is a type error in the vscode on the line that's changed in this PR. this is to fix that and add typecheck script to catch this kind of situation in the future.
=> chore: make tsc happy on typechecking

packages/checkout/widgets-lib/src/widgets/connect/components/WalletItem.tsx
Display `Recommended` badge on top of wallet title on smaller screens. Previous behaviour was to collapse the badge, displaying only a small blue circle without the text.
=> chore: CM-694 - Adjust Recommended wallet badge for smaller screens

packages/game-bridge/README.md
Update the `game-bridge` README with proper build steps to ensure the SDK version string matches the latest SDK release. 
No impact to customers.
=> docs: add game bridge version update process

packages/passport/README.md, packages/passport/sdk-sample-app/package.json, packages/passport/sdk/package.json, yarn.lock
Fix concurrent passport dev commands and update README to represent change
=> fix: [DX-2945] Fix command for passport package running sdk and sample app in dev concurrently

packages/game-bridge/src/index.ts
Refactored the game bridge `status` field so that it is set to true if:
1. the function executed successfully without throwing an error
2. the response object we expect to return to the game engine is there
Also, I updated the error block to check if the error message is defined.
=> [DX-2954] refactor: game bridge status field

tests/func-tests/zkevm/step-definitions/shared.ts, tests/func-tests/zkevm/yarn.lock
Workaround multi-job flake in functional test suite. This is not a perfect fix, but it is likely to reduce the flake rate significantly
=> fix: workaround multi-job flake in functional test suite

packages/internal/metrics/src/initialise.ts, packages/internal/metrics/src/track.ts, packages/internal/metrics/src/utils/clock.ts
=> patch: handle clock skew

packages/checkout/sdk/src/widgets/definitions/parameters/sale.ts, packages/checkout/widgets-lib/src/components/Transak/TransakIframe.tsx, packages/checkout/widgets-lib/src/components/Transak/useTransakIframe.ts, packages/checkout/widgets-lib/src/widgets/sale/SaleWidget.tsx, packages/checkout/widgets-lib/src/widgets/sale/SaleWidgetRoot.tsx, packages/checkout/widgets-lib/src/widgets/sale/components/WithCard.tsx, packages/checkout/widgets-lib/src/widgets/sale/context/SaleContextProvider.tsx, packages/checkout/widgets-sample-app/src/App.tsx, packages/checkout/widgets-sample-app/src/components/ui/sale/sale.tsx
=> feat: CM-735 - Add parameter to disable fiat currencies on primary sales card payments

.github/scripts/check-team-membership.sh, .github/workflows/build-game-bridge.yaml, packages/game-bridge/scripts/updateSdkVersion.sh
Workflow to build the game bridge and create a PR in the Game SDK repo(s).
No impact to customers. The workflow is intended to be run by the SDK team only.
- Workflow to build the game bridge
=> feat: game bridge build workflow

packages/checkout/widgets-lib/src/components/NetworkSwitchDrawer/NetworkSwitchDrawer.tsx
- Bridge drawer `img` size
- Replace `png` with `svg` to make use of BIOME’s default image optimisation functionality
=> [NO JIRA] Fix/bridge drawer img resolution

examples/minting-backend-with-postgres/index.ts
Add code snippet comments to minting backend examples
=> [EXC-13] add doc code snippet comments

examples/minting-backend-with-postgres/index.ts, examples/passport/next-web3-modal/src/app/passport.ts
Add some comments to the examples which will be referred by docs
=> [EXC-16] update passport setup example

examples/minting-backend-with-postgres/index.ts, packages/passport/sdk/jest.config.ts, packages/passport/sdk/src/Passport.int.test.ts, packages/passport/sdk/src/Passport.test.ts, packages/passport/sdk/src/zkEvm/zkEvmProvider.test.ts
=> [EXC-18] passport doc snippet

packages/checkout/widgets-lib/src/widgets/sale/components/PaymentOptions.tsx
=> feat: Skip PaymentOptions screen if there is only one enabled option

packages/checkout/sdk/src/widgets/definitions/events/sale.ts
=> [NO-CHANGELOG][Sale Widget] Fix type import error

dev.sh, packages/passport/README.md, packages/passport/sdk-sample-app/package.json
=> fix dev mod for passport sample sdk

.github/workflows/build-game-bridge.yaml
=> fix: game bridge build workflow

packages/blockchain-data/sdk/src/blockchain-data.ts
Fix type for `listAllNFTOwners` method on Blockchain Data package
=> fix: Request type for listAllNftOwners method on Blockchain Data package

packages/checkout/widgets-lib/src/widgets/sale/utils/analytics.ts
Fix type error on sale widget analytics
=> [NO CHANGELOG][Sale Widget] fix type error

examples/passport/identity/src/app/page.tsx, examples/passport/identity/src/context/passport.tsx
=> [EXC-25] get linked addresses example

examples/passport/identity/src/app/page.tsx, examples/passport/identity/src/context/passport.tsx
=> [EXC-25] get user info example

packages/passport/sdk/src/zkEvm/zkEvmProvider.ts
Users might call `ethRequestAccounts` a lot. This causes this to get triggered more than required.
=> fix: change session activity trigger to reduce unintended multiple calls

packages/checkout/sdk/src/widgets/definitions/parameters/checkout.ts, packages/checkout/widgets-lib/src/widgets/BaseWidgetRoot.ts, packages/checkout/widgets-lib/src/widgets/checkout/CheckoutWidget.tsx, packages/checkout/widgets-lib/src/widgets/checkout/CheckoutWidgetRoot.tsx, packages/checkout/widgets-lib/src/widgets/checkout/functions/iframeParams.ts, packages/checkout/widgets-sample-app/src/components/ui/checkout/checkout.tsx
- Add types for checkout widget configuration 
- Receive and forward configuration values via query params
=> feat: [NO CHANGELOG][Checkout Widget] Forward configuration to checkout app thru iframe query params

.github/workflows/publish.yaml
Debugging publish workflow to see why checkout bundle is missing
=> debug publish

.github/workflows/publish.yaml, package.json
Try skip NX cache in publish to debug why checkout bundle is missing
=> try skip cache

packages/game-bridge/src/index.ts
Add version info to game bridge track error
=> [DX-3045] feat: add version info to track error

package.json
build did not include checkout browser bundle
=> skip nx cache in build

.github/workflows/passport-sdk-sample-app-deployment.yaml, packages/passport/sdk-sample-app/package.json, packages/passport/sdk-sample-app/scripts/updateSdkVersion.sh
make sure sdk version is in the deployed sample app.
=> fix: DX-3061 fix passport sample app deployment

.github/workflows/passport-sdk-sample-app-deployment.yaml
skip nx cache in passport sample app deployment
=> fix: skip nx cache in passport sample app deployment

packages/passport/sdk-sample-app/scripts/updateSdkVersion.sh
=> fix: passport sample app deployment fix

packages/checkout/sdk/src/widgets/definitions/events/checkout.ts, packages/checkout/sdk/src/widgets/definitions/events/connect.ts, packages/checkout/sdk/src/widgets/definitions/parameters/checkout.ts, packages/checkout/sdk/src/widgets/definitions/types.ts, packages/checkout/widgets-lib/src/widgets/checkout/CheckoutWidget.tsx, packages/checkout/widgets-lib/src/widgets/checkout/CheckoutWidgetEvents.ts, packages/checkout/widgets-sample-app/src/components/ui/checkout/checkout.tsx
Define checkout widget event types
=> [NO-CHANGELOG][Checkout Widget] Define event types

packages/checkout/widgets-lib/src/widgets/checkout/context/CheckoutContextProvider.tsx
* destroys PostMessageHandler on unmount
=> fix: destroys PostMessageHandler on unmount

packages/checkout/widgets-lib/src/widgets/bridge/components/BridgeReviewSummary.tsx, packages/checkout/widgets-lib/src/widgets/sale/components/CoinsDrawerItem.tsx, packages/checkout/widgets-lib/src/widgets/sale/components/OrderItem.tsx, packages/checkout/widgets-lib/src/widgets/sale/components/SelectCoinDropdown.tsx, packages/checkout/widgets-lib/src/widgets/wallet/components/BalanceItem/BalanceItem.tsx, yarn.lock
Fix various instances of `<MenuItem.PriceDisplay />` from specifying non-standard text
https://immutable.atlassian.net/browse/DS-917
MenuItem.PriceDisplay text sizing
=> fix: menuitem price display text

.github/workflows/build-game-bridge.yaml
The Version string in the Game Bridge was getting the wrong version tag set.
Game SDKs should report the correct version.
- Game bridge build workflow to set the correct SDK version.
=> fix: Set correct SDK version in the Game Bridge 

.github/workflows/build-game-bridge.yaml
=> fix: disable version string check to unblock build

.github/workflows/build-game-bridge.yaml, packages/game-bridge/package.json, packages/game-bridge/scripts/updateSdkVersion.sh
Main branch check in the `updateSdkVersion.sh` script wasn't working as expected. Disabling it to unblock building game bridge.
=> fix: game bridge build disable main branch check

README.md, packages/blockchain-data/sdk/README.md, packages/x-client/src/utils/stark/starkCurve.ts
Fix typos from this PR: https://github.com/immutable/ts-immutable-sdk/pull/2046
Looks like fork was causing CI to fail the above PR.
- Typos in SDK, Blockchain data, x-client READMEs
=> chore: typos in SDK, Blockchain Data, X Client READMEs

packages/checkout/sdk/src/widgets/definitions/events/checkout.ts, packages/checkout/widgets-sample-app/src/components/ui/checkout/checkout.tsx
=> [NO CHANGELOG][Checkout Widget] Update checkout event to include type and data

.github/workflows/publish-docs.yaml
Run workflow only on main branch changes.
=> fix: SDK reference docs workflow

.github/scripts/check-docs-version.sh, .github/workflows/publish-docs.yaml
=> fix: SDK reference docs alpha version check

packages/checkout/sdk/src/widgets/definitions/events/checkout.ts
=> [NO CHANEGELOG] [Checkout Widget] Add checkout connect success event and swap rejected event

packages/game-bridge/src/index.ts
Include request ID in `callFunction` track call.
- track request ID at the start of the game bridge call function
=> feat: game-bridge track request ID

packages/checkout/widgets-lib/src/lib/constants.ts, packages/checkout/widgets-lib/src/widgets/checkout/CheckoutWidget.tsx, packages/checkout/widgets-lib/src/widgets/checkout/context/CheckoutContextProvider.tsx
- FIx iframe url initialisation
- Remove hardcoded sandbox env
- Remove provider self initialisation
=> [NO CHANGELOG][Checkout Widget] Fix initial iframe url

packages/checkout/sdk/src/postMessageHandler/index.ts, packages/checkout/sdk/src/postMessageHandler/postMessageEventTypes.ts, packages/checkout/sdk/src/postMessageHandler/postMessageHandler.ts, packages/checkout/widgets-lib/src/components/ConnectLoader/ConnectLoader.tsx, packages/checkout/widgets-lib/src/lib/constants.ts, packages/checkout/widgets-lib/src/widgets/checkout/CheckoutWidget.tsx, packages/checkout/widgets-lib/src/widgets/checkout/context/CheckoutContext.ts, packages/checkout/widgets-lib/src/widgets/checkout/context/CheckoutContextProvider.tsx, packages/checkout/widgets-lib/src/widgets/checkout/context/ProviderRelay.ts, packages/checkout/widgets-lib/src/widgets/checkout/utils/config.ts, packages/checkout/widgets-lib/src/widgets/checkout/views/CheckoutAppIframe.tsx, packages/checkout/widgets-sample-app/src/components/ui/checkout/checkout.tsx
Refactor checkout widget post message handler to:
- Sync with a handshake
- Queue and flush events sent before handshake
- Broadcast events to all subscribers regardless of event type. Less coupled implementation, allows easier introduction of breaking changes between widget and app.
- Add a event logger
- Constructor params validation
Update checkout iframe app component
- Add initialisation error validation
- Add loader
=> [NO CHANGELOG][Checkout Widget] Refactor post message handler

packages/checkout/widgets-lib/src/lib/constants.ts
FAQs link was pointing to our support home. We're now pointing it directly to the FAQ page.
=> fix: Update FAQs link

packages/checkout/widgets-lib/src/lib/walletConnect.ts
Adding Wombat wallet to the list of whitelisted wallets for wallet. connect
=> feat: Adding Wombat Wallet to whitelist of wallet connect

packages/checkout/sdk/src/postMessageHandler/postMessageHandler.ts, packages/checkout/widgets-lib/src/widgets/checkout/views/CheckoutAppIframe.tsx, packages/checkout/widgets-sample-app/src/components/ui/checkout/checkout.tsx
- add permissions policy to checkout widget integration
=> Feat: [NO CHANGELOG][Checkout Widget] Add iframe permissions policy

packages/checkout/sdk/src/widgets/definitions/configurations/addFunds.ts, packages/checkout/sdk/src/widgets/definitions/events/addFunds.ts, packages/checkout/sdk/src/widgets/definitions/events/index.ts, packages/checkout/sdk/src/widgets/definitions/events/orchestration.ts, packages/checkout/sdk/src/widgets/definitions/events/widgets.ts, packages/checkout/sdk/src/widgets/definitions/parameters/addFunds.ts, packages/checkout/sdk/src/widgets/definitions/types.ts, packages/checkout/widgets-lib/src/context/analytics-provider/SegmentAnalyticsProvider.ts, packages/checkout/widgets-lib/src/context/view-context/AddFundsViewContextTypes.ts, packages/checkout/widgets-lib/src/factory.ts, packages/checkout/widgets-lib/src/widgets/add-funds/AddFundsRoot.tsx, packages/checkout/widgets-lib/src/widgets/add-funds/AddFundsWidget.tsx, packages/checkout/widgets-lib/src/widgets/add-funds/AddFundsWidgetEvents.ts, packages/checkout/widgets-sample-app/src/App.tsx, packages/checkout/widgets-sample-app/src/components/ui/add-funds/addFunds.tsx, packages/checkout/widgets-sample-app/src/index.tsx
Create Add Funds Widget by surfacing Top Up View
=> Feat: [NO CHANGELOG][Add Funds Widget] Create Add Funds Widget by surfacing Top Up View

packages/checkout/sdk/src/config/tokensFetcher.test.ts, packages/checkout/sdk/src/config/tokensFetcher.ts
Add getChainTokensConfig to get all the available chain and tokens
=> [CM-844] feat : Add getChainTokensConfig in TokenFetcher

packages/checkout/widgets-lib/src/widgets/add-funds/AddFundsWidget.tsx, packages/checkout/widgets-lib/src/widgets/add-funds/views/AddFunds.tsx, packages/checkout/widgets-sample-app/src/components/ui/add-funds/addFunds.tsx
This is the **steel thread** version which is currently missing proper biome components for input and menu item. 
Once those Biome components are ready, we will add them to the current design.
=> [NO CHANGELOG][Add Funds Widget]  Feat/add funds view

packages/checkout/widgets-lib/src/widgets/add-funds/views/AddFunds.tsx, packages/checkout/widgets-sample-app/src/components/ui/add-funds/addFunds.tsx
Fix swap and on ramp widget properties
=> [NO CHANGELOG][Add Funds Widget] Fix swap and on ramp widget properties

packages/checkout/widgets-lib/src/widgets/add-funds/components/OptionsDrawer.tsx, packages/checkout/widgets-lib/src/widgets/add-funds/views/AddFunds.tsx
=> [NO CHANGELOG][Add Funds Widget] Polish add funds view slice 2

packages/checkout/widgets-lib/src/widgets/add-funds/components/OptionsDrawer.tsx, packages/checkout/widgets-lib/src/widgets/add-funds/views/AddFunds.tsx, packages/checkout/widgets-sample-app/src/components/ui/add-funds/addFunds.tsx
=> [NO CHANGELOG][Add Funds Widget] Fix/add funds prefill token address

.github/workflows/publish.yaml
Fix Error: Failed to get ID token: Error message: Unable to get ACTIONS_ID_TOKEN_REQUEST_URL env variable
=> [NO CHANGELOG] fix: Error with NPM deploy attestations step

packages/checkout/widgets-lib/src/context/view-context/ViewContext.ts, packages/checkout/widgets-lib/src/widgets/add-funds/AddFundsWidget.tsx, packages/checkout/widgets-lib/src/widgets/add-funds/views/AddFunds.tsx
=> [NO CHANGELOG][Add Funds Widget] Add error handling to AddFunds

packages/passport/sdk/src/Passport.test.ts, packages/passport/sdk/src/Passport.ts, packages/passport/sdk/src/utils/metrics.test.ts, packages/passport/sdk/src/utils/metrics.ts
https://immutable.atlassian.net/browse/ID-2146
Adds further observability around root Passport SDK methods.
=> [ID-2146] chore: Add tracking metrics to root Passport class

packages/checkout/sdk/src/config/config.ts, packages/checkout/sdk/src/types/config.ts, packages/checkout/widgets-lib/src/widgets/checkout/CheckoutWidget.tsx, packages/checkout/widgets-lib/src/widgets/checkout/functions/iframeParams.ts
- Allow to override the environment or checkout app URL to facilitate development and manual flow testing
- Pass publishableKey, Language, and SDK Version as query params to checkout app
=> [NO CHANGELOG][Checkout Widget] Add support for env overrides

packages/game-bridge/src/index.ts
Change the game bridge `init` silent logout option to a boolean option.
- Only affects game SDKs integrating with the game bridge.
- No impact to external customers.
- Game bridge silent logout option from string to boolean.
=> refactor: game bridge silent logout option to boolean input

packages/passport/sdk/src/Passport.int.test.ts, packages/passport/sdk/src/magicAdapter.test.ts, packages/passport/sdk/src/magicAdapter.ts, packages/passport/sdk/src/utils/lazyLoad.test.ts, packages/passport/sdk/src/utils/lazyLoad.ts
Reverts immutable/ts-immutable-sdk#2110
=> Revert "[ID-2334] Defer preload for magic in Passport SDK"

packages/checkout/widgets-lib/src/widgets/checkout/CheckoutWidget.tsx, packages/checkout/widgets-lib/src/widgets/checkout/hooks/useMount.ts
Notify iframe when widget was initialised with a provider, only runs on first render
=> [NO CHANGELOG][Checkout Widget] Notify iframe if widget was initialised with a provider

packages/checkout/widgets-lib/package.json, yarn.lock
`widgets-sample-app` was breaking without this package.
=> [NO CHANGELOG][Checkout Widget]fix: Adds 0xsquid/squid-types package.

packages/checkout/widgets-lib/src/widgets/sale/SaleWidgetRoot.tsx
Merging duplicated items by increasing their qty, this will improve the Order Summary UI and payload sent to backend when user proceeds to sign.
=> [NO CHANGELOG][Sale Widget] Feat: Sale widget merge duplicated items

packages/checkout/widgets-lib/src/widgets/add-funds/AddFundsWidget.tsx, packages/checkout/widgets-lib/src/widgets/add-funds/context/AddFundsContext.ts, packages/checkout/widgets-lib/src/widgets/add-funds/functions/fetchChains.ts, packages/checkout/widgets-lib/src/widgets/add-funds/types.ts, packages/checkout/widgets-lib/src/widgets/add-funds/utils/config.ts
Get Chains and balances for add funds widget
Co-authored-by: Mimi Tran <mimi-imtbl@users.noreply.github.com>
=> [NO CHANGELOG][Add Funds Widget] Get Chains and balances

packages/checkout/widgets-lib/src/widgets/add-funds/hooks/useRoutes.ts
=> [NO CHANGELOG][Add Funds Widget] Create useRoutes

packages/checkout/widgets-lib/src/widgets/add-funds/AddFundsWidget.tsx, packages/checkout/widgets-lib/src/widgets/add-funds/functions/delay.ts, packages/checkout/widgets-lib/src/widgets/add-funds/hooks/useRoutes.ts, packages/checkout/widgets-lib/src/widgets/add-funds/types.ts, packages/checkout/widgets-lib/src/widgets/add-funds/views/AddFunds.tsx
=> [NO CHANGELOG][Add Funds Widget] Add funds update useRoutes to handle rate limiting

packages/checkout/widgets-lib/src/widgets/add-funds/hooks/useExecute.ts
=> [NO CHANGELOG][Add Funds Widget] Implement useExecute

packages/checkout/sdk/src/widgets/definitions/configurations/checkout.ts, packages/checkout/sdk/src/widgets/definitions/configurations/index.ts, packages/checkout/sdk/src/widgets/definitions/parameters/checkout.ts, packages/checkout/sdk/src/widgets/definitions/types.ts, packages/checkout/widgets-lib/src/context/event-target-context/EventTargetContext.ts, packages/checkout/widgets-lib/src/context/view-context/CheckoutWidgetViewContextTypes.ts, packages/checkout/widgets-lib/src/context/view-context/ViewContext.tsx, packages/checkout/widgets-lib/src/widgets/checkout/CheckoutWidget.tsx, packages/checkout/widgets-lib/src/widgets/checkout/CheckoutWidgetRoot.tsx, packages/checkout/widgets-lib/src/widgets/checkout/context/CheckoutContextProvider.tsx, packages/checkout/widgets-lib/src/widgets/checkout/functions/getViewShouldConnect.ts, packages/checkout/widgets-sample-app/src/components/ui/checkout/checkout.tsx
Render each widget within its own view passing params and config
=> [NO CHANGELOG][Checkout Widget] Feature: Render a widget per view

examples/blockchain-data/api-examples-with-node/get-token.ts, examples/blockchain-data/api-examples-with-node/index.ts, examples/blockchain-data/api-examples-with-node/list-activties-by-activity-type.ts, examples/blockchain-data/api-examples-with-node/list-all-nft-owners.ts, examples/blockchain-data/api-examples-with-node/list-chains.ts, examples/blockchain-data/api-examples-with-node/list-nft-owners-by-contract-address.ts, examples/blockchain-data/api-examples-with-node/list-nft-owners-by-token-id.ts, examples/blockchain-data/api-examples-with-node/list-nfts-by-collection.ts, examples/blockchain-data/api-examples-with-node/list-nfts.ts, examples/blockchain-data/api-examples-with-node/list-tokens.ts, examples/blockchain-data/test/blockchain-data.test.ts
Add code examples to be referenced in the Blockchain Data APIs docs
=> chore: [GMS-2175] Add blockchain data code examples

packages/checkout/sdk/src/widgets/definitions/parameters/checkout.ts, packages/checkout/widgets-lib/src/widgets/checkout/CheckoutWidget.tsx, packages/checkout/widgets-lib/src/widgets/checkout/CheckoutWidgetRoot.tsx, packages/checkout/widgets-lib/src/widgets/checkout/functions/deduplicateSaleItemsArray.ts, packages/checkout/widgets-lib/src/widgets/checkout/functions/isValidCheckoutFlow.ts, packages/checkout/widgets-sample-app/src/components/ui/checkout/checkout.tsx
Validate the parameters passed to checkout widget by flow
=> [NO CHANGELOG][Checkout Widget] Validate checkout widget inputs

packages/game-bridge/src/index.ts
Add `dev` Passport config to the game bridge.
- Only affects game SDK developers.
Requires the VPN to connect to the `dev` env.
Also removed `startedCallFunction` tracking call.
=> feat: add dev config to game bridge

tests/func-tests/zkevm/specs/orderbook.spec.ts
Enable orderbook bids tests in CI.
=> chore: [TD-1677] Enable orderbook bids tests

packages/checkout/widgets-lib/src/widgets/add-funds/functions/sortRoutesByFastestTime.ts
=> [NO CHANGELOG][Add Funds Widget] Add sortRoutesByFastestTime function

packages/checkout/widgets-lib/src/widgets/add-funds/functions/convertTokenBalanceToUsd.ts
=> [NO CHANGELOG][Add Funds Widget] Add convertTokenBalanceToUsd function

packages/checkout/widgets-lib/src/widgets/add-funds/components/FiatOption.tsx, packages/checkout/widgets-lib/src/widgets/add-funds/types.ts
=> [NO CHANGELOG][Add Funds Widget] Add FiatOption component

packages/checkout/widgets-lib/src/widgets/add-funds/components/FiatOption.tsx, packages/checkout/widgets-lib/src/widgets/add-funds/components/RouteOption.tsx, packages/checkout/widgets-lib/src/widgets/add-funds/hooks/useSquid.ts
=> [NO CHANGELOG] [Add Funds Widget] Feat/add funds route option component

packages/checkout/sdk/src/widgets/definitions/parameters/sale.ts, packages/checkout/widgets-lib/src/widgets/sale/SaleWidget.tsx, packages/checkout/widgets-lib/src/widgets/sale/SaleWidgetRoot.tsx, packages/checkout/widgets-lib/src/widgets/sale/context/SaleContextProvider.tsx, packages/checkout/widgets-lib/src/widgets/sale/hooks/useSignOrder.ts, packages/checkout/widgets-lib/src/widgets/sale/types.ts
=> feat: CM-901 - Implement custom order data for primary sales sign call

packages/checkout/sdk/src/widgets/definitions/configurations/checkout.ts, packages/checkout/sdk/src/widgets/definitions/events/addFunds.ts, packages/checkout/sdk/src/widgets/definitions/events/checkout.ts, packages/checkout/widgets-lib/src/widgets/checkout/CheckoutWidget.tsx
Add missing types to integrate add funds flow into Checkout Widget
=> [NO CHANGELOG][Checkout Widget] Add types for add funds widget

packages/checkout/widgets-lib/src/context/view-context/AddFundsViewContextTypes.ts
Create REVIEW and CONFIRMATION widget view and view type
=> [NOCHANGELOG] [Add Funds Widget] Create REVIEW and CONFIRMATION widget view and view type

packages/checkout/widgets-lib/src/widgets/add-funds/functions/fetchBalances.ts
Create fetch Balances function
=> [NOCHANGELOG] [Add Funds Widget] Create fetch Balances function

packages/checkout/widgets-lib/src/widgets/add-funds/views/AddFunds.tsx
=> [NO CHANGELOG][Add Funds Widget] Add debounce for input

packages/checkout/widgets-lib/src/widgets/add-funds/views/Confirmation.tsx
=> [NO CHANGELOG] [Add Funds Widget] Confirmation view

packages/checkout/widgets-lib/src/widgets/add-funds/functions/fetchChains.ts, packages/checkout/widgets-lib/src/widgets/add-funds/types.ts
Add and populate native currency in chain type
=> [NO CHANGELOG] [Add Funds Widget] Add native currency in chain type

packages/checkout/widgets-lib/src/widgets/add-funds/components/RouteOption.tsx
Show estimated time for each route option
=> [NO CHANGELOG][Add Funds Widget] Show estimated time

examples/orderbook/fulfill-bid-with-nextjs/src/app/fulfill-bid-with-erc1155/page.tsx, examples/orderbook/fulfill-bid-with-nextjs/src/app/fulfill-bid-with-erc721/page.tsx
Small transaction waiting fix to bids example application.
=> chore: Fix bids example apps

examples/passport/wallets-connect-with-nextjs/package.json, packages/checkout/sdk-sample-app/package.json, packages/checkout/widgets-lib/package.json, packages/checkout/widgets-sample-app/package.json, packages/passport/sdk-sample-app/package.json, packages/x-provider/src/sample-app/package.json, sdk/package.json, yarn.lock
this PR simply updates @biom3/react to the latest version - which brings some necessary bugfixes
- @biom3/react dep updated
=> chore: update biome across monorepo

packages/checkout/widgets-lib/package.json, sdk/package.json, yarn.lock
Upgrade squid sdk to 2.9.24 and types to 0.1.108
=> [NO CHANGELOG] [Add Funds Widget] Upgrade squid

packages/checkout/widgets-lib/src/widgets/add-funds/AddFundsRoot.tsx
- Add validation for toTokenAddress param
=> [NO CHANGELOG][Add Funds Widget] Add validation for toTokenAddress param

examples/passport/wallets-connect-with-nextjs/package.json, packages/checkout/sdk-sample-app/package.json, packages/checkout/widgets-lib/package.json, packages/checkout/widgets-sample-app/package.json, packages/passport/sdk-sample-app/package.json, packages/x-provider/src/sample-app/package.json, sdk/package.json, yarn.lock
bumps @biom3/react to `0.27.9`
=> chore: bump biome dep again

packages/orderbook/src/orderbook.ts
- adds missing orderbook method for listing collection bids
=> [TD-1719] Collection bids list

packages/checkout/widgets-lib/src/widgets/add-funds/AddFundsWidget.tsx, packages/checkout/widgets-lib/src/widgets/add-funds/components/RouteOption.tsx, packages/checkout/widgets-lib/src/widgets/add-funds/context/AddFundsContext.ts, packages/checkout/widgets-lib/src/widgets/add-funds/functions/fetchTokens.ts, packages/checkout/widgets-lib/src/widgets/add-funds/hooks/useRoutes.ts, packages/checkout/widgets-lib/src/widgets/add-funds/hooks/useTokens.ts, packages/checkout/widgets-lib/src/widgets/add-funds/types.ts, packages/checkout/widgets-lib/src/widgets/add-funds/views/AddFunds.tsx, packages/checkout/widgets-lib/src/widgets/add-funds/views/Review.tsx
Implement from amount calculation to avoid calling squid api too many times
=> [NO CHANGELOG] [Add Funds Widget] Add funds/improve get from amount

packages/checkout/widgets-lib/src/widgets/add-funds/views/AddFunds.tsx
Small change to improve the readability of the labels in token selection drawer
=> [NO CHANGELOG][Add funds widget] Improve labels on token selection list

packages/orderbook/src/api-client/api-client.ts, packages/orderbook/src/openapi/sdk/models/FulfillableOrder.ts, packages/orderbook/src/openapi/sdk/models/FulfillmentDataRequest.ts, packages/orderbook/src/openapi/sdk/models/UnfulfillableOrder.ts, packages/orderbook/src/orderbook.ts, packages/orderbook/src/seaport/seaport.ts, packages/orderbook/src/types.ts, tests/func-tests/zkevm/specs/orderbook.spec.ts
- Implement support for bulk collection bid fulfilment
- Fix for bulk approvals
- functional tests for bulk fulfil bid and collection bids
- Collection bids bulk support
=> feat: [TD-1719] Add support for collection bid bulk fulfilment

packages/checkout/widgets-lib/src/context/providers-context/ProvidersContext.tsx, packages/checkout/widgets-lib/src/context/view-context/ViewContext.tsx, packages/checkout/widgets-lib/src/widgets/add-funds/AddFundsRoot.tsx, packages/checkout/widgets-lib/src/widgets/add-funds/AddFundsWidget.tsx, packages/checkout/widgets-lib/src/widgets/add-funds/components/DeliverToDrawer.tsx, packages/checkout/widgets-lib/src/widgets/add-funds/components/Options.tsx, packages/checkout/widgets-lib/src/widgets/add-funds/components/OptionsDrawer.tsx, packages/checkout/widgets-lib/src/widgets/add-funds/components/PayWithDrawer.tsx, packages/checkout/widgets-lib/src/widgets/add-funds/components/SelectedRouteOption.tsx, packages/checkout/widgets-lib/src/widgets/add-funds/context/AddFundsContext.tsx, packages/checkout/widgets-lib/src/widgets/add-funds/functions/convertTokenBalanceToUsd.ts, packages/checkout/widgets-lib/src/widgets/add-funds/functions/sortRoutesByFastestTime.ts, packages/checkout/widgets-lib/src/widgets/add-funds/hooks/useRoutes.ts, packages/checkout/widgets-lib/src/widgets/add-funds/views/AddFunds.tsx, packages/checkout/widgets-lib/src/widgets/add-funds/views/Review.tsx, packages/checkout/widgets-sample-app/src/components/ui/add-funds/addFunds.tsx
- Remove connect loader
- Add Providers Context
- Scaffold Pay with & Deliver to 
- Add Selected route UI
https://www.loom.com/share/3f61593feb2043e6a0b641077e22ed61
=> [NO CHANGELOG][Add Funds Widget] Connect from/to wallets UI

examples/contracts/contract-interaction-with-viem/batch-mint-erc721-by-id.ts, examples/contracts/contract-interaction-with-viem/batch-mint-erc721-by-quantity.ts, examples/contracts/contract-interaction-with-viem/index.ts, examples/contracts/test/contracts.test.ts
Add contract interaction examples
- `batch-mint-erc721-by-quantity`
=> docs: Add contract interaction examples for minting #2

packages/checkout/widgets-lib/src/widgets/add-funds/hooks/useRoutes.ts
Retry when 429 is returned from squid api
=> [NO CHANGELOG] [Add Funds Widget] Retry when 429

packages/checkout/sdk/src/errors/checkoutError.ts, packages/checkout/sdk/src/index.ts, packages/checkout/widgets-lib/src/components/ChangedYourMindDrawer/ChangedYourMindDrawer.tsx, packages/checkout/widgets-lib/src/components/UnableToConnectDrawer/UnableToConnectDrawer.tsx, packages/checkout/widgets-lib/src/components/WalletDrawer/ConnectWalletDrawer.tsx, packages/checkout/widgets-lib/src/components/WalletDrawer/DeliverToWalletDrawer.tsx, packages/checkout/widgets-lib/src/components/WalletDrawer/PayWithWalletDrawer.tsx, packages/checkout/widgets-lib/src/lib/connectEIP6963Provider.ts, packages/checkout/widgets-lib/src/widgets/add-funds/AddFundsWidget.tsx, packages/checkout/widgets-lib/src/widgets/connect/components/NonPassportWarningDrawer.tsx
- Fix Error drawers button size
- Hooks sanctioned wallets error to unavailable service view
=> CM-934 | Add funds connect error handling

packages/checkout/widgets-lib/src/components/WalletDrawer/PayWithWalletDrawer.tsx, packages/checkout/widgets-lib/src/widgets/add-funds/components/RouteFees.tsx, packages/checkout/widgets-lib/src/widgets/add-funds/functions/amountValidation.ts, packages/checkout/widgets-lib/src/widgets/add-funds/views/AddFunds.tsx
Fixes to bugs introduced by recent features
- Validate amounts input doesn't go below zero
- Validate fees token is set correctly when swap routes is chosen
- Remove pay with card when token is not allowed for onRamp
=> Add funds flow fixes

examples/orderbook/fulfill-collection-bid-with-nextjs/src/app/fulfill-collection-bid-with-erc1155/page.tsx, examples/orderbook/fulfill-collection-bid-with-nextjs/src/app/fulfill-collection-bid-with-erc721/page.tsx
- adds #doc tags to collection bids fulfillment example apps
=> [TD-1662] Add doc tags to collection bids example apps

packages/checkout/widgets-lib/src/components/SimpleLayout/SimpleLayout.tsx, packages/checkout/widgets-lib/src/locales/en.json, packages/checkout/widgets-lib/src/widgets/add-funds/AddFundsWidget.tsx, packages/checkout/widgets-lib/src/widgets/add-funds/components/OnboardingDrawer.tsx, packages/checkout/widgets-lib/src/widgets/add-funds/functions/onboardingState.ts, packages/checkout/widgets-lib/src/widgets/add-funds/views/AddFunds.tsx
https://github.com/immutable/ts-immutable-sdk/pull/2293
=> Cm 933 add funds onboarding screens

packages/checkout/widgets-lib/src/widgets/add-funds/functions/getFormattedNumber.ts, packages/checkout/widgets-lib/src/widgets/add-funds/functions/getRouteAndTokenBalances.ts, packages/checkout/widgets-lib/src/widgets/add-funds/hooks/useRoutes.ts
- Fixes bug with incorrect amounts used for fiat price calculation
- Ensure routes are always sorted
=> [NO CHANGELOG] [Checkout Widget] Fix routes sorting and formatted price calculation

packages/checkout/widgets-lib/src/widgets/add-funds/AddFundsWidget.tsx, packages/checkout/widgets-lib/src/widgets/add-funds/views/AddFunds.tsx
https://immutable.atlassian.net/browse/CM-1002
=> [NO CHANGELOG] (AddFunds) fix: add theme color support for bg image texture inside AddFunds

packages/checkout/widgets-lib/src/widgets/add-funds/views/AddFunds.tsx
Update to only send track event when route exists
=> [NO CHANGELOGS] [Add Funds Widget] Update to only send track event when route exists

packages/checkout/widgets-lib/src/widgets/add-funds/views/AddFunds.tsx
fix but with back button visible even when hidden
=> [NO CHANGELOG][Add Funds Widget] fix back button visibility

examples/checkout/sdk-load-widgets-with-nextjs/package.json, examples/checkout/sdk-load-widgets-with-nextjs/tests/utils/intercept-widgets.ts, examples/checkout/sdk-load-widgets-with-nextjs/tests/version.spec.ts, yarn.lock
Test weren't loading a local widgets bundle correctly.
=> fix: Checkout widgets e2e tests

packages/checkout/widgets-lib/src/locales/en.json, packages/checkout/widgets-lib/src/widgets/add-funds/components/SquidFooter.tsx, packages/checkout/widgets-lib/src/widgets/add-funds/functions/fetchTokens.ts, packages/checkout/widgets-lib/src/widgets/add-funds/functions/getFormattedNumber.ts, packages/checkout/widgets-lib/src/widgets/add-funds/views/AddFunds.tsx, packages/checkout/widgets-lib/src/widgets/add-funds/views/Review.tsx
=> [NO CHANGELOG] [Add Funds Widget] Add funds legal footer

packages/checkout/widgets-lib/src/context/view-context/AddFundsViewContextTypes.ts, packages/checkout/widgets-lib/src/locales/en.json, packages/checkout/widgets-lib/src/locales/ja.json, packages/checkout/widgets-lib/src/locales/ko.json, packages/checkout/widgets-lib/src/locales/zh.json, packages/checkout/widgets-lib/src/views/error/serviceTypes.ts, packages/checkout/widgets-lib/src/widgets/add-funds/AddFundsWidget.tsx, packages/checkout/widgets-sample-app/src/components/ui/add-funds/addFunds.tsx
=> [NO CHANGELOG] [Add Funds Widget] Add Geo Block error for AU and USA

packages/orderbook/src/openapi/mapper.ts, packages/orderbook/src/types.ts
=> [TD-1676] Add deprecation tags to trade fields

packages/checkout/widgets-lib/src/widgets/add-tokens/views/AddTokens.tsx
Fix the token image for IMX when the user prefills the Add Tokens widget with IMX address.
=> [NO CHANGELOG] [Add Tokens Widget] Fix imx token image when prefill toTokenAddress

packages/checkout/widgets-lib/src/widgets/add-tokens/hooks/useRoutes.ts
Turn refuel feature on only for EOA.
=> [NO CHANGELOG] [Add Tokens Widget] Switch on refuel for EOA only

packages/checkout/widgets-lib/src/components/WalletDrawer/PayWithWalletDrawer.tsx, packages/checkout/widgets-lib/src/widgets/add-tokens/views/AddTokens.tsx
=> [NO CHANGELOG] [Add Tokens Widget] Update Add Tokens widget to copy

packages/checkout/widgets-lib/src/views/loading/LoadingView.tsx, packages/checkout/widgets-lib/src/widgets/add-tokens/views/Review.tsx
Show the gradient bg on Review screen.
=> [NO CHANGELOG] [Add Tokens Widget] Fix bg on Review screen

packages/checkout/widgets-lib/src/widgets/add-tokens/views/Review.tsx
Fix to show the right token image on Review screen.
=> [NO CHANGELOG] [Add Tokens Widget] Fix review screen to token

packages/checkout/widgets-lib/src/widgets/add-tokens/components/SelectedRouteOption.tsx, packages/checkout/widgets-lib/src/widgets/add-tokens/components/SelectedWallet.tsx, packages/checkout/widgets-lib/src/widgets/add-tokens/views/AddTokens.tsx
Loom: https://www.loom.com/share/ccd4025b5f8040509f445ab3be71a101?sid=04c05a64-4564-4d58-bd24-33e3107d5e44
Add the pulsating effect to replace error text.
=> [NO CHANGELOG] [Add Tokens Widget] Feat/add tokens pulse effect

packages/checkout/sdk/src/index.ts, packages/checkout/sdk/src/riskAssessment/riskAssessment.test.ts, packages/checkout/sdk/src/riskAssessment/riskAssessment.ts, packages/checkout/sdk/src/sdk.ts, packages/checkout/widgets-lib/src/widgets/sale/SaleWidget.tsx, packages/checkout/widgets-lib/src/widgets/sale/context/SaleContextProvider.tsx, packages/checkout/widgets-lib/src/widgets/sale/views/OrderSummary.tsx, packages/checkout/widgets-lib/src/widgets/sale/views/PaymentMethods.tsx
Ensure Primary Sales checks the risk assessment for a given address before proceeding with payment.
=> feat: Check if address is sanctioned during Primary Sales

packages/checkout/widgets-lib/src/widgets/add-tokens/AddTokensWidget.tsx, packages/checkout/widgets-lib/src/widgets/add-tokens/functions/fetchChains.ts, packages/checkout/widgets-lib/src/widgets/add-tokens/utils/config.ts, packages/checkout/widgets-lib/src/widgets/add-tokens/views/Review.tsx
This also fixes the circled chains icon issue since SDK v2 stores icons in a squared format.
=> [NO CHANGELOG] [Add Tokens Widget] Fetch chains from squid sdk

packages/checkout/widgets-lib/src/widgets/add-tokens/views/AddTokens.tsx
=> [NO CHANGELOG] [Add Tokens Widget] Add tokens input focus by default

packages/checkout/widgets-lib/src/context/view-context/BridgeViewContextTypes.ts, packages/checkout/widgets-lib/src/widgets/bridge/BridgeWidget.tsx, packages/checkout/widgets-lib/src/widgets/bridge/components/BridgeForm.tsx, packages/checkout/widgets-lib/src/widgets/bridge/components/BridgeReviewSummary.tsx, packages/checkout/widgets-lib/src/widgets/bridge/components/WalletAndNetworkSelector.tsx, packages/checkout/widgets-lib/src/widgets/bridge/context/BridgeContext.ts
https://github.com/user-attachments/assets/2f6e5f41-79f6-4adb-8aaa-a511458facdc
=> feat: Add validation to sanctioned wallets in Bridge widget

packages/checkout/widgets-lib/src/context/view-context/SwapViewContextTypes.ts, packages/checkout/widgets-lib/src/widgets/swap/SwapWidget.tsx, packages/checkout/widgets-lib/src/widgets/swap/components/SwapForm.tsx, packages/checkout/widgets-lib/src/widgets/swap/context/SwapContext.ts
Adding validation to Swap widget for sanctioned wallets
https://github.com/user-attachments/assets/4a1e6178-62f1-4177-a6fa-cd0819e118a6
=> feat: Adding sanctions validation to Swap widget

packages/checkout/widgets-lib/src/widgets/sale/components/OrderReview.tsx
=> fix: Handles case when getFundingBalanceTotalFees returns undefined

examples/blockchain-data/api-examples-with-node/index.ts, examples/blockchain-data/api-examples-with-node/list-filters.ts, examples/blockchain-data/api-examples-with-node/list-nfts-by-account-address.ts, examples/blockchain-data/api-examples-with-node/list-stacks.ts, examples/blockchain-data/api-examples-with-node/quotes-for-nfts.ts, examples/blockchain-data/api-examples-with-node/quotes-for-stacks.ts, examples/blockchain-data/api-examples-with-node/search-nfts.ts, examples/blockchain-data/api-examples-with-node/search-stacks.ts, examples/blockchain-data/package.json, examples/blockchain-data/test/blockchain-data.test.ts, package.json, yarn.lock
=> docs: Add code examples for Marketplace API endpoints

packages/checkout/widgets-lib/src/widgets/add-tokens/components/TokenDrawerMenu.tsx, packages/checkout/widgets-lib/src/widgets/add-tokens/views/AddTokens.tsx
Update analytics events for Add Tokens widget
- Add geoblocked in input screen page event
- Add hasEmbbededSwap in routes event
- Update to only send event when user has initiated instead of pre defined
- Fix Review button event
=> [NO CHANGELOG] [Add Tokens Widget] feat: Update analytics events

packages/checkout/widgets-lib/src/widgets/on-ramp/OnRampWidget.tsx, packages/checkout/widgets-lib/src/widgets/on-ramp/views/OnRampMain.tsx
=> feat: Add risk assessment to OnRamp widget

packages/webhook/sdk/src/event-types.ts, packages/webhook/sdk/src/handler.ts
Fix immutable X webhook event schema
=> fix: fix webhook event schema

packages/checkout/widgets-lib/src/widgets/add-tokens/utils/animation.ts
=> [NO CHANGELOG] [Add tokens Widget] Make animation smoother

packages/checkout/widgets-lib/src/components/WalletDrawer/ConnectWalletDrawer.tsx, packages/checkout/widgets-lib/src/lib/metrics.ts, packages/checkout/widgets-lib/src/lib/utils.ts, packages/checkout/widgets-lib/src/widgets/add-tokens/AddTokensWidget.tsx, packages/checkout/widgets-lib/src/widgets/add-tokens/components/TokenDrawerMenu.tsx, packages/checkout/widgets-lib/src/widgets/add-tokens/context/AddTokensContext.tsx, packages/checkout/widgets-lib/src/widgets/add-tokens/hooks/useError.tsx, packages/checkout/widgets-lib/src/widgets/add-tokens/hooks/useExecute.ts, packages/checkout/widgets-lib/src/widgets/add-tokens/hooks/useRoutes.ts, packages/checkout/widgets-lib/src/widgets/add-tokens/views/AddTokens.tsx, packages/checkout/widgets-lib/src/widgets/add-tokens/views/Review.tsx, packages/checkout/widgets-lib/src/widgets/connect/components/WalletList.tsx
Add Metrics to measure approval and execution
Improve Analytics events
=> [NO CHANGELOG] [Add Tokens Widget] Add Metrics and Improve Analytics events

packages/checkout/widgets-lib/src/widgets/add-tokens/hooks/useExecute.ts, packages/checkout/widgets-lib/src/widgets/add-tokens/views/Review.tsx
=> [NO CHANGELOG] [Add Tokens Widget] fix:Update metrics to send error

examples/x-to-zkevm-migration-app/backend/README.md, examples/x-to-zkevm-migration-app/frontend/README.md
=> docs: migration example update readme

packages/checkout/widgets-lib/src/locales/en.json, packages/checkout/widgets-lib/src/locales/ja.json, packages/checkout/widgets-lib/src/locales/ko.json, packages/checkout/widgets-lib/src/locales/zh.json, packages/checkout/widgets-lib/src/widgets/add-tokens/hooks/useExecute.ts, packages/checkout/widgets-lib/src/widgets/add-tokens/utils/config.ts, packages/checkout/widgets-lib/src/widgets/add-tokens/views/Review.tsx
Completion state covers error states from squid
=> [NO CHANGELOG] [Add Tokens Widget] Add tokens/id 2965 confirmation

packages/checkout/widgets-lib/src/locales/en.json, packages/checkout/widgets-lib/src/locales/ja.json, packages/checkout/widgets-lib/src/locales/ko.json, packages/checkout/widgets-lib/src/locales/zh.json
Remove Included in fee section
=> [NO CHANGELOG] [Add Tokens Widget] fix:Remove Included in fee section

packages/checkout/widgets-lib/src/widgets/add-tokens/views/AddTokens.tsx
Making sure `selectedAmount` has the latest value before proceeding to the review screen.
=> [NO CHANGELOG] [Add Tokens Widget] Fix input amount syncing

packages/checkout/widgets-lib/src/widgets/add-tokens/views/Review.tsx
=> [NO CHANGELOG] [Add Tokens Widget] Replace name with symbol

packages/checkout/widgets-lib/src/widgets/add-tokens/views/Review.tsx
=> feat: Track estimated Squid route execution durations

packages/checkout/widgets-lib/src/lib/metrics.ts, packages/checkout/widgets-lib/src/widgets/add-tokens/functions/errorType.ts, packages/checkout/widgets-lib/src/widgets/add-tokens/hooks/useExecute.ts, packages/checkout/widgets-lib/src/widgets/add-tokens/views/Review.tsx
=> [NO CHANGELOG] [Add Tokens Widget] Add more metrics

packages/checkout/widgets-lib/src/components/WalletDrawer/ConnectWalletDrawer.tsx
=> [NO CHANGELOG] [Add Tokens Widget] Fix to prevent logging out from Passport if toProvider is locked

packages/checkout/widgets-lib/src/widgets/immutable-commerce/CommerceWidget.tsx, packages/checkout/widgets-lib/src/widgets/immutable-commerce/CommerceWidgetRoot.tsx
Commerce widget to set toProvider for add tokens flow
=> [NO CHANGELOG] [Commerce Widget] fix:Set toProvider

packages/checkout/sdk/src/widgets/definitions/configurations/index.ts, packages/checkout/sdk/src/widgets/definitions/configurations/purchase.ts, packages/checkout/sdk/src/widgets/definitions/events/index.ts, packages/checkout/sdk/src/widgets/definitions/events/orchestration.ts, packages/checkout/sdk/src/widgets/definitions/events/purchase.ts, packages/checkout/sdk/src/widgets/definitions/events/widgets.ts, packages/checkout/sdk/src/widgets/definitions/parameters/index.ts, packages/checkout/sdk/src/widgets/definitions/parameters/purchase.ts, packages/checkout/sdk/src/widgets/definitions/types.ts, packages/checkout/widgets-lib/src/context/analytics-provider/SegmentAnalyticsProvider.ts, packages/checkout/widgets-lib/src/context/view-context/PurchaseViewContextTypes.ts, packages/checkout/widgets-lib/src/context/view-context/ViewContext.tsx, packages/checkout/widgets-lib/src/factory.ts, packages/checkout/widgets-lib/src/widgets/purchase/PurchaseWidget.tsx, packages/checkout/widgets-lib/src/widgets/purchase/PurchaseWidgetEvents.ts, packages/checkout/widgets-lib/src/widgets/purchase/PurchaseWidgetRoot.tsx, packages/checkout/widgets-lib/src/widgets/purchase/context/PurchaseContext.tsx, packages/checkout/widgets-lib/src/widgets/purchase/views/Purchase.tsx, packages/checkout/widgets-lib/src/widgets/purchase/views/Review.tsx, packages/checkout/widgets-sample-app/src/App.tsx, packages/checkout/widgets-sample-app/src/components/ui/purchase/purchase.tsx, packages/checkout/widgets-sample-app/src/index.tsx
Base definitions for our upcoming Purchase flow.
=> feat: Add skeleton for Purchase widget

packages/checkout/widgets-lib/src/components/ConnectLoader/ConnectLoader.tsx, packages/checkout/widgets-lib/src/lib/analytics/identifyUser.ts, packages/checkout/widgets-lib/src/widgets/connect/ConnectWidget.tsx, packages/checkout/widgets-lib/src/widgets/connect/components/WalletList.tsx, packages/checkout/widgets-lib/src/widgets/connect/views/ReadyToConnect.tsx
Similar problem fixed on #2422, now to all widgets.
=> fix: Ensure anonymousId is kept through every Segment identify call

packages/checkout/widgets-lib/src/widgets/add-tokens/views/AddTokens.tsx
- Fire an event when there are no routes available for the user
[JIRA](https://immutable.atlassian.net/browse/ID-3052)
=> feat: Fire an event when there are no routes available

packages/checkout/widgets-lib/src/widgets/add-tokens/components/OptionsDrawer.tsx, packages/checkout/widgets-lib/src/widgets/add-tokens/views/Review.tsx
- Adding a new event for when the routes drawer opens
- Enriching the Succeed event with extra props
=> chore: Add extra telemetry events for Add Tokens

packages/game-bridge/src/index.ts
- Added a new callback function for Unity Windows WebView.
- Fixed how game bridge checks for Unity.call
=> [DX-3465] feat: new game bridge callback function for unity windows

packages/checkout/widgets-lib/src/lib/metrics.ts, packages/checkout/widgets-lib/src/widgets/add-tokens/hooks/useExecute.ts, packages/checkout/widgets-lib/src/widgets/add-tokens/views/AddTokens.tsx, packages/checkout/widgets-lib/src/widgets/add-tokens/views/Review.tsx
Add anonymous id to approve and execute metrics
Add track error for loaded and funds success event
=> [NO CHANGELOG] [ADD TOKENS WIDGET] fix: Add more metrics

packages/checkout/widgets-lib/src/locales/en.json, packages/checkout/widgets-lib/src/locales/ja.json, packages/checkout/widgets-lib/src/locales/ko.json, packages/checkout/widgets-lib/src/locales/zh.json, packages/checkout/widgets-lib/src/widgets/add-tokens/utils/animation.ts, packages/checkout/widgets-lib/src/widgets/add-tokens/views/AddTokens.tsx
- Update token input button text
- Make the pulse more pronounced
=> [NO CHANGELOG] [Add Tokens Widget] Fix/add tokens make input pronounce

packages/checkout/widgets-lib/src/widgets/add-tokens/views/AddTokens.tsx, packages/checkout/widgets-lib/src/widgets/add-tokens/views/Review.tsx
=> [NO CHANGELOG] [Add Tokens Widget] Add trackFlow with messageId

packages/checkout/widgets-lib/src/widgets/add-tokens/components/TokenDrawerMenu.tsx
=> [NO CHANGELOG] [Add Tokens Widget] Fix double scrollbar token menu

packages/checkout/widgets-lib/src/locales/en.json, packages/checkout/widgets-lib/src/locales/ja.json, packages/checkout/widgets-lib/src/locales/zh.json
=> [NO CHANGELOG] [Add Tokens Widget] Fix typo

packages/checkout/widgets-lib/src/locales/en.json, packages/checkout/widgets-lib/src/locales/ja.json, packages/checkout/widgets-lib/src/locales/ko.json, packages/checkout/widgets-lib/src/locales/zh.json, packages/checkout/widgets-lib/src/widgets/add-tokens/components/SelectedWallet.tsx, packages/checkout/widgets-lib/src/widgets/add-tokens/views/AddTokens.tsx
Add captions to wallet selection menus.
=> [NO CHANGELOG] [Add Tokens Widget] Chore/add tokens add wallet text

packages/checkout/widgets-lib/src/widgets/add-tokens/components/SelectedWallet.tsx, packages/checkout/widgets-lib/src/widgets/add-tokens/views/AddTokens.tsx
Deliver to wallet to have chain icon
=> [NO CHANGELOG] [Add Tokens Widget] Update Deliver to wallet to set chain icon

packages/checkout/widgets-lib/src/widgets/on-ramp/views/OnRampMain.tsx
- adding the `transactionHash` to tracking events in onramp.
=> feat: Adding tx hash to tracking events

packages/checkout/sdk-sample-app/package.json, packages/checkout/widgets-lib/package.json, packages/checkout/widgets-lib/src/components/RawImage/RawImage.tsx, packages/checkout/widgets-lib/src/components/SimpleLayout/SimpleLayout.tsx, packages/checkout/widgets-lib/src/lib/squid/components/SquidIcon.tsx, packages/checkout/widgets-lib/src/widgets/add-tokens/components/SelectedRouteOption.tsx, packages/checkout/widgets-lib/src/widgets/add-tokens/components/SelectedWallet.tsx, packages/checkout/widgets-sample-app/package.json, packages/passport/sdk-sample-app/package.json, packages/x-provider/src/sample-app/package.json, sdk/package.json, yarn.lock
Add Tooltip for chain in route and destination wallet
Upgrade @biom3/react to 0.28.13
=> [NO CHANGELOG] [Add Tokens Widget] Chain Tooltip

packages/checkout/sdk/src/widgets/definitions/parameters/addTokens.ts, packages/checkout/widgets-lib/src/widgets/add-tokens/AddTokensRoot.tsx, packages/checkout/widgets-lib/src/widgets/add-tokens/AddTokensWidget.tsx, packages/checkout/widgets-lib/src/widgets/add-tokens/components/TokenDrawerMenu.tsx, packages/checkout/widgets-lib/src/widgets/add-tokens/context/AddTokensContext.tsx, packages/checkout/widgets-lib/src/widgets/add-tokens/types.ts, packages/checkout/widgets-lib/src/widgets/add-tokens/views/AddTokens.tsx, packages/checkout/widgets-sample-app/src/components/ui/add-tokens/addTokens.tsx
=> feat: Enable prefilled token experiment on Add Tokens

packages/checkout/widgets-lib/src/widgets/add-tokens/views/Review.tsx
Add some tracking to understand when the fee breakdown is displayed.
=> chore: Track fee breakdown button click

.github/workflows/publish.yaml
=> disable publish workflow triggers

packages/checkout/sdk/src/widgets/version.ts
Check files availability on CDN using `HEAD` requests for a minimal bandwidth usage. Fallback to `latest` version.
=> Check CDN availability before loading latest version

packages/checkout/widgets-lib/src/lib/squid/hooks/useRoutes.ts
- Instead of applying a fixed 2% , we apply a different percentage depending on the usd value
=> fix: Add value based percentage

packages/passport/sdk/src/zkEvm/sessionActivity/sessionActivity.ts
initialise session activity count to 0 before incrementing it.
=> fix: fix initial session count

packages/passport/sdk/src/authManager.test.ts, packages/passport/sdk/src/authManager.ts
- Prevent Unknown or invalid refresh token requests being triggered multiple times
=> fix: ID-3129 Prevent Unknown or invalid refresh token requests from being triggered multiple times

packages/webhook/sdk/src/event-types.ts
Correct the webhook event type for imtbl_zkevm_order_updated event.
=> fix: fix order webhook event schema

.github/workflows/publish-major-version.yaml, .github/workflows/publish.yaml
- Fix indentation
- Update `JS-DevTools/npm-publish@v3` to a specific commit hash (see https://github.com/JS-DevTools/npm-publish/releases/tag/v3)
=> fix: Fix indentation in publish workflow

.github/workflows/publish-docs.yaml
use a new key for publish docs cache restore.
=> fix: change publish doc cache key

packages/checkout/widgets-lib/src/lib/hooks/useSignOrder.ts, packages/checkout/widgets-lib/src/lib/primary-sales.ts, packages/checkout/widgets-lib/src/lib/squid/functions/findBalance.ts, packages/checkout/widgets-lib/src/lib/squid/hooks/useExecute.ts, packages/checkout/widgets-lib/src/lib/squid/hooks/useRoutes.ts, packages/checkout/widgets-lib/src/locales/en.json, packages/checkout/widgets-lib/src/locales/ja.json, packages/checkout/widgets-lib/src/locales/ko.json, packages/checkout/widgets-lib/src/locales/zh.json, packages/checkout/widgets-lib/src/widgets/purchase/components/RouteOptionsDrawer/DirectCryptoPayOption.tsx, packages/checkout/widgets-lib/src/widgets/purchase/components/RouteOptionsDrawer/FiatOption.tsx, packages/checkout/widgets-lib/src/widgets/purchase/components/RouteOptionsDrawer/RouteOption.tsx, packages/checkout/widgets-lib/src/widgets/purchase/components/RouteOptionsDrawer/RouteOptions.tsx, packages/checkout/widgets-lib/src/widgets/purchase/components/RouteOptionsDrawer/RouteOptionsDrawer.tsx, packages/checkout/widgets-lib/src/widgets/purchase/components/SelectedRouteOption/SelectedRouteOption.tsx, packages/checkout/widgets-lib/src/widgets/purchase/functions/getRouteAndBalancesForDirectCryptoPay.ts, packages/checkout/widgets-lib/src/widgets/purchase/types.ts
- Adding components to purchase widget to visualice direct crypto purchases in the UI
=> feat: Adding routes component to purchase widget

packages/checkout/widgets-lib/src/widgets/purchase/components/RouteOptionsDrawer/RouteOptions.tsx, packages/checkout/widgets-lib/src/widgets/purchase/views/Purchase.tsx
=> feat: Adding direct crypto payments along with squid routes

packages/checkout/widgets-lib/src/widgets/purchase/hooks/useHandoverConfig.tsx
- Adding useHandoverConfig to purchase widget
=> feat: Adding useHandoverConfig to purchase widget

packages/checkout/widgets-lib/src/widgets/purchase/components/PurchaseConnectWalletDrawer.tsx, packages/checkout/widgets-lib/src/widgets/purchase/components/PurchaseDeliverToWalletDrawer.tsx, packages/checkout/widgets-lib/src/widgets/purchase/components/PurchasePayWithWalletDrawer.tsx, packages/checkout/widgets-lib/src/widgets/purchase/components/PurchaseSelectedRouteOption.tsx, packages/checkout/widgets-lib/src/widgets/purchase/views/Purchase.tsx
- Adding Pay with card behaviour to Wallet selector
=> feat: Adding Pay with card behaviour to Wallet selector

packages/checkout/widgets-lib/src/locales/en.json
Make changes to field labels for the swap form
=> refactor(widgets-lib): Text changes for swap form

packages/passport/sdk-sample-app/.env.development, packages/passport/sdk-sample-app/.env.production, packages/passport/sdk-sample-app/src/components/PassportMethods.tsx, packages/passport/sdk-sample-app/src/config/index.ts, packages/passport/sdk-sample-app/src/context/ImmutableProvider.tsx, packages/passport/sdk-sample-app/src/context/PassportProvider.tsx, packages/passport/sdk-sample-app/src/pages/login/callback.ts, packages/passport/sdk-sample-app/src/pages/login/redirect-callback.ts, packages/passport/sdk/src/Passport.int.test.ts, packages/passport/sdk/src/Passport.test.ts, packages/passport/sdk/src/Passport.ts, packages/passport/sdk/src/authManager.test.ts, packages/passport/sdk/src/authManager.ts, packages/passport/sdk/src/config/config.test.ts, packages/passport/sdk/src/confirmation/confirmation.test.ts, packages/passport/sdk/src/guardian/index.test.ts, packages/passport/sdk/src/test/mocks.ts, packages/passport/sdk/src/types.ts, packages/passport/sdk/src/zkEvm/walletHelpers.test.ts
This PR aims to add support for redirect based login, to solve the issues described in [this](https://immutable.atlassian.net/browse/ID-3265) task.
=> feat(passport): Redirect based login

packages/internal/dex/sdk/src/lib/utils.test.ts, packages/internal/dex/sdk/src/lib/utils.ts
In rare circumstances, due to mixed casing of contract addresses, swaps can fail.
=> fix(checkout): GFI-98: Fix token mismatch errors

packages/checkout/widgets-lib/rollup.config.js
Fixes the loading of the Checkout widgets.
=> fix(checkout): Fix widgets loading

.github/CODEOWNERS, packages/blockchain-data/sdk/package.json, packages/checkout/sdk/package.json, packages/checkout/sdk/src/sdk.test.ts, packages/checkout/sdk/src/sdk.ts, packages/checkout/widgets-lib/src/lib/hooks/useInjectedProviders.ts, packages/checkout/widgets-sample-app/src/components/ui/bridge/bridge.tsx, packages/config/package.json, packages/internal/bridge/sdk/package.json, packages/internal/cryptofiat/package.json, packages/internal/dex/sdk/package.json, packages/internal/metrics/package.json, packages/internal/toolkit/package.json, packages/minting-backend/sdk/package.json, packages/orderbook/package.json, packages/passport/sdk/package.json, packages/webhook/sdk/package.json, packages/x-client/package.json, packages/x-provider/package.json, pnpm-lock.yaml
Fixes a couple of bugs in Checkout that surfaced in the Bridge widget.
* If your EOA wallet is not on the correct provider, you won't see any balances when trying to bridge.
* Sometimes, you get an error when choosing Passport from the list because we convert it to a WrappedBrowserProvider too early in the process.
=> fix(checkout): Fix checkout / bridge regressions in v2

packages/checkout/widgets-lib/src/widgets/transfer/TransferWidget.tsx
Ensure transfer amount is positive.
=> fix(checkout): Ensure transfer amount is positive

.github/workflows/publish-example-tutorials.yaml, examples/_parsed/checkout-examples.json, examples/_parsed/contracts-examples.json, examples/_parsed/orderbook-examples.json, examples/_parsed/passport-examples.json, examples/_scripts/sample-app-parser.mjs, examples/checkout/prompt.txt, examples/checkout/sdk-connect-with-nextjs/metadata.json, examples/checkout/sdk-gas-estimation-with-nextjs/metadata.json, examples/checkout/sdk-switch-network-with-nextjs/metadata.json, examples/checkout/sdk-wallet-balance-with-nextjs/metadata.json, examples/orderbook/create-bid-with-nextjs/metadata.json, examples/orderbook/create-collection-bid-with-nextjs/metadata.json, examples/orderbook/create-listing-with-nextjs/metadata.json, examples/orderbook/fulfill-bid-with-nextjs/metadata.json, examples/orderbook/fulfill-collection-bid-with-nextjs/metadata.json, examples/orderbook/fulfill-listing-with-nextjs/metadata.json, examples/orderbook/prompt.txt, examples/passport/logged-in-user-with-nextjs/metadata.json, examples/passport/login-with-nextjs/metadata.json, examples/passport/prompt.txt, examples/passport/telegram-mini-app/metadata.json, examples/passport/wallets-connect-with-nextjs/metadata.json, examples/passport/wallets-signing-with-nextjs/metadata.json, examples/passport/wallets-transactions-with-nextjs/metadata.json
Changed how sidebar_orders for example apps are assigned to the metadata.json file. This fix is to ensure that updates to the order can be done via the parser instead of having to run the prompt.
=> fix: DVR-330 | Changed the mechanism on example app's sidebar_orders for consistency 

packages/internal/bridge/sdk/src/tokenBridge.ts
Update the minGasPrice on Axelar requests as suggested by Axelar to reduce number of stuck transactions.
=> fix(bridge): Update minGasPrice for Axelar

.github/CODEOWNERS, examples/checkout/prompt.txt, examples/contracts/prompt.txt, examples/orderbook/prompt.txt, examples/passport/prompt.txt
Update to the prompt to make it more explicitly about generating 1 sample app tutorial and accept the parameter passed in from by the user prompt
=> fix(examples): prompt fix

yarn.lock
Adds in the missed `yarn.lock` file change.
=> chore(passport): ID-3423: add explicit dependency for @magic-sdk/commons to sdk/package.json

packages/checkout/widgets-lib/src/widgets/connect/ConnectWidget.tsx, packages/checkout/widgets-lib/src/widgets/connect/ConnectWidgetRoot.tsx, packages/checkout/widgets-sample-app/src/components/ui/connect/connect.tsx
Allow the Connect Widget to respect the l2ChainId specified by overrides.
=> fix(checkout): Allow targetChainId to use overrides

packages/checkout/widgets-lib/src/widgets/swap/components/SwapForm.tsx
Show an error message if the price impact is at least 15%.
=> feat(checkout): Show price impact message

packages/checkout/widgets-lib/src/lib/hooks/useSignOrder.ts, packages/checkout/widgets-lib/src/lib/primary-sales.ts, packages/checkout/widgets-lib/src/lib/utils.ts, packages/checkout/widgets-lib/src/widgets/sale/context/SaleContextProvider.tsx, packages/checkout/widgets-lib/src/widgets/sale/hooks/useQuoteOrder.ts, packages/checkout/widgets-lib/src/widgets/sale/hooks/useSignOrder.ts, packages/checkout/widgets-lib/src/widgets/sale/types.ts, packages/checkout/widgets-lib/src/widgets/sale/views/OrderSummary.tsx, packages/checkout/widgets-lib/src/widgets/sale/views/PayWithCoins.tsx
=> chore(checkout-widgets): Track errors

packages/checkout/widgets-lib/src/widgets/on-ramp/views/OnRampMain.tsx
=> chore(checkout-widgets): Remove sanctions check from onramp widget

packages/game-bridge/src/index.ts, packages/passport/sdk/src/Passport.ts, packages/passport/sdk/src/authManager.test.ts, packages/passport/sdk/src/authManager.ts, packages/passport/sdk/src/confirmation/embeddedLoginPrompt.test.ts, packages/passport/sdk/src/confirmation/embeddedLoginPrompt.ts, packages/passport/sdk/src/confirmation/types.ts, packages/passport/sdk/src/overlay/elements.ts
This PR improves the headless login analytics.
- Passport: Improved headless login analytics
=> feat(passport): ID-3960 Headless login analytics
