.github/workflows/build-lint-typecheck-test.yaml
.github/workflows/publish.yaml

Since this repository was made public, all github actions have been stalled , unable to select a runner from our enterprise account.
We will need to figure out a strategy here (as switch back to ubuntu-latest will extend build times)
For the moment however, this temporary change will keep CI/CD moving.
Follow up PR will need to consider a runner group just for this repository, and ensure adequate security protections.

Move runners back to ubuntu-latest

---

packages/passport/sdk/src/confirmation/confirmation.ts

Adjusting the default IMX transaction screen height in order to accommodate the new layout with the cancel button
IMX transaction screen default height: 380 > 720
Accompanies https://github.com/immutable/imx-passport-ts/pull/112

ID-1186: Adjust Passport transaction confirmation window height

---

packages/checkout/widgets-lib/src/widgets/x-bridge/components/BridgeReviewSummary.tsx

When getting the unsigned txns for the bridge we were sending the default token decimals of 18. We should use the decimals that come from the token to handle all token decimals. This fixes the issue when trying to bridge across the 6 decimal usdc contract.

WT-1996 Correctly handle token decimals when getting unsigned transactions from bridge

---

packages/checkout/widgets-lib/src/lib/balance.ts
packages/checkout/widgets-lib/src/widgets/swap/SwapWidget.tsx
packages/checkout/widgets-lib/src/widgets/x-bridge/views/Bridge.tsx

Due to an error in the retry logic when the user changes network; the widget, at time, believes that there are no balances and therefore it fires a no enough IMX screen this also affected the bridge widget.
Additional follow up bug ticket https://immutable.atlassian.net/browse/WT-1948

WT-1946 - fix balances error due to change of network

---

packages/checkout/widgets-lib/src/components/NotEnoughGas/NotEnoughGas.tsx
packages/checkout/widgets-lib/src/components/NotEnoughGas/NotEnoughGasStyles.tsx
packages/checkout/widgets-lib/src/resources/text/textConfig.ts
packages/checkout/widgets-lib/src/views/top-up/TopUpView.tsx
packages/checkout/widgets-lib/src/widgets/bridge/BridgeWidget.tsx
packages/checkout/widgets-lib/src/widgets/bridge/components/BridgeForm.tsx
packages/checkout/widgets-lib/src/widgets/on-ramp/OnRampWidget.tsx
packages/checkout/widgets-lib/src/widgets/swap/SwapWidget.tsx
packages/checkout/widgets-lib/src/widgets/wallet/WalletWidget.tsx
packages/checkout/widgets-lib/src/widgets/wallet/views/WalletBalances.tsx
packages/checkout/widgets-sample-app/src/components/ui/marketplace-orchestrator/MainPage.tsx

Adds the not enough gas drawer and conditionally renders depending on whether the native token is ETH or IMX.
Also added the 'Add IMX coins' button, which is what we do in the swap widget. This button will take the user to the TopUpView.
https://github.com/immutable/ts-immutable-sdk/assets/122326421/4c54a36a-b93b-4694-b1ea-b1af82ceab97
https://github.com/immutable/ts-immutable-sdk/assets/122326421/f17c7fd8-a225-4ecb-a101-0f00446697c4
https://github.com/immutable/ts-immutable-sdk/assets/122326421/5ffcb876-5c71-4362-9d77-372762b2b9f2
https://github.com/immutable/ts-immutable-sdk/assets/122326421/ba078630-f7e1-46e9-8a08-920a4781a963

WT-1934 Not enough gas drawer

---

packages/checkout/sdk/src/balances/balances.test.ts
packages/checkout/sdk/src/balances/balances.ts
packages/checkout/sdk/src/errors/checkoutError.ts
packages/checkout/sdk/src/sdk.ts
packages/checkout/sdk/src/types/balances.ts

Allow a user to use `getAllBalances` without a connected `web3provider` as long as a walletAddress is provided.
A `web3provider` is a must if the indexer is disabled.

WT-1971 - allow get balances without connected provider

---

sdk/tsconfig.json

[DX-2487](https://immutable.atlassian.net/browse/DX-2487)
Less type errors in the generated type declaration files.
- Enable type checking in third party libraries (SDK internal packages).
`typecheck` on the SDK package will now type check the internal SDK packages. 
[DX-2487]: https://immutable.atlassian.net/browse/DX-2487?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: set skipLibCheck false

---

packages/checkout/sdk/src/index.ts
packages/checkout/sdk/src/smartCheckout/routing/bridge/bridgeRoute.test.ts
packages/checkout/sdk/src/smartCheckout/routing/bridge/bridgeRoute.ts
packages/checkout/sdk/src/smartCheckout/routing/bridgeAndSwap/bridgeAndSwapRoute.test.ts
packages/checkout/sdk/src/smartCheckout/routing/routingCalculator.test.ts
packages/checkout/sdk/src/smartCheckout/routing/swap/swapRoute.test.ts
packages/checkout/sdk/src/smartCheckout/routing/swap/swapRoute.ts
packages/checkout/sdk/src/types/smartCheckout.ts
packages/checkout/widgets-lib/src/widgets/sale/components/FundingRouteSelect/FundingRouteSelect.cy.tsx
packages/checkout/widgets-lib/src/widgets/sale/functions/smartCheckoutUtils.test.ts
packages/checkout/widgets-lib/src/widgets/sale/functions/smartCheckoutUtils.ts

Adds a fee type to clearly differentiate between gas, bridge/swap & the immutable fee
Also this PR renames the following, as they are just a singular fee and not part of an array:
- `approvalGasFees` -> `approvalGasFee`
- `swapGasFees` -> `swapGasFee`
- `bridgeGasFees` -> `bridgeGasFee`

WT-1980 Update smart checkout fee types

---

packages/checkout/widgets-lib/src/components/Transactions/TransactionItem.tsx
packages/checkout/widgets-lib/src/components/Transactions/TransactionsInProgress.tsx

After completing a Bridge, going to the Transaction in progress screen should show details about the wallets and networks that the bridge is between. It currently doesn’t show the correct wallet addresses.
Data returned by the backend
```
{
"result": [
{
"blockchain_metadata": {
"transaction_hash": "0x1b8c4a3252b8ead7e4d942be3d8c6c6d1cb049edde11bc014536263062cc5a07"
},
"created_at": "2024-01-11T00:47:00Z",
"details": {
"amount": "100000",
"current_status": {
"status": "in_progress"
},
"from_address": "0x1e8dc77bed0da06621e819fa0afb59d50f76cfdf",
"from_chain": "sepolia",
"from_token_address": "0x40b87d235a5b010a20a241f15797c9debf1ecd01",
"to_address": "0x1e8dc77bed0da06621e819fa0afb59d50f76cfdf",
"to_chain": "imtbl-zkevm-testnet",
"to_token_address": …
```

fix: WT-2040 - dynamic from and to address in the in-progress screen

---

.github/workflows/publish.yaml

Checkout JS bundle is fetched from JS Deliver. JS Deliver will cache that bundle at the first hit; however given the size of the bundle, the time to fetch and cache it is not negligible; therefore on release we can pre-warm the CDN by making the first request.
Reduce the load time of the Checkout bundle when a new NPM version is released.
Hit JS Deliver when a new NPM version is released.

feat: WT-2032 - Warm up CDN as soon as a new NPM package has been released

---

packages/orderbook/src/openapi/sdk/models/FulfillmentDataRequest.ts
packages/orderbook/src/orderbook.ts

Adds the taker address to the fulfillment data request in the order fulfillment flow.
Fulfillment data retrieved will no longer be valid when submitted by any other address than the specified taker address to the settlement contract.
Fulfillment data retrieved will no longer be valid when submitted by any other address than the specified taker address to the settlement contract.
N/A

feat: [TD-1158] Add `taker_address` to fulfillment data request

---

packages/checkout/widgets-lib/src/widgets/wallet/WalletWidget.tsx
packages/checkout/widgets-lib/src/widgets/wallet/components/NetworkMenu/NetworkMenu.cy.tsx
packages/checkout/widgets-lib/src/widgets/wallet/components/NetworkMenu/NetworkMenu.tsx
packages/checkout/widgets-lib/src/widgets/wallet/views/WalletBalances.cy.tsx
packages/checkout/widgets-lib/src/widgets/wallet/views/WalletBalances.tsx

When switching networks in the Wallet Widget we only want to show the loading shimmer once API request started, not while the switch network confirmation is requested in MetaMask.
Fix made as part of https://immutable.atlassian.net/browse/WT-1948

WT-1948 fix: Only show loading shimmer once balance API request started

---

packages/checkout/sdk/src/blockExplorer/blockExplorer.test.ts
packages/checkout/sdk/src/blockExplorer/blockExplorer.ts
packages/checkout/sdk/src/blockExplorer/index.ts
packages/checkout/sdk/src/index.ts
packages/checkout/widgets-lib/src/context/view-context/SaleViewContextTypes.ts
packages/checkout/widgets-lib/src/widgets/sale/SaleWidget.tsx
packages/checkout/widgets-lib/src/widgets/sale/SaleWidgetRoot.tsx
packages/checkout/widgets-lib/src/widgets/sale/context/SaleContextProvider.tsx
packages/checkout/widgets-lib/src/widgets/sale/hooks/useSignOrder.ts
packages/checkout/widgets-lib/src/widgets/sale/views/SaleErrorView.tsx
packages/checkout/widgets-sample-app/src/components/ui/sale/sale.tsx

- When transaction fails with txn hash display error view with View Details ( link to block explorer )
- If not hash, display Dimiss ( closes widget )
- When any other error, display default error view

[GPR-354] Sale Widget | Handle Default Error and Transaction Error

---

packages/passport/sdk/src/zkEvm/walletHelpers.test.ts
packages/passport/sdk/src/zkEvm/walletHelpers.ts

This PR fixes an issue where signatures generated by some certain would be invalid.
- Passport: Fixed an issue where EIP-712 signatures generated by certain wallets would fail to validate.

fix: ID-1356 Fixed zkEvm message signing implementation

---

packages/checkout/widgets-lib/src/components/Transak/TransakTypes.ts
packages/checkout/widgets-lib/src/components/Transak/useTransakIframe.ts
packages/checkout/widgets-lib/src/widgets/sale/components/WithCard.tsx
packages/checkout/widgets-lib/src/widgets/sale/hooks/useSignOrder.ts
packages/checkout/widgets-lib/src/widgets/sale/types.ts

Signed transaction responses have changed after sales backend added ERC115 support. This PR updates the types and mapping to:
```
type SignApiResponse = {
order: {
currency: {
name: string;
decimals: number;
erc20_address: string;
};
currency_symbol: string;
products: Array<{
product_id: string;
collection_address: string;
contract_type: string;
detail: Array<{
amount: number;
token_id: string;
}>;
}>;
total_amount: string;
};
transactions: Array<{
contract_address: string;
gas_estimate: number;
method_call: string;
params: {
amount?: number;
spender?: string;
data?: Array<string>;
deadline?: number;
multicallSigner?: string;
reference?: string;
signature?: string;
targets?: Array<string>;
};
raw_data: string;
}>
};
```

[GPR-370] Update sign transaction response type

---

packages/internal/generated-clients/src/mr-openapi.json
packages/internal/generated-clients/src/multi-rollup/models/collection.ts
packages/internal/generated-clients/src/multi-rollup/models/fulfillment-data-request.ts

Renamed a field in the `Collection` response object returned from the following methods available in the Blockchain Data package:
- `getCollection`
- `listCollections`
- `listCollectionsByNFTOwner`
Field has been renamed from `last_metadata_synced_at` to `metadata_synced_at`.
This is a breaking change for any user whose integration is reading this specific field. 
- API response type for Blockchain Data Collection object renamed from from `last_metadata_synced_at` to `metadata_synced_at`.

breaking-change fix: Renamed Collection response object field to be consistent with NFT object

---

packages/checkout/sdk-sample-app/src/components/Connect.tsx
packages/checkout/sdk/src/connect/connect.test.ts
packages/checkout/sdk/src/connect/connect.ts
packages/checkout/sdk/src/sdk.test.ts
packages/checkout/sdk/src/sdk.ts
packages/checkout/sdk/src/types/connect.ts
packages/checkout/sdk/src/types/wallet.ts

https://immutable.atlassian.net/browse/WT-2058
- implement `requestPermissions` function
- added new param `requestWalletPermissions` to `ConnectParams`
- extended the `checkout.connect` function to check for `requestWalletPermissions` and wallet type to determine whether to action `wallet_requestPermissions` or `eth_requestAccounts` 
- add tests
- add `requestWalletPermissions` param when calling `checkout.connect` in sdk sample app

Feat: WT-2058 Add change account functionality to SDK connect

---

.github/workflows/publish-major-version.yaml
.github/workflows/publish.yaml

Adds the GitHub username to the workflow status messages pushed to Slack. 
No impact on SDK users.
- Publish to NPM workflow status messages including the triggering user.

feat: add GitHub triggering actor username to publish workflow messages

---

packages/checkout/sdk/src/widgets/definitions/events/sale.ts
packages/checkout/widgets-lib/src/widgets/sale/SaleWidgetEvents.ts
packages/checkout/widgets-lib/src/widgets/sale/context/SaleContextProvider.tsx
packages/checkout/widgets-lib/src/widgets/sale/hooks/useSaleEvents.ts
packages/checkout/widgets-lib/src/widgets/sale/hooks/useSignOrder.ts
packages/checkout/widgets-lib/src/widgets/sale/views/PayWithCoins.tsx

After a transaction is executed or cancelled handle the necessary events.
* A successful transaction event was being sent every time regardless of transaction completion

fix: [GPR-347][Sale widget] Handle failed/success events for individual transactions

---

packages/checkout/widgets-lib/src/context/view-context/SwapViewContextTypes.ts
packages/checkout/widgets-lib/src/widgets/bridge/components/BridgeReviewSummary.tsx
packages/checkout/widgets-lib/src/widgets/bridge/views/MoveInProgress.tsx
packages/checkout/widgets-lib/src/widgets/swap/SwapWidget.tsx
packages/checkout/widgets-lib/src/widgets/swap/components/SwapButton.tsx
packages/checkout/widgets-lib/src/widgets/swap/views/SwapInProgress.cy.tsx
packages/checkout/widgets-lib/src/widgets/swap/views/SwapInProgress.tsx

Added additional tracking analytics to the Swap and Bridget Widgets success events.
https://immutable.atlassian.net/browse/WT-2071
`checkoutSwapSwapSuccess` includes fromAmount, fromTokenAddress, toAmount, toTokenAddress
`checkoutBridgeInProgress` includes fromWalletAddress, toWalletAddress, amount, fiatAmount, tokenAddress

feat: [WT-2071] Swap and Bridge Widget analytics update

---

packages/checkout/widgets-lib/src/widgets/sale/hooks/useSignOrder.ts
packages/checkout/widgets-lib/src/widgets/sale/views/SaleErrorView.tsx

After Transak emits event `"TRANSAK_ORDER_FAILED"` allow user to retry by redirecting them to Payment Methods view

fix: [Sale Widget] Enable retries after a Transak order fails

---

packages/checkout/widgets-lib/src/components/Transactions/Transactions.tsx
packages/checkout/widgets-lib/src/widgets/bridge/components/BridgeForm.tsx

When clicking back from the Transactions screen, reset the to wallet in state so that wallets are not pre-filled in the wallet network selector.
Also, re-fetch transactions on wallet change in the transactions screen.

Small bridge txn fixes

---

packages/passport/sdk/src/Passport.int.test.ts
packages/passport/sdk/src/Passport.ts
packages/passport/sdk/src/authManager.ts
packages/passport/sdk/src/starkEx/passportImxProvider.ts
packages/passport/sdk/src/starkEx/passportImxProviderFactory.ts
packages/passport/sdk/src/types.ts

The current overrides prevents us from using the dev environment with Passport outside of the SDK because `ImxApiClients` is an internal package. This fixes that by using the existing `imxPublicApiDomain` override to create the client.

fix: NOJIRA passport dev fix

---

.github/CODEOWNERS
.husky/pre-commit

Remove the Jest test command from the Husky pre-commit hook. It should not have been added.
- Test command in the pre-commit hook.
SDK team has been added as the owner of the `.husky` folder. Other teams should not be touching those files.

chore: Revert husky pre-commit script

---

packages/checkout/sdk/src/balances/balances.ts
packages/checkout/widgets-lib/src/components/Transactions/TransactionItem.tsx
packages/checkout/widgets-lib/src/components/Transactions/TransactionItemWithdrawPending.tsx
packages/checkout/widgets-lib/src/components/Transactions/TransactionList.tsx
packages/checkout/widgets-lib/src/lib/balance.test.ts
packages/checkout/widgets-lib/src/lib/balance.ts
packages/checkout/widgets-lib/src/lib/chains.ts
packages/checkout/widgets-lib/src/widgets/swap/components/SwapForm.tsx
packages/checkout/widgets-lib/src/widgets/wallet/components/BalanceItem/BalanceItem.tsx
packages/checkout/widgets-lib/src/widgets/wallet/functions/tokenBalances.test.ts
packages/checkout/widgets-lib/src/widgets/wallet/functions/tokenBalances.ts

Updates to show token icons in Wallet, Bridge, and Swap Widgets.
https://immutable.atlassian.net/browse/WT-2101
Checkout Widgets now displays token icons.

feat: [WT-2101] Map token icons in Checkout Widgets

---

.github/scripts/push-docs.sh
.github/workflows/publish-docs.yaml

Make the Push SDK Reference docs workflow push to the new docs repo name.
No changes to SDK code.

chore: [DX-2652] Push docs to new repo name

---

packages/internal/metrics/package.json
packages/internal/metrics/src/details.ts
packages/internal/metrics/src/initialise.ts
packages/internal/metrics/src/track.ts
packages/internal/metrics/src/utils/constants.ts
packages/internal/metrics/src/utils/globalise.ts
packages/internal/metrics/src/utils/state.ts
sdk/package.json
yarn.lock

Currently, customers using the code split might instantiate multiple metrics pollers. To fix this issue, we'd like to globalise the metrics functions and to prevent the same values being noted in one instance.

fix: globalise metrics functions

---

packages/checkout/widgets-lib/src/components/FormComponents/TextInputForm/TextInputForm.tsx
packages/checkout/widgets-lib/src/widgets/bridge/components/BridgeForm.tsx

Removed the initial gas estimates in the Move Widget amount view. 
Added `enter` key down event to speed up form submission.
The Move Widget amount input view no longer includes a gas fee estimate.

fix: Move Widget gas estimate flow optimisation

---

.github/CODEOWNERS

Adds the code owners for the metrics package

chore: add codeowners for metrics

---

packages/internal/metrics/src/details.ts
packages/internal/metrics/src/index.ts
packages/passport/sdk/src/authManager.ts

This PR reverts immutable/ts-immutable-sdk#1475 to fix an issue with the `access_token` being returned from the `token` endpoint being invalid.
Fixed an issue with the `access_token` that was returned from the `token` endpoint being invalid.

fix: Revert "feat: EXP add cross product identity matching"

---

.github/workflows/publish.yaml

Update the `Publish to NPM` workflow to use the `gh` token to create/push git tags when the GitHub release is created.
- This change will have no impact on external customers
- How tags are created in the Publish workflow
- A tag ruleset will be added along side this PR to prevent non-admins from creating tags in the repo.

update publish workflow, only push tags when creating github release

---

.github/workflows/publish.yaml

Revert [this PR](https://github.com/immutable/ts-immutable-sdk/pull/1506) to stop pushing alpha tags.
Alpha tags are required for the workflow to correctly figure out the next alpha version.
Also used the `platform-sa` token to checkout the repo which gets stored in the local git config and should be used later on to push the tags to GitHub.

fix: revert push tags step

---

packages/checkout/widgets-lib/src/widgets/sale/SaleWidget.tsx
packages/checkout/widgets-lib/src/widgets/sale/SaleWidgetRoot.tsx
packages/checkout/widgets-lib/src/widgets/sale/components/FundingRouteExecute/FundingRouteExecute.tsx
packages/checkout/widgets-lib/src/widgets/sale/views/FundWithSmartCheckout.tsx

Ensure loading screen footer is shown across entire Sale Widget flow

Fix: [Sale Widget] Display footer across all loading screens

---

packages/internal/metrics/src/utils/checkEnv.ts
packages/internal/metrics/src/utils/errorBoundary.test.ts
packages/internal/metrics/src/utils/errorBoundary.ts
packages/internal/metrics/src/utils/request.ts
packages/passport/sdk/package.json
packages/passport/sdk/src/utils/logger.ts
sdk/rollup.config.js
yarn.lock

Fixes an issue where users have monkey-patched their browser environment to have a `process` global value, causing issues with test-env detection code.
It also adds an error boundary and changes the API URL to the new unified API url. (Both work, just proxies)

fix: handle process not defined in browser bundle

---

packages/x-provider/src/signable-actions/registration.ts

The IMX provider `isRegisteredOffChain` function was throwing a `404` error when checking if a unregistered user was registered instead of returning the expected `false` value.
The fix was tested in SDK version [1.14.0-alpha.1](https://www.npmjs.com/package/@imtbl/sdk/v/1.14.0-alpha.1).
- IMX provider `isRegisteredOffChain` function should return a boolean instead of throwing when the user is not registered.

fix: check axios error on isRegisteredOffChain function

---

packages/checkout/sdk/src/widgets/definitions/configurations/wallet.ts
packages/checkout/sdk/src/widgets/definitions/configurations/widget.ts
packages/checkout/widgets-lib/src/factory.ts
packages/checkout/widgets-lib/src/views/top-up/TopUpView.cy.tsx
packages/checkout/widgets-lib/src/widgets/BaseWidgetRoot.ts
packages/checkout/widgets-lib/src/widgets/wallet/WalletWidget.cy.tsx
packages/checkout/widgets-lib/src/widgets/wallet/WalletWidget.tsx
packages/checkout/widgets-lib/src/widgets/wallet/WalletWidgetRoot.tsx
packages/checkout/widgets-lib/src/widgets/wallet/components/BalanceItem/BalanceItem.cy.tsx
packages/checkout/widgets-lib/src/widgets/wallet/components/NetworkMenu/NetworkMenu.cy.tsx
packages/checkout/widgets-lib/src/widgets/wallet/context/WalletContext.ts
packages/checkout/widgets-lib/src/widgets/wallet/views/Settings.tsx
packages/checkout/widgets-lib/src/widgets/wallet/views/WalletBalances.cy.tsx
packages/checkout/widgets-lib/src/widgets/wallet/views/WalletBalances.tsx

Adding functionality into the Disconnect Wallet button in the Wallet Widget. If the current provider is a WalletConnect provider, we make sure to disconnect all existing pairings and disconnect the provider. This enables reconnection in the connect widget with a different mobile wallet.
Wallet Widget Configurations
When creating the Wallet Widget through the factory, you can now pass in flags to show/hide
* Disconnect Button
* Network Menu
Both of these configurations default to true.

feat: WT-2158 handle wallet disconnect

---

packages/x-client/src/IMXClient.ts
packages/x-client/src/config/config.test.ts
packages/x-client/src/config/index.ts

The underlying API clients in the `IMXClient` class were not correctly setting the API keys from Hub in request headers.
`IMXClient` methods should now send the API keys.
- IMXClient methods were not sending Hub API keys with requests

fix: IMXClient not sending API keys

---

packages/checkout/widgets-lib/src/widgets/sale/SaleWidgetEvents.ts
packages/checkout/widgets-lib/src/widgets/sale/context/SaleContextProvider.tsx
packages/checkout/widgets-lib/src/widgets/sale/hooks/useSaleEvents.ts
packages/checkout/widgets-lib/src/widgets/sale/hooks/useSignOrder.ts
packages/checkout/widgets-lib/src/widgets/sale/views/SaleSuccessView.tsx

Improve the integration of the sale widget by:
- Including the tokenIds from order on the success event payload, and
- Removing the transaction settlement waits

fix: [GPR-439][Sale Widget] Include tokenId on the success event payload

---

packages/checkout/sdk/src/widgets/definitions/events/sale.ts
packages/checkout/widgets-lib/src/widgets/sale/views/PaymentMethods.tsx

Fixes broken copy path and missing type definition

fix: [Sale widget] Loading copy and missing type field

---

packages/config/package.json
packages/x-client/package.json
yarn.lock

Remove Core SDK as a dependency from the x-client and config packages, since it is not used.
No impact.
No code changes

chore: [DX-2714] remove unused core sdk dependencies

---

packages/checkout/widgets-lib/src/lib/hooks/useWalletConnect.ts
packages/checkout/widgets-lib/src/widgets/bridge/components/WalletNetworkButton.tsx
packages/checkout/widgets-lib/src/widgets/connect/components/WalletList.tsx

**_MetaMask_**
https://github.com/immutable/ts-immutable-sdk/assets/37326128/03e9d475-1eff-4aeb-b334-80d712bfcb1a
**_Passport_**
https://github.com/immutable/ts-immutable-sdk/assets/37326128/df9cf426-5d66-4897-a1aa-f33cc7aaa12e
https://github.com/immutable/ts-immutable-sdk/assets/37326128/f541c35b-2c90-4d66-a0d5-3a68d18ba298
- showing ChangedYourMind drawer when user rejects connection, all other errors will show UnableToConnect drawer
- replaced generic error view with unable to connect drawer
- add `isWalletConnectEnabled` as dependency to avoid multiple errors for WC initialisation

feat: Hook up error drawers to connect widget

---

packages/blockchain-data/sdk/src/blockchain-data.ts
packages/internal/generated-clients/src/mr-openapi.json
packages/internal/generated-clients/src/multi-rollup/domain/nfts-api.ts

Remove experimental tags from Minting API requests, as part of production release.
Removed experimental tags for the following methods being released to production:
- `createMintRequest`
- `listMintRequests`
- `getMintRequest`
Non-breaking code documentation change.

refactor: Remove experimental tags for Minting API request documentation

---

packages/checkout/sdk/src/fiatRamp/fiatRamp.test.ts
packages/checkout/sdk/src/fiatRamp/fiatRamp.ts

Transak widget can be initialised with a fiat amount or a crypto amount. currently initialising the crypto amount is failing as the value is ignore, given that fiat values take priority.
To fix this, we must ensure that a valid combination of params is set.
**Valid combinations**:
* To set fiat amount pass: `fiatCurrency=usd` or `defaultFiatCurrency=usd` + `defaultFiatAmount=50`
* To set crypto amount pass `cryptoCurrencyCode=usdc` + `defaultCryptoAmount=200`
This PR fix, ensure `defaultFiatAmount` is never sent if `defaultCryptoAmount` was set.
- Test `defaultFiatAmount=50` is included always if not crypto amount set
- Improve params to query string econding by using `URLSearchParams`
- crypto amount now takes priority over fiat amount, if both given only the crypto amount will be passed …

fix: [GPR-477][OnRamp Widget] Fix default crypto amount

---

packages/checkout/sdk/src/widgets/definitions/events/sale.ts
packages/checkout/widgets-lib/src/widgets/sale/SaleWidgetEvents.ts
packages/checkout/widgets-lib/src/widgets/sale/hooks/useSaleEvents.ts
packages/checkout/widgets-lib/src/widgets/sale/hooks/useSignOrder.ts
packages/checkout/widgets-lib/src/widgets/sale/types.ts
packages/checkout/widgets-lib/src/widgets/sale/views/PayWithCard.tsx
packages/checkout/widgets-lib/src/widgets/sale/views/PayWithCoins.tsx

Add transaction id to sale widget events to help trace the orders across flows

Fix:[Sale Widget] Add transaction id to events

---

packages/checkout/sdk/src/widgets/definitions/configurations/wallet.ts

Fix up jsdocs for WalletWidgetConfiguration so that it'll appear in the sdk reference site.

fix: jsdoc for WalletWidgetConfiguration

---

packages/checkout/widgets-lib/src/widgets/sale/views/FundWithSmartCheckout.tsx

Delay calls to smart checkout until token address was set
Sale widget was throwing error `Can't check wallet balances` on first time, given that calls to get `client-config` were running slow in sandbox.

[GASBT-10][Sale Widget] Delay calls to smart checkout until token address is set

---

packages/passport/sdk/src/confirmation/confirmation.test.ts
packages/passport/sdk/src/confirmation/confirmation.ts
packages/passport/sdk/src/confirmation/types.ts

https://github.com/immutable/ts-immutable-sdk/assets/3668156/5853e32f-119e-45a5-acd8-ad031fc817d1
* send Post message to popup window when received the window is ready event.

[ID-1456]send confirmation start post message to confirmation screen

---

.github/scripts/update-docs-link.sh

Fix the update docs link script ["redirection unexpected" error](https://github.com/immutable/ts-immutable-sdk/actions/runs/8366243195/job/22906013440) which occurred when publishing a release.
There are no functional changes to the `@imtbl/sdk` code.
The previous version of the script used [here strings](https://unix.stackexchange.com/a/80372/7684) (`<<< $VERSION`), which didn't work on the Github runners. Therefore, fall back to the more traditional `echo $VERSION |`

chore: [DX-2725] fix update docs link script

---

packages/checkout/sdk/src/smartCheckout/balanceCheck/balanceCheck.ts
packages/checkout/sdk/src/smartCheckout/balanceCheck/balanceRequirement.test.ts
packages/checkout/sdk/src/smartCheckout/balanceCheck/balanceRequirement.ts

Fix for smart checkout balance requirements incorrectly calculation formatted balances based on default token data.
Smart checkout balance requirements formatted balance is now retrieving the correct token contract information (decimals, name, symbol) when no balance is found via Blockscout.

fix: Smart checkout balance token information

---

packages/passport/sdk-sample-app/src/context/ImmutableProvider.tsx

This PR fixes an issue where the Passport SDK sample app would hit the `sandbox` IMX API when the `dev` environment had been selected. This was caused by a recent change that removed all references to the `core-sdk` from this SDK.

chore: ID-1514 Fixed dev for the Passport SDK sample app

---

packages/orderbook/package.json
packages/orderbook/src/seaport/seaport-lib-factory.ts
sdk/package.json
yarn.lock

Upgrade from seaport-js v3 to v4. There are no interface differences between these versions, however v4 fixes partial fill bugs and adds support for Seaport 1.6, while retaining support for Seaport 1.5

chore: upgrade to seaport-js v4

---

package.json
packages/config/package.json
packages/internal/bridge/sdk/package.json
packages/internal/cryptofiat/package.json
packages/internal/dex/sdk/package.json
packages/internal/factory/sdk/package.json
packages/internal/generated-clients/package.json
packages/internal/guardian/package.json
packages/internal/metrics/package.json
packages/internal/toolkit/package.json
packages/internal/version-check/package.json
packages/passport/sdk/package.json
packages/x-client/package.json
packages/x-provider/package.json
sdk/package.json

Bump engine version to a minimum of 20.11.0, the current LTS version.
No functionality/behavioural changes
CI and local dev are already using `v20.11.0`

chore: bump engine version to v20.11.0

---

.github/workflows/publish.yaml

Fix args used when calling `version-up.sh` in the publish workflow
Also add debugging statements for the future
This might be easier to review commit by commit.
No code / functionality changes to the SDK

chore: [DX-2697] Use correct versions

---

.github/workflows/secret-scan.yaml

The GitLeaks workflow doesn't support the `merge_group` Github action event.
The workflow is throwing an error and preventing PR's from merging.
PR removes the `merge_group` event to unblock PR's. 
The change should not impact external customers as it only changes the GitLeaks workflow events.
- `merge_group` event from GitLeaks workflow

fix: remove merge_group event from secret scanning

---

.github/workflows/build-lint-typecheck-test.yaml
.github/workflows/functional-tests-imx.yml
.github/workflows/functional-tests-zkevm.yml
.github/workflows/playwright.yml

In order to speed up the build queue, this PR prevents checks that have already run in the merge queue from running on push to main. 
No other code changes.

chore: [DX-2681] if a check is run in a merge queue, don't run it on push to main

---

packages/passport/sdk/src/Passport.test.ts
packages/passport/sdk/src/Passport.ts

This PR resolves an issue where users were not being correctly logged out of their Magic wallet.
- Passport: Fixed an issue where users were not correctly logged out of their Magic wallet when using the `redirect` logout mode.

fix: ID-1538 Resolved issue with redirect logout not logging out of Magic

---

packages/checkout/sdk/src/smartCheckout/allowance/erc721.test.ts
packages/checkout/sdk/src/smartCheckout/allowance/erc721.ts

tokenId is uint256 so must be a BigNumber
Test in checkout sdk-sample-app
When listing NFTs with a number that is too big to fit in a JS number, it will succeed.

fix: tokenId is uint256 so must be a BigNumber

---

packages/orderbook/src/api-client/api-client-factory.ts
packages/orderbook/src/config/config.ts
packages/orderbook/src/orderbook.ts
packages/orderbook/src/seaport/seaport-lib-factory.ts
packages/orderbook/src/seaport/seaport.ts

Previously if an Immutable rate limiting key was provided to the orderbook config, it was not added to the request headers. This PR fixes that
- Add immutable rate limit api key to headers when provided from orderbook module

fix: Support apiKey from orderbook module when provided

---

packages/passport/sdk/src/zkEvm/sendTransaction.test.ts
packages/passport/sdk/src/zkEvm/sendTransaction.ts
packages/passport/sdk/src/zkEvm/signTypedDataV4.test.ts
packages/passport/sdk/src/zkEvm/signTypedDataV4.ts
packages/passport/sdk/src/zkEvm/zkEvmProvider.test.ts
packages/passport/sdk/src/zkEvm/zkEvmProvider.ts

Updated the EVM provider `eth_sendTransaction` and `eth_signTypedData_v4` methods to open the confirmation popup before the ethSigner is initialised. This should prevent browsers from blocking the popup, since the popup will no longer be opened after an async call.
On the zkEVM provider:
- eth_sendTransaction
- eth_signTypedData_v4
- eth_signTypedData
Before:
https://github.com/immutable/ts-immutable-sdk/assets/24399271/91840cc7-436a-4e75-b8d6-3a60d299691d
After:
https://github.com/immutable/ts-immutable-sdk/assets/24399271/ff2954be-1b90-4341-af92-5144391d7cb2

fix: ID-1584 Force confirmation popup to be opened while provider is instantiated

---

packages/checkout/widgets-lib/src/locales/en.json
packages/checkout/widgets-lib/src/locales/ja.json
packages/checkout/widgets-lib/src/locales/ko.json
packages/checkout/widgets-lib/src/locales/zh.json
packages/checkout/widgets-lib/src/views/top-up/TopUpView.cy.tsx
packages/checkout/widgets-lib/src/views/top-up/TopUpView.tsx

Introducing a link to Layerswap in the Toolkit, opening up in a new tab.
New Top Up feature: advances options for fast bridge and CEX deposits (Layerswap)

feat: GPR-581 - "Advanced Options" in Balance Widget top up screen

---

packages/passport/sdk/src/zkEvm/zkEvmProvider.test.ts
packages/passport/sdk/src/zkEvm/zkEvmProvider.ts

This PR adds a call to the `identify` method in `eth_requestAccounts`
- Passport: Added additional tracking to `eth_requestAccounts`

chore: ID-1588 Add identify to eth_requestAccounts

---

packages/checkout/widgets-lib/src/components/ChangedYourMindDrawer/ChangedYourMindDrawer.tsx
packages/checkout/widgets-lib/src/components/NotEnoughGas/NotEnoughGas.tsx
packages/checkout/widgets-lib/src/components/NotEnoughImx/NotEnoughImx.tsx
packages/checkout/widgets-lib/src/components/Transactions/NotEnoughEthToWithdraw.tsx
packages/checkout/widgets-lib/src/components/UnableToConnectDrawer/UnableToConnectDrawer.tsx
packages/checkout/widgets-lib/src/lib/constants.ts

CloudImage component within the Checkout widgets now correctly switches its CDN image resizer url based on environment.
[GPR-594](https://immutable.atlassian.net/browse/GPR-594)
CloudImage component imageResizerUrl attributes.
[GPR-594]: https://immutable.atlassian.net/browse/GPR-594?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: [GPR-594] Updates to cloud image component image resizer url based on environment

---

packages/checkout/sdk-sample-app/src/components/SmartCheckoutForm.tsx
packages/checkout/sdk-sample-app/src/pages/SmartCheckout.tsx
packages/checkout/sdk/src/connect/connect.test.ts
packages/checkout/sdk/src/network/network.test.ts
packages/checkout/sdk/src/provider/provider.test.ts
packages/checkout/sdk/src/provider/provider.ts
packages/checkout/sdk/src/sdk.test.ts
packages/checkout/sdk/src/sdk.ts
packages/checkout/sdk/src/smartCheckout/routing/routingCalculator.ts
packages/checkout/sdk/src/smartCheckout/smartCheckout.test.ts
packages/checkout/sdk/src/smartCheckout/smartCheckout.ts
packages/checkout/sdk/src/types/smartCheckout.ts

Smart checkout optimisations to flag only the funding routes you are interested in calculating.
[GPR-551](https://immutable.atlassian.net/browse/GPR-551)
Added `routingOptions` to Smart checkout to flag the funding paths swap, bridge, onRamp
CreateProvider to use new injected providers listing.
[GPR-551]: https://immutable.atlassian.net/browse/GPR-551?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: [GPR-551] Smart checkout routing options flags

---

packages/checkout/sdk/src/types/config.ts
packages/checkout/sdk/src/widgets/definitions/events/connect.ts
packages/checkout/sdk/src/widgets/definitions/parameters/connect.ts
packages/checkout/sdk/src/widgets/definitions/types.ts
packages/checkout/widgets-lib/src/lib/hooks/useInjectedProviders.ts
packages/checkout/widgets-lib/src/lib/hooks/useWalletConnect.ts
packages/checkout/widgets-lib/src/lib/walletConnect.ts
packages/checkout/widgets-lib/src/widgets/connect/ConnectWidget.tsx
packages/checkout/widgets-lib/src/widgets/connect/ConnectWidgetRoot.tsx
packages/checkout/widgets-lib/src/widgets/connect/components/WalletList.tsx
packages/checkout/widgets-lib/src/widgets/connect/connectWidgetEvents.ts
packages/checkout/widgets-lib/src/widgets/connect/views/ConnectWallet.tsx
packages/checkout/widgets-sample-app/src/components/ui/marketplace-orchestrator/MainPage.tsx

Checkout connect widget supports a `blocklistWalletRdns` param to restrict the wallets in the wallet listing.
blocklistWalletRdns param to support restricting specific wallets.
`Walletconnect-provider-updated` event to propagate walletConnectManager reference.
WalletConnect option will always start a new session via the Connect widget

feat: [GPR-559] Checkout Connect widget to support blocklist

---

packages/checkout/widgets-lib/src/lib/hooks/useWalletConnect.ts
packages/checkout/widgets-lib/src/lib/walletConnect.ts

We now correctly wait for WalletConnect to be ready via a promise when attempting to access it's provider.
[GPR-590](https://immutable.atlassian.net/browse/GPR-590)
WallerConnect getProvider now correctly resolves when WalletConnect is ready.
[GPR-590]: https://immutable.atlassian.net/browse/GPR-590?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: [GPR-590] Resolve provider when walletConnect is not ready

---

packages/checkout/widgets-lib/src/components/Transak/TransakIframe.tsx
packages/checkout/widgets-lib/src/components/Transak/useTransakEvents.ts
packages/checkout/widgets-lib/src/components/Transak/useTransakIframe.ts
packages/checkout/widgets-lib/src/widgets/on-ramp/views/OnRampMain.tsx
packages/checkout/widgets-lib/src/widgets/sale/components/WithCard.tsx
packages/checkout/widgets-lib/src/widgets/sale/hooks/useSaleEvents.ts

https://immutable.atlassian.net/browse/GPR-586
https://immutable.atlassian.net/browse/GPR-587
Some Segment events in Checkout widgets are sending the user's email. Due to data privacy regulations we should not do this, so remove them.
* `email` from events in `SaleWidget` and `OnRampWidget`
* rename `userId` to `walletAddress` in Transak segment events

fix: [GPR-586] Remove email from Segment tracking

---

packages/passport/sdk/src/confirmation/confirmation.ts
packages/passport/sdk/src/confirmation/types.ts

This PR adds additional message types for the message that is posted to the SDK from the transaction confirmation screen.
- Passport: Added support for additional transaction confirmation messages

chore: ID-1601 Added additional transaction confirmation message types

---

packages/checkout/sdk/src/sdk.test.ts
packages/checkout/sdk/src/sdk.ts
packages/checkout/sdk/src/smartCheckout/routing/routingCalculator.test.ts
packages/checkout/sdk/src/smartCheckout/routing/routingCalculator.ts
packages/checkout/sdk/src/smartCheckout/smartCheckout.test.ts
packages/checkout/sdk/src/smartCheckout/smartCheckout.ts
packages/checkout/sdk/src/types/smartCheckout.ts
packages/checkout/widgets-lib/src/widgets/sale/functions/smartCheckoutUtils.ts

Update `smartCheckout` to accept `onComplete` and `onFundingRoute` callbacks.
Add `onComplete` and `onFundingRoute` optional callbacks to `smartCheckout`. 
When `onComplete` callback is passed in, the method returns `SmartCheckoutSufficient` early while allowing the user to get notified about funding routes through `onComplete` callback.
Allows the user to get notified on each funding route found, avoiding the need to wait until all funding routes are found.
Refactor the way `routingCalculator` constructs routes.

[feat]gpr-593 smart checkout onComplete and onFundingRoute callbacks

---

package.json

Change `@imtbl/checkout-widgets-lib` to `@imtbl/checkout-widgets` in the build script and only build `@imtbl/sdk` for `build:onlysdk`
No code changes.

chore: make build:onlysdk actually only build the sdk

---

packages/checkout/sdk/src/smartCheckout/smartCheckout.test.ts
packages/checkout/sdk/src/smartCheckout/smartCheckout.ts

Add `overrideSufficientBalanceCheckResult` to get funding routes when `sufficient: true` and `onComplete` callback is defined.

[feat] gpr 536 smart checkout override balance requirement on sufficient

---

packages/passport/sdk/src/Passport.test.ts
packages/passport/sdk/src/Passport.ts
packages/passport/sdk/src/confirmation/confirmation.test.ts
packages/passport/sdk/src/confirmation/confirmation.ts
packages/passport/sdk/src/confirmation/types.ts

This PR removes the logic that opens the `logout` page of the transaction confirmation app.

chore: ID-1591 Remove logic to logout of transaction confirmation

---

packages/checkout/widgets-lib/src/components/Transak/TransakIframe.tsx
packages/checkout/widgets-lib/src/components/Transak/useTransakIframe.ts
packages/checkout/widgets-lib/src/widgets/sale/components/WithCard.tsx
packages/checkout/widgets-sample-app/src/components/ui/sale/sale.tsx

The old way of using a query string with all data will break when the payload is too big. Transak implemented this new approach so we can post the data before generating the URL.

feat: [GPR-476][Sale Widget] Generate transaction ID for Transak's NFT sale

---

packages/checkout/sdk/src/transaction/transaction.test.ts
packages/checkout/sdk/src/transaction/transaction.ts
packages/checkout/widgets-lib/src/widgets/swap/components/SwapButton.tsx
packages/checkout/widgets-lib/src/widgets/swap/components/SwapForm.tsx
packages/checkout/widgets-lib/src/widgets/swap/views/ApproveERC20Onboarding.tsx
packages/checkout/widgets-lib/src/widgets/swap/views/SwapCoins.tsx
packages/checkout/widgets-sample-app/src/components/ui/marketplace-orchestrator/MainPage.tsx

Added support for zero IMX balance swaps in the swap widget. Swap transactions for Passport users have been adjusted to support zero gas.
IMX zero balance checks in swap widget for Passport users, as gas fees don't apply.

fix: [GPR-528] Add support for zero IMX balance swaps with Passport in Swap widget

---

packages/checkout/widgets-lib/src/widgets/sale/SaleWidget.tsx
packages/checkout/widgets-lib/src/widgets/sale/components/CreditCardWarningDrawer.tsx
packages/checkout/widgets-lib/src/widgets/sale/context/SaleContextProvider.tsx
packages/checkout/widgets-lib/src/widgets/sale/views/PaymentMethods.tsx

Move the CC warning component to the root so it shows up globally.

[feat][sale widget] Move CC warning drawer to the root

---

packages/internal/bridge/sdk/src/tokenBridge.ts

Error logging in the tokenBridge is returning undefined.
Fix to address the simulation error message being reported as `undefined`

fix: [NO-JIRA] Tenderly gas simulation error logging

---

packages/passport/sdk/src/Passport.int.test.ts
packages/passport/sdk/src/authManager.test.ts
packages/passport/sdk/src/authManager.ts

Updates logout functions in AuthManager to use `/oidc/` endpoint (documented https://auth0.com/docs/authenticate/login/logout/log-users-out-of-auth0) to work around looming changes to third-party cookie restrictions
Changes logout method from retrieving user session via cookie to supplying the user session to the logout endpoint
* New method to build logout arguments, and supplying those to the logout functions
* Rewrites URL construction to use URI objects rather than compounding strings.

feat: ID-1590 Updates AuthManager Logout to use OIDC methods

---

packages/checkout/widgets-lib/src/components/Fees/Fees.tsx
packages/checkout/widgets-lib/src/components/FeesBreakdown/FeesBreakdown.tsx
packages/checkout/widgets-lib/src/components/FeesBreakdown/FeesBreakdownStyles.tsx
packages/checkout/widgets-lib/src/locales/en.json
packages/checkout/widgets-lib/src/locales/ja.json
packages/checkout/widgets-lib/src/locales/ko.json
packages/checkout/widgets-lib/src/locales/zh.json
packages/checkout/widgets-lib/src/widgets/bridge/functions/BridgeFees.ts
packages/checkout/widgets-lib/src/widgets/swap/components/SwapForm.tsx
packages/checkout/widgets-lib/src/widgets/swap/functions/swapFees.test.ts

Updates to Swap widget fee breakdown.
[CM-521](https://immutable.atlassian.net/browse/CM-521)
Separated the Swap widget fees into gas, approval gas, and secondary fees.
Removed swap gas fees from the UI for Passport users.
[CM-521]: https://immutable.atlassian.net/browse/CM-521?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: [CM-521] Updates to Swap widget fee breakdown

---

packages/internal/generated-clients/src/mr-openapi.json
packages/internal/generated-clients/src/multi-rollup/domain/nft-owners-api.ts
packages/internal/generated-clients/src/multi-rollup/domain/nfts-api.ts
packages/internal/generated-clients/src/multi-rollup/domain/passport-api.ts
packages/internal/generated-clients/src/multi-rollup/models/activity-nft.ts
packages/internal/generated-clients/src/multi-rollup/models/fill-status.ts
packages/internal/generated-clients/src/multi-rollup/models/get-mint-request-result.ts
packages/internal/generated-clients/src/multi-rollup/models/mint-asset.ts
packages/internal/generated-clients/src/multi-rollup/models/protocol-data.ts
packages/internal/generated-clients/src/multi-rollup/models/seaport-create-listing-metadata.ts

Regenerate internal OpenAPI clients to be in sync with current production API
- Added `from_updated_at` filter to `ListNFTsByAccountAddress`
- Added `account_address` filter to `ListOwnersByContractAddress`
- Added `amount` field to Sale Activity return type for sales involving ERC1155 tokens
- Added `amount` to `CreateMintRequest` and `ListMintRequest` to support minting on ERC1155 colllections
- `SeaportCreateListingMetadata` only accepts a single sell item instead of an array
- `getLinkedAddresses` in `passport` package is marked is now deprecated

chore: Regenerate interal OpenAPI clients

---

packages/checkout/widgets-lib/src/widgets/wallet/components/BalanceItem/BalanceItem.tsx

`MenuItem.FramedImage` uses `CloudImage` under the hood, so you need to pass the `imageResizeServiceUrl` to it in order for the image to load in sandbox and prod.
There are other instances of `MenuItem.FramedImage` that needs this fix, but this PR fixes the known occurrence of this in the Gems Game.

fix: Coin logos not loading in the Balance Widget

---

packages/checkout/sdk/src/widgets/definitions/configurations/sale.ts
packages/checkout/widgets-lib/src/widgets/sale/SaleWidget.tsx
packages/checkout/widgets-lib/src/widgets/sale/SaleWidgetRoot.tsx
packages/checkout/widgets-lib/src/widgets/sale/context/SaleContextProvider.tsx
packages/checkout/widgets-lib/src/widgets/sale/hooks/useSignOrder.ts
packages/checkout/widgets-lib/src/widgets/sale/types.ts
packages/checkout/widgets-lib/src/widgets/sale/views/PayWithCoins.tsx

Added `waitFulfillmentSettlements` to sale widget config to enable/disable wait for transaction settlement. `true` by default.

feat: [CM-632][Sale Widget] Add configuration flat to enable/disable transaction finality confirmation

---

.github/scripts/update-docs-link.sh

Fix the reference workflow failing. Broken by https://github.com/immutable/docs/pull/928
No code changes. Just CI.

chore: [DX-2802] fix failing publish docs workflow

---

.github/workflows/functional-tests-zkevm.yml

Rename the zkEVM function test job name so I can be excluded from the required status checks.

fix: rename zkEVM job

---

packages/checkout/sdk/src/widgets/definitions/parameters/sale.ts
packages/checkout/widgets-lib/src/lib/utils.ts
packages/checkout/widgets-lib/src/widgets/sale/SaleWidget.tsx
packages/checkout/widgets-lib/src/widgets/sale/SaleWidgetRoot.tsx
packages/checkout/widgets-lib/src/widgets/sale/components/OrderItem.tsx
packages/checkout/widgets-lib/src/widgets/sale/components/OrderItems.tsx
packages/checkout/widgets-lib/src/widgets/sale/components/OrderReview.tsx
packages/checkout/widgets-lib/src/widgets/sale/components/SelectCoinDropdown.tsx
packages/checkout/widgets-lib/src/widgets/sale/components/WithCard.tsx
packages/checkout/widgets-lib/src/widgets/sale/context/SaleContextProvider.tsx
packages/checkout/widgets-lib/src/widgets/sale/functions/fetchFundingBalances.ts
packages/checkout/widgets-lib/src/widgets/sale/functions/fetchFundingBalancesUtils.test.ts
packages/checkout/widgets-lib/src/widgets/sale/functions/fetchFundingBalancesUtils.ts
packages/checkout/widgets-lib/src/widgets/sale/functions/transformToClientConfig.test.ts
packages/checkout/widgets-lib/src/widgets/sale/functions/transformToClientConfig.ts
packages/checkout/widgets-lib/src/widgets/sale/functions/transformToOrderQuote.test.ts
packages/checkout/widgets-lib/src/widgets/sale/functions/transformToOrderQuote.ts
packages/checkout/widgets-lib/src/widgets/sale/hooks/useClientConfig.ts
packages/checkout/widgets-lib/src/widgets/sale/hooks/useFundingBalances.ts
packages/checkout/widgets-lib/src/widgets/sale/hooks/useQuoteOrder.ts
packages/checkout/widgets-lib/src/widgets/sale/hooks/useSmartCheckout.ts
packages/checkout/widgets-lib/src/widgets/sale/types.ts
packages/checkout/widgets-lib/src/widgets/sale/utils/pricing.test.ts
packages/checkout/widgets-lib/src/widgets/sale/utils/pricing.ts
packages/checkout/widgets-lib/src/widgets/sale/views/OrderSummary.tsx
packages/checkout/widgets-sample-app/src/App.tsx
packages/checkout/widgets-sample-app/src/components/ui/sale/sale.tsx

Improve how primary sales widget gets the quote and configurations for an order. Instead of the widget knowing which `amount` needs to be paid, it can now instead pass the items `sku` & `qty` to the `/client-config` service, and it will be able to return a response with by item amounts and total amounts including conversions.
**BREAKING CHANGE:**
Requires customers to implement new [Quotes endpoint](https://docs.immutable.com/docs/zkEVM/products/checkout/widgets/primary-sales/backend/byo#quote-endpoint)
**Before:**
**After: Multi item with correct pricing conversion**
- Able to list multiple products multiple currency
- Able to quote a price by having the items sku and qty
- No longer required to be initialised with the `amount` param
- `amount` param
- Item pricing is display correct in …

feat: [CM-607][Sale Widget] Get order config from product skus + qty

---

packages/orderbook/src/api-client/api-client.ts
packages/orderbook/src/openapi/mapper.ts
packages/orderbook/src/openapi/sdk/OrderBookClient.ts
packages/orderbook/src/openapi/sdk/core/OpenAPI.ts
packages/orderbook/src/openapi/sdk/index.ts
packages/orderbook/src/openapi/sdk/models/FillStatus.ts
packages/orderbook/src/openapi/sdk/models/Order.ts
packages/orderbook/src/openapi/sdk/models/ProtocolData.ts
packages/orderbook/src/orderbook.ts
packages/orderbook/src/seaport/map-to-seaport-order.ts
packages/orderbook/src/seaport/seaport.test.ts
packages/orderbook/src/seaport/seaport.ts
packages/orderbook/src/types.ts

Adding ERC1155 token support to the orderbook to enable orders containing ERC1155 tokens to be created and filled using the SDK.
* ERC1155 support to the orderbook.
* Partials order fulfillment for ERC1155 orders.

TD-1365: feat: Add ERC1155 & partial fills support to Orderbook

---

packages/checkout/widgets-lib/src/components/ChangedYourMindDrawer/ChangedYourMindDrawer.tsx
packages/checkout/widgets-lib/src/components/CoinSelector/CoinSelectorOption.tsx
packages/checkout/widgets-lib/src/components/FormComponents/SelectForm/SelectForm.tsx
packages/checkout/widgets-lib/src/components/FormComponents/SelectInput/SelectInput.tsx
packages/checkout/widgets-lib/src/components/NetworkSwitchDrawer/NetworkSwitchDrawer.tsx
packages/checkout/widgets-lib/src/components/NotEnoughGas/NotEnoughGas.tsx
packages/checkout/widgets-lib/src/components/NotEnoughImx/NotEnoughImx.tsx
packages/checkout/widgets-lib/src/components/Transactions/ChangeWallet.tsx
packages/checkout/widgets-lib/src/components/Transactions/NotEnoughEthToWithdraw.tsx
packages/checkout/widgets-lib/src/components/Transactions/TransactionItem.tsx
packages/checkout/widgets-lib/src/components/Transactions/TransactionItemWithdrawPending.tsx
packages/checkout/widgets-lib/src/components/UnableToConnectDrawer/UnableToConnectDrawer.tsx
packages/checkout/widgets-lib/src/widgets/bridge/BridgeWidget.tsx
packages/checkout/widgets-lib/src/widgets/bridge/components/BridgeForm.tsx
packages/checkout/widgets-lib/src/widgets/bridge/views/Bridge.tsx
packages/checkout/widgets-lib/src/widgets/swap/components/SwapForm.tsx
packages/checkout/widgets-lib/src/widgets/wallet/components/BalanceItem/BalanceItem.tsx

Updates to all token images and use of the Biome Cloud Image component to skip the Immutable Image Resizer.
[CM-616](https://immutable.atlassian.net/browse/CM-616)
All token images loading now correctly display when loaded outside of an immutable.com domain.
[CM-616]: https://immutable.atlassian.net/browse/CM-616?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: [CM-616] Checkout widgets cloud image component refactor

---

packages/checkout/sdk/src/sdk.ts
packages/checkout/sdk/src/transaction/transaction.ts
packages/checkout/widgets-lib/src/context/view-context/BridgeViewContextTypes.ts
packages/checkout/widgets-lib/src/context/view-context/ViewContext.test.ts
packages/checkout/widgets-lib/src/locales/en.json
packages/checkout/widgets-lib/src/locales/ja.json
packages/checkout/widgets-lib/src/locales/ko.json
packages/checkout/widgets-lib/src/locales/zh.json
packages/checkout/widgets-lib/src/widgets/bridge/BridgeWidget.tsx
packages/checkout/widgets-lib/src/widgets/bridge/components/BridgeReviewSummary.tsx
packages/checkout/widgets-lib/src/widgets/bridge/components/WalletAndNetworkSelector.tsx
packages/checkout/widgets-lib/src/widgets/bridge/functions/TransferErc20.ts
packages/checkout/widgets-lib/src/widgets/bridge/views/ApproveTransaction.tsx
packages/checkout/widgets-lib/src/widgets/bridge/views/MoveInProgress.tsx

- Create generic `checkout.providerCall` to wrap non-sendTransaction calls and still get validation + error handling  (e.g. ERC20 transfer)
- Reuse existing network drawer to allow "to" network selection with rules: Passport MUST be L2, if the same wallet is selected for to & from it must be a bridge. 
- Estimate gas for an L2 transfer directly in BridgeReviewSummary
- Initiate transfer from ApproveTransaction
- Update MoveInProgress screen to show different success state for transfers. Also don't highlight the "Transactions" button.
- The Checkout Bridge widget can now be used to transfer tokens between zkEVM wallets!

feat: ID-1674 allow L2 token transfers via Checkout bridge widget

---

packages/orderbook/src/seaport/map-to-seaport-order.ts
packages/orderbook/src/seaport/seaport.ts

For fulfilment and cancel flows, use the zone contract address in the order data and not the hardcoded config value.
This allows orders to be created when the application only had zone V1 in play be filled when the application has multiple zones V1 and V2 enabled.

TD-1359: chore: use the zone contract address in the order data and not the hardcoded config value.

---

packages/checkout/widgets-lib/src/widgets/swap/functions/swapConversionRate.test.ts
packages/checkout/widgets-lib/src/widgets/swap/functions/swapConversionRate.ts

* Handles uncaught exception showing Swap Fees when `quotesProcessor` returns no fees
* On dev environments, the `fees` array is empty when swapping `tIMX > WIMX`, causing the Swap widget to crash
* Fallback to 0 if this fees are not available when displaying Swap secondary fees
https://github.com/immutable/ts-immutable-sdk/assets/13159042/185b4a32-87eb-4404-9374-2f667c55ffd7

fix: Safely handle empty Swap fees

---

packages/checkout/sdk/src/smartCheckout/routing/swap/swapRoute.test.ts
packages/checkout/sdk/src/smartCheckout/routing/swap/swapRoute.ts
packages/checkout/sdk/src/types/smartCheckout.ts

Including field `basisPoints` from `quote` on smart checkout response, to allow consumer to calculate % fee applied on secondary fees.

fix: [CM-638] Include quote basis Points on smartCheckout response

---

packages/checkout/widgets-lib/src/widgets/sale/components/OrderItem.tsx
packages/checkout/widgets-lib/src/widgets/sale/components/OrderItems.tsx
packages/checkout/widgets-lib/src/widgets/sale/components/PaymentOption.tsx
packages/checkout/widgets-lib/src/widgets/sale/components/PaymentOptions.tsx

-  Improve menu items rendering config to allow listed items to fit in screen in scenarios where the list are too large.
- Added a slot for rendering order fees ( Fees UI done in next PR )

chore: [CM-638][Sale Widget] Improve menu items display

---

packages/internal/bridge/sdk/src/constants/bridges.ts
packages/internal/bridge/sdk/src/tokenBridge.ts
packages/internal/bridge/sdk/src/types/tenderly.ts

Currently, we are using tenderly simulate batch API to estimate gas but Tenderly team has recently implemented estimate gas API that is faster and 10x less expensive.
This PR switches the usage of simulation to estimation in the bridge SDK.
This PR changed from tenderly simulation API to tenderly node estimation API inside the bridge dynamic gas estimation.

feat: Switch to tenderly estimation

---

packages/checkout/widgets-lib/src/widgets/sale/components/CoinsDrawer.tsx

Hide more options divider from sale widget coins drawer if no fiat payments options are available.

[fix][sale widget] cm-658 hide more options divider if no fiat payment options are available

---

packages/checkout/sdk/src/smartCheckout/sell/sell.test.ts
packages/checkout/sdk/src/smartCheckout/sell/sell.ts
packages/checkout/sdk/src/types/smartCheckout.ts

A previous change introduced a minor type break. This restores backwards compatibility by introducing a deprecated type that matches the previous type, and ensure the code behaves as expected when that type is provided
Backwards compatible SellItem type

fix: update the checkout.Sell interface to allow undefined type property

---

packages/checkout/widgets-lib/src/views/top-up/TopUpView.tsx

**Footer is removed**
**Which fixes Immutable logo being cut off at bottom**

fix: [CM-645] Remove Top up view footer

---

packages/passport/sdk/src/overlay/elements.ts
packages/passport/sdk/src/overlay/overlay.ts

- Fix issue with background not being blurred on Safari & iPhone
- Append font links to head to import Roboto

fix: ID-1732 Fix background blur and append required font links to the head

---

packages/checkout/widgets-lib/src/widgets/on-ramp/OnRampWidget.tsx
packages/checkout/widgets-sample-app/src/components/ui/sale/sale.tsx

fix: [CM 660][Sale Widget] Fix onramp prefill

---

packages/checkout/widgets-lib/src/widgets/swap/functions/swapConversionRate.test.ts
packages/checkout/widgets-lib/src/widgets/swap/functions/swapConversionRate.ts

`expandedFromAmount` had a scientific notation format (e.g. `1e+21`) when the amount was >= 10^21. When it was passed to `BigNumber.from` it caused an `invalid BigNumber` error.
Use `parseUnits` from `ethers` to convert `fromAmount` to integer.

[fix]cm-663 swap conversion bug fix scientific notation

---

packages/orderbook/src/seaport/seaport.ts
tests/func-tests/zkevm/package.json
tests/func-tests/zkevm/yarn.lock

The `fulfillOrders` Seaport SDK function has a bug which causes the fees to not be scaled in proportion to the size of the order being filled. This could result in failed balance checks because the user is expected to have more funds than strictly required to fill the order. The excess funds are then returned back to the user by the Seaport settlement so there is no net loss of funds.
This PR adds a temporary workaround to use an alternate function that works just as expected in terms of scaling the fees for the proportion of the order being filled.
This PR doesn't address the fee scaling issue in the case of BulkOrder fulfillments - a PR will be submitted against the Seaport SDK repository to address this issue permanently.

TD-1359: fix: add temporary workaround for partial fills fees scaling issue.

---

packages/checkout/widgets-lib/src/locales/en.json
packages/checkout/widgets-lib/src/locales/ja.json
packages/checkout/widgets-lib/src/locales/ko.json
packages/checkout/widgets-lib/src/locales/zh.json
packages/checkout/widgets-lib/src/widgets/bridge/components/BridgeReviewSummary.tsx
packages/checkout/widgets-lib/src/widgets/bridge/functions/BridgeFees.ts

Renames Bridge Service Fee labels.
* Replaces `Service Fees` with 
* * `Ethereum gas fees` when withdrawing
* * `zkEVM gas fees` when depositing
* Improves typing
https://immutable.atlassian.net/browse/CM-532
**L2 -> L1**
**L1 -> L2**

feat:[CM-532][Bridge Widget] Rename Bridge Service Fee Labels

---

packages/checkout/widgets-lib/src/widgets/sale/components/CoinsDrawer.tsx
packages/checkout/widgets-lib/src/widgets/sale/components/PaymentOptions.tsx

Do not render `more options` section when all options are disabled
Given that `debit` and `credit` options were disabled:
**Before**
**After**

fix: [Sale WIdget] Do not render `more options` section when all options are disabled

---

packages/checkout/widgets-lib/src/lib/utils.ts
packages/checkout/widgets-lib/src/widgets/sale/functions/transformToOrderQuote.test.ts
packages/checkout/widgets-lib/src/widgets/sale/functions/transformToOrderQuote.ts
packages/checkout/widgets-lib/src/widgets/sale/hooks/useQuoteOrder.ts
packages/checkout/widgets-lib/src/widgets/sale/views/OrderSummary.tsx

When `preferredCurrency` is given, the override should apply but only remove other currencies as the intention is to only settle the coin on the preferred currency.
For example:
- Accepted currencies: USDC, ETH, GOG
- If, preferred currency = GOG, then Accepted currencies = GOG only
- `preferredCurrency` will filter other currencies, causing quote to only consider that single coin. if insufficient balance, user will go thru a Top up experience.
**Before: Accepted (USDC default) | ETH | GOG**
**After: Accepted (USDC default) | ETH | (GOG preference)**
Only GOG will be used in quote, coins swappable to GOG will only show if found (not in this case)

feat: [Sale Widget] Filter other currencies if preferred currency applied

---

packages/checkout/sdk/src/widgets/definitions/configurations/sale.ts
packages/checkout/sdk/src/widgets/definitions/parameters/sale.ts
packages/checkout/widgets-lib/src/widgets/sale/SaleWidget.tsx
packages/checkout/widgets-lib/src/widgets/sale/SaleWidgetRoot.tsx
packages/checkout/widgets-lib/src/widgets/sale/context/SaleContextProvider.tsx
packages/checkout/widgets-lib/src/widgets/sale/hooks/useQuoteOrder.ts
packages/checkout/widgets-lib/src/widgets/sale/views/PaymentMethods.tsx
packages/checkout/widgets-sample-app/src/components/ui/sale/sale.tsx

Add `hideExcludedPaymentTypes` to sale widget config, this flag will allow to hide disabledPaymentTypes.
- A  `hideExcludedPaymentTypes: boolean` flag, defaults to `false`
- When true, disabled payment types will not be rendered
- When false, disabled payment types will render but will not be clickable if disabled.
Given both debit & credit are disabled
**hideExcludedPaymentTypes=false**
**hideExcludedPaymentTypes=true**

feat: [Sale Widget] Add config to hide disabled payment types

---

packages/orderbook/src/config/config.ts

Adding zone v2 in production config to enable ERC1155 & partial fills support.

TD-1359: chore: add zone v2 in production config.

---

packages/checkout/widgets-lib/src/widgets/sale/functions/fetchFundingBalances.ts
packages/checkout/widgets-lib/src/widgets/sale/hooks/useFundingBalances.ts

Fix issue where balances where quoted for all currencies. Instead, it should only quote funding routes for the base currency.
**Before: Duplicated routes**
**After: Only routes for base currency**

fix: [Sale Widget] Duplicated balances quotes

---

packages/checkout/widgets-lib/src/widgets/sale/functions/fetchFundingBalances.ts
packages/checkout/widgets-lib/src/widgets/sale/views/OrderSummary.tsx
packages/checkout/widgets-sample-app/src/components/ui/sale/sale.tsx

- Fix to only suggest swapping tokens for base currency
- Fix to reset select payment method when no coins found. fixes bug with clicking back button when on Top Up View.

fix: [Sale Widget] Remove SWAP options for funding tokens that are not base currency

---

packages/x-provider/src/signable-actions/deposit-actions/depositERC20.test.ts
packages/x-provider/src/signable-actions/deposit-actions/depositERC20.ts
packages/x-provider/src/signable-actions/deposit-actions/depositERC721.test.ts
packages/x-provider/src/signable-actions/deposit-actions/depositERC721.ts
packages/x-provider/src/signable-actions/deposit-actions/depositEth.test.ts
packages/x-provider/src/signable-actions/deposit-actions/depositEth.ts

Update deposit flows to drop the registration check. This is for StarkEx upgrade to v4.
From StarkEx V4, users are not required to be registered on-chain in order to deposit.

DX-2821/update_deposits

---

packages/checkout/sdk/src/index.ts
packages/checkout/sdk/src/provider/getUnderlyingProvider.test.ts
packages/checkout/sdk/src/provider/getUnderlyingProvider.ts
packages/checkout/widgets-lib/src/widgets/connect/components/WalletList.tsx
packages/checkout/widgets-sample-app/src/components/ui/sale/sale.tsx

When connecting with wallet connect the underlying provider chain id was always out of sync. Given the following issues:
1. Ethereum provider returned by wallet connect is not in sync with selected network in wallet. To fix it, one must ensure to request a network switch.
2. Chain id validation was incorrect for wallet connect, as  both`chainId` property and value returned from rpc call was returned as an hex value for desktop wallets, but as a number for wallet connect.
**Misc changes**:
- Add export for `validateProvider` in SDK. this function is handy to check and debug providers within widgets
- Add wallet connect config to `/sale` page in widgets sample app.
- Connect widget: After connecting with Wallet connect trigger network switch if chain id mismatch
- Fix `getUnderlyingChainId` …

fix: [Connect Widget] Wallet connect provider chain id validation

---

packages/minting-backend/sdk/src/index.ts
packages/webhook/sdk/src/index.ts
packages/webhook/sdk/src/init.ts

This change is to improve the devex for webhook interface
`init` function is renamed to `handle` in the `webhook` package. `handlers` arg has been made optional. `other` handler has been renamed to `all` and changed semantics to "all events will trigger the `all` handler" so that when new named handlers are added, there won't be breaking changes on the `all` handler.

breaking-change: improve webhook package

---

packages/checkout/widgets-lib/src/components/Handover/Handover.tsx
packages/checkout/widgets-lib/src/context/handover-context/HandoverContext.ts
packages/checkout/widgets-lib/src/context/handover-context/HandoverProvider.tsx
packages/checkout/widgets-lib/src/lib/hooks/useHandover.ts
packages/checkout/widgets-lib/src/widgets/swap/GeoblockLoader.cy.tsx
packages/checkout/widgets-lib/src/widgets/swap/GeoblockLoader.tsx
packages/checkout/widgets-lib/src/widgets/swap/SwapWidgetRoot.tsx

Implementation of loader for the Checkout widgets handover component.
[CM-676](https://immutable.atlassian.net/browse/CM-676)
New loader functions to `useHandover` hook, showLoader, hideLoader
Support for handover loader by the swap widget geoblock loader.
[CM-676]: https://immutable.atlassian.net/browse/CM-676?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: [CM-676] Checkout widgets handover loader component

---

packages/minting-backend/sdk/src/index.ts

Safe guard the usage of `process.on`. Checkout widgets ended up importing minting backend code. This is to be defensive in calling `process.on`. A further investigation is needed to understand why Widgets will end up importing this module.

fix: safe guard process on

---

packages/checkout/widgets-lib/src/widgets/swap/components/SwapForm.tsx
packages/checkout/widgets-sample-app/src/components/ui/swap/swap.tsx

Fixes crypto -> fiat conversion bug.
* crypto <> fiat conversions weren't being recalculated when `cryptoFiatState` is updated
https://github.com/immutable/ts-immutable-sdk/assets/13159042/99ff8497-9162-4714-97db-09ef6417ae18

fix:[ISGS-11] Token fiat conversions

---

packages/webhook/sdk/src/index.ts

Export webhook types so that the caller can use them
Adding types export from webhook package.

fix: export webhook types

---

packages/webhook/sdk/package.json
packages/webhook/sdk/src/index.ts

The types for the webhook package were added to the built index.d.ts file for the SDK, rather than the webhook.d.ts file. This adds the types back to the webhook.d.ts

fix: [DX-2910] Webhook Package exports types in index.d.ts rather than webhook.d.ts

---

packages/passport/sdk-sample-app/src/components/Message.tsx
packages/passport/sdk-sample-app/src/context/StatusProvider.tsx
packages/passport/sdk/src/confirmation/confirmation.test.ts
packages/passport/sdk/src/confirmation/confirmation.ts

This PR fixes an inconsistency with the errors that are thrown when the user rejects a transaction or message. Previously, rejecting a transaction with the "Cancel" button in the transaction confirmation app would throw a "User rejected transaction" error, but closing the window using the popup overlay or the OS' close button would result in a "Transaction rejected by user" error.
This PR removes the "User rejected transaction" error in favour of the "Transaction rejected by user" error.
https://github.com/immutable/ts-immutable-sdk/assets/9940216/9168807e-443e-4daa-8321-69c7d6ee5d86
- Passport: Fixed issue with inconsistent errors when the user rejects a transaction or message confirmation.
- Added a clear button to the messages output of the Passport sample application

fix: ID-1903 Fixed inconsistent errors

---

.github/workflows/publish.yaml

Increase alpha release frequency by automatically release alpha version to npm ONLY on every main push so that user can get the latest non-alpha packages on all alpha versions.
Increase alpha release frequency by automatically release alpha version on every main push.

chore: release alpha on main push

---

sdk/module-release.json

Move minting backend and webhook package out of alpha.
Webhook package and minting backend is not in production builds other than the browser bundle.

:feat move webhook minting backend out of alpha

---

packages/checkout/sdk-sample-app/package.json
packages/checkout/widgets-lib/package.json
packages/checkout/widgets-lib/src/widgets/sale/views/SaleErrorView.tsx
packages/checkout/widgets-sample-app/package.json
packages/passport/sdk-sample-app/package.json
packages/x-provider/src/sample-app/package.json
sdk/package.json
yarn.lock

Updates biome packages and resolves breaking changes
Removed one use of the now deprecated design token: `base.color.status.destructive`
https://immutable.atlassian.net/browse/DS-879

chore: migrate biome and resolve breaking change

---

packages/checkout/sdk/src/provider/provider.ts

Checkout SDK createProvider with a custom Passport instance now creates a unique provider each request.
Checkout SDK createProvider with a custom Passport instance would only support unique creation the first time, then use the cached version on the injected providers array. A fix has been applied to now always create a unique provider.

fix: [NO-JIRA] Support for unique providers using Checkout create provider and passport SDK

---

packages/checkout/sdk/src/balances/balances.ts

Tokentrove reported this issue a couple of weeks ago, the issue happens when it's a newly created wallet but has ERC721 tokens (NO ERC20 and NO IMX), the blockscout api returns a payload like below, and the `coin_balance` field being `null` breaks when passed to the `BigNumber.from` function.
```
{
"block_number_balance_updated_at": null,
"coin_balance": null,
"creation_tx_hash": null,
"creator_address_hash": null,
"ens_domain_name": null,
"exchange_rate": null,
"has_beacon_chain_withdrawals": false,
"has_decompiled_code": false,
"has_logs": false,
"has_token_transfers": true,
"has_tokens": false,
"has_validated_blocks": false,
"hash": "0x9509A79c32AAdE7cbfC0175890a6d0F33c089084",
"implementation_address": null,
"implementation_name": null,
"implementations": [],
"is_contract": false, …
```

fix: CM-664 - Checks value is not null before parse to BigNumber

---

.github/CODEOWNERS

Correct team as codeowners of packages/orderbook

Add traders as codeowners to orderbook package

---

packages/checkout/widgets-lib/src/components/Transactions/TransactionList.tsx
packages/internal/bridge/sdk/src/lib/axelarUtils.ts
packages/internal/bridge/sdk/src/tokenBridge.ts
packages/internal/dex/sdk/src/lib/transactionUtils/swap.ts
packages/passport/sdk-sample-app/src/components/zkevm/EthSendTransactionExamples/NFTApproval.tsx
packages/passport/sdk-sample-app/src/components/zkevm/EthSendTransactionExamples/NFTTransfer.tsx
packages/passport/sdk-sample-app/src/components/zkevm/EthSendTransactionExamples/SpendingCapApproval.tsx
packages/passport/sdk-sample-app/src/components/zkevm/EthSendTransactionExamples/TransferERC20.tsx
packages/passport/sdk-sample-app/src/components/zkevm/EthSendTransactionExamples/TransferImx.tsx
packages/x-client/src/utils/crypto/crypto.test.ts
packages/x-client/src/utils/crypto/crypto.ts

Change import for ethers.utils as advised by https://github.com/ethers-io/ethers.js/discussions/3179
Some users are reporting the following error when building:
```
Error: Cannot find module '[..]\node_modules\ethers\lib\utils' imported from [..]\node_modules\@imtbl\sdk\dist\index.js
Did you mean to import "ethers/lib/utils.js"?
```

fix: Change ethers.utils imports

---

packages/checkout/widgets-lib/src/widgets/bridge/views/ApproveTransaction.tsx

- Once approval is confirmed move to in progress view and skip L1 transaction confirmation.
- If error is returned, still displays bridge failure view.

Bridge approval is confirmed move to in progress view

---

packages/internal/dex/sdk/package.json
sdk/rollup.config.js
yarn.lock

Make esm module not replicating each other as much as possible.
The size of this approach is ~31 MB vs 37.8MB on npm
Group esm package inputs into a rollup config so that roll up can reason about their relationship.

fix: no russian nesting doll

---

packages/checkout/sdk/src/sdk.ts

We are deprecating the headless checkout orderbook methods and encouraging users towards the orderbook methods directly to prevent significant duplicate effort. We have confirmed that our marketplace partners are not relying on these methods - if anyone is we expect the deprecation tags to make them raise any concerns if they exist.
- checkout.buy
- checkout.sell
- checkout.cancel

Chore: Add deprecation tags to checkout.buy, checkout.sell and checkout.cancel

---

packages/passport/sdk-sample-app/src/components/zkevm/EthSignTypedDataV4Examples/SeaportCreateERC1155ListingDefault.tsx
packages/passport/sdk-sample-app/src/components/zkevm/EthSignTypedDataV4Examples/SeaportCreateERC721ListingDefault.tsx
packages/passport/sdk-sample-app/src/components/zkevm/EthSignTypedDataV4Examples/SeaportCreateListing.tsx
packages/passport/sdk-sample-app/src/components/zkevm/EthSignTypedDataV4Examples/SeaportCreateListingExample.ts
packages/passport/sdk-sample-app/src/components/zkevm/EthSignTypedDataV4Examples/index.ts

Add examples for signing ERC1155 listings in Passport sample app.
* New hardcoded example to generate signable message for ERC1155 listings creation
* Updated the generic `CreateListing` example to support ERC1155 token type.

TD-1515: chore: add examples for signing ERC1155 listings in Passport sample app.

---

.github/workflows/build-lint-typecheck-test.yaml
.github/workflows/build-sdk.yaml
.github/workflows/detect-node-version-change.yaml
.github/workflows/functional-tests-imx.yml
.github/workflows/functional-tests-zkevm.yml
.github/workflows/playwright.yml
.github/workflows/publish-docs.yaml
.github/workflows/publish-major-version.yaml
.github/workflows/publish.yaml
.github/workflows/secret-scan.yaml
.github/workflows/smokes-tests.yaml

Refactor workflows to use the cached `node_modules` between workflows. This cache should be similar between workflow runs as it should only change when adding or removing dependencies from the root level `package.json`.
`build-lint-typecheck` and `build-sdk` workflows should update the cache if the `yarn.lock` changes.
- When dependencies haven't changed in `package.json` this appears to reduce run time of all affected workflows by around 2 minutes.

refactor: use cached node_modules across workflows

---

packages/game-bridge/src/index.ts

Updated the game bridge so that if `status` is `false`, an `error` object is always returned.

[DX-2954] feat: always return an error if 'success' is false

---

packages/checkout/widgets-lib/src/widgets/sale/context/SaleContextProvider.tsx
packages/checkout/widgets-lib/src/widgets/sale/views/OrderSummary.tsx

On unhappy paths, it should close handovers before proceeding to top up view.
Add back `useEffect` to listen to errors from sale context.

[Fix] add close handovers

---

packages/passport/sdk/src/Passport.int.test.ts
packages/passport/sdk/src/Passport.ts
packages/passport/sdk/src/types.ts
packages/passport/sdk/src/zkEvm/sendTransaction.test.ts
packages/passport/sdk/src/zkEvm/sendTransaction.ts
packages/passport/sdk/src/zkEvm/zkEvmProvider.test.ts
packages/passport/sdk/src/zkEvm/zkEvmProvider.ts

This PR:
- [Passport zkEVM provider automatically connects to dApp if a valid user session exists](https://immutable.atlassian.net/browse/ID-1770); and
- [Manages state around token expiration better by checking user session and if not exists, forcing a login.](https://immutable.atlassian.net/browse/ID-1769)
Main changes:
- We're _always_ emitting the accountsChanged event when the Logout button is pressed; decoupling it from the class attribute
- For every request, we are preemptively trying to get their zkEvm address from their User session. If the User doesn't exist, then they will be prompted to login for `eth_requestAccounts` requests and for all other requests, throw an error for the dApp to nudge them to `eth_requestAccounts` first. This handles cases where a Users session is …

[ID-1769] fix: Passport zkEVM Provider denotes ethAddress from user session

---

packages/checkout/widgets-lib/src/views/top-up/TopUpView.tsx

In the Checkout widgets, when a user has insufficient funds, we present a list of options to the user to choose how to fund their wallet.
Currently, we link to the Layerswap Bridge in Toolkit. This PR changes the link to go to the Squid Bridge in Toolkit.
https://immutable.atlassian.net/browse/CM-771

feat: Sale widget - advanced topup options link to Squid

---

packages/checkout/sdk/src/widgets/definitions/events/sale.ts
packages/checkout/widgets-lib/src/widgets/sale/components/OrderReview.tsx
packages/checkout/widgets-lib/src/widgets/sale/hooks/useSaleEvents.ts
packages/checkout/widgets-lib/src/widgets/sale/utils/analytics.ts
packages/checkout/widgets-lib/src/widgets/sale/views/OrderSummary.tsx

Add the settlementType of SUFFICIENT or SWAP into the Segment events for ProceedToPay in the Checkout Sales Widget
https://immutable.atlassian.net/browse/CM-775

feat: Add settlementType to Segment events

---

package.json
packages/passport/sdk/package.json
packages/passport/sdk/src/authManager.ts
packages/passport/sdk/src/storage/LocalForageAsyncStorage.ts
sdk/package.json
yarn.lock

The device code authentication works well on Android, iOS, and Mac, but the Unity SDK encounters issues on Windows. After logging in, the user's OIDC data stored in localStorage often disappears when reopening the game. This happens because Windows initially stores localStorage items in memory, unlike IndexedDB, which writes directly to disk. Upon looking at the Chromium source code for version 122.0.6261.130, local storage items only get committed after every [5 seconds](https://source.chromium.org/chromium/chromium/src/+/refs/tags/122.0.6261.130:components/services/storage/dom_storage/local_storage_impl.cc;drc=81b3c99740a33d3ed7cf86781031637417c3aa38;l=154). Additionally, this [line](https://source.chromium.org/chromium/chromium/src/+/main:components/services/storage/dom_storage/local_st …

[DX-3013] feat: passport indexed db storage for unity sdk

---

.github/workflows/publish.yaml
package.json

Put in a temp fix for browser bundling copying logic so that when running test and typecheck during publish, the copied bundle will not be deleted.
A proper fix is coming to include the bundling logic inside nx target.

fix: DX-3055 deal with browser bundle

---

package.json
packages/game-bridge/package.json
sdk/package.json

Make copyBrowserBundle part of sdk's nx build target. So all contains under sdk/dist folder will be part of nx cache.
Move all scripts under root build script to sdk's build script

fix: make copyBrowserBundle part of nx target

---

.github/scripts/update-docs-link.sh

Fix links to the SDK docs in the update links script.
New versions of the SDK should have the TS SDK reference docs published correctly.
- Publish SDK reference docs workflow

fix: Publish SDK reference docs workflow 

---

packages/passport/sdk-sample-app/package.json
yarn.lock

Passport sample app imports @imtbl/orderbook but it's not in the package.json

fix: add missing dep to passport sample app

---

.github/scripts/check-docs-deployed.sh
.github/scripts/check-docs-version.sh
.github/workflows/publish-docs.yaml

The workflow was incorrectly exiting with a failure status when the SDK reference docs had actually built and deployed correctly.
This fixes the script to check the correct deployed docs URL, and prevents the workflow from returning a failed status when attempting to build and deploy docs for `alpha` versions. 
No impact for customers.  
- SDK reference docs workflow incorrectly reporting failed status

fix: SDK reference docs workflow

---

.github/workflows/publish-docs.yaml

Need more logging to figure out why it's publishing on alpha builds

fix: SDK reference docs workflow 

---

.github/workflows/publish-docs.yaml

Only run the build and publish docs job for non-alpha builds.

fix: check alpha version on publish job

---

.github/workflows/publish-docs.yaml

Set the correct SDK version in the SDK reference docs. Recent changes caused it to have version `0.0.0`.

fix: set correct SDK version in SDK reference docs

---

sdk/package.json
yarn.lock

Fix for the nextjs build warning:
../../../node_modules/pino/lib/tools.js
Module not found: Can't resolve 'pino-pretty' in 'node_modules/pino/lib'
Import trace for requested module:
../../../node_modules/pino/lib/tools.js
../../../node_modules/pino/pino.js
../../../node_modules/@wagmi/connectors/node_modules/@walletconnect/logger/dist/index.es.js
../../../node_modules/@wagmi/connectors/node_modules/@walletconnect/universal-provider/dist/index.es.js
../../../node_modules/@wagmi/connectors/node_modules/@walletconnect/ethereum-provider/dist/index.es.js
../../../node_modules/@wagmi/connectors/dist/esm/walletConnect.js
../../../node_modules/@wagmi/connectors/dist/esm/exports/index.js
../../../node_modules/wagmi/dist/esm/exports/connectors.js

fix: [DX-3083] Fix pino-pretty build warning

---

.github/workflows/build-game-bridge.yaml
packages/game-bridge/scripts/updateSdkVersion.sh

Check the version string is set in the game bridge build artefacts.
Should prevent SDKs being released with the incorrect version string. This can cause issues for Passport if the string is not set correctly.
- Workflow steps to check the version string in game bridge is set correctly

feat: game bridge build check version string

---

.eslintrc
build-dependents.js
dev.sh
examples/passport/identity-with-nextjs/.eslintrc.json
examples/passport/next-connect-kit/.eslintrc.json
examples/passport/next-rainbow-kit/.eslintrc.json
examples/passport/next-wagmi/.eslintrc.json
examples/passport/next-web3-modal/.eslintrc.json
examples/passport/wallets-connect-with-nextjs/.eslintrc.json
examples/passport/wallets-signing-with-nextjs/.eslintrc.json
examples/passport/wallets-transactions-with-nextjs/.eslintrc.json

The swc d command nx watch mode is using for our yarn dev command doesn’t generate the declaration files. Revert back to using the rollup build command for the watch mode.

fix: [DX-3092] Use rollup build instead of swc d for watch mode

---

tests/func-tests/zkevm/features/order.feature
tests/func-tests/zkevm/step-definitions/order.steps.ts
tests/func-tests/zkevm/step-definitions/shared.ts

Add additional step in E2E tests to return any remaining funds from funded accounts back to banker.

chore: TD-1596: optimize use of banker funds in E2E tests.

---

packages/game-bridge/src/index.ts

When checking whether the get transaction receipt failed or not, it should only check that the response is undefined, not null.

[DX-3122] fix: get transaction receipt success check

---

build-dependents.js
dev.sh

Fixes the delay in the initial rebuild caused by the nx cloud connection. This disables that to save us ~5-8 seconds in dev rebuild loop times, especially since the impact will be minimal with dev mode facing constant changes

fix: [DX-3131] Fix slow dev rebuild for initial changed package

---

packages/checkout/widgets-lib/src/components/WalletDrawer/WalletDrawer.tsx
packages/checkout/widgets-lib/src/components/WalletDrawer/WalletItem.tsx
packages/checkout/widgets-lib/src/widgets/connect/components/WalletItem.tsx
packages/checkout/widgets-lib/src/widgets/connect/components/WalletList.tsx

Prevent passing non serialisable objects as props to components that are wrapped with framer motion.
As this objects wont be serialised when the widgets are rendered within a cross domain iframe

[NO-CHANGELOG][Checkout Widgets] fix: Prevent passing provider as prop to framer motion children

---

packages/checkout/widgets-lib/src/widgets/sale/components/FundingRouteExecute/FundingRouteExecute.tsx
packages/checkout/widgets-lib/src/widgets/swap/SwapWidget.tsx
packages/checkout/widgets-lib/src/widgets/swap/components/SwapForm.tsx

Modify `SaleWidget` to use `autoProceed` to `true` on the `SwapWidget`

feat: Add autoProceed to SaleWidget

---

packages/checkout/widgets-lib/src/context/view-context/SwapViewContextTypes.ts
packages/checkout/widgets-lib/src/widgets/sale/hooks/useSaleEvents.ts
packages/checkout/widgets-lib/src/widgets/sale/views/OrderSummary.tsx
packages/checkout/widgets-lib/src/widgets/swap/components/SwapForm.tsx
packages/checkout/widgets-lib/src/widgets/swap/views/ApproveERC20Onboarding.tsx

- Adding a new analytic event when the user has insufficient funds in the Sale Widget.
- Adding autoProceed property to analytics events in the Swap Widget

feat: Add analytic event to insufficient funds scenario

---

packages/checkout/widgets-lib/src/locales/en.json
packages/checkout/widgets-lib/src/locales/ja.json
packages/checkout/widgets-lib/src/locales/ko.json
packages/checkout/widgets-lib/src/locales/zh.json
packages/checkout/widgets-lib/src/widgets/sale/components/OrderReview.tsx
packages/checkout/widgets-lib/src/widgets/sale/components/SelectCoinDropdown.tsx

Primary Sales can work with free items, but the UI doesn't reflect it 100% correctly. This change will make that more obvious to avoid any confusion.

feat: Adjust confirmation screen on free mints

---

packages/checkout/widgets-lib/src/components/WithdrawalQueueDrawer/WithdrawalQueueDrawer.tsx
packages/checkout/widgets-lib/src/locales/en.json
packages/checkout/widgets-lib/src/locales/ja.json
packages/checkout/widgets-lib/src/locales/ko.json
packages/checkout/widgets-lib/src/locales/zh.json
packages/checkout/widgets-lib/src/widgets/bridge/components/BridgeReviewSummary.tsx

Our bridge has a [withdrawal delay mechanism](https://github.com/immutable/zkevm-bridge-contracts/blob/main/docs/high-level-architecture.md#withdrawal-delay-mechanism) that can affect large transfers or delay any transfer when the queue is activated. Users performing a bridge operation have no information about it before the transfer, sometimes leading to funds being locked without the user knowing it'll happen.
Given we can predict when transactions will cause a queue and know when the queue is activated, we're adding a warning before transactions are sent, so users can make an informed decision.
Sample flows:
https://github.com/user-attachments/assets/64b27704-be41-4ad3-bc52-09dc42afa200
https://github.com/user-attachments/assets/e78c2bb8-ff09-4edf-8dfe-9243dc5b7fbc

feat: Inform users about bridge withdrawal queue

---

packages/game-bridge/src/index.ts

Add the `logoutMode` option to be passed into the Game Bridge init function from game SDKs.
The new option is optional and only affects the Unreal and Unity SDKs.
- Optional `logoutMode` option in game bridge `init` function

feat: Add logout mode option to Game Bridge

---

packages/checkout/widgets-lib/src/components/TokenImage/TokenImage.tsx

TokenImage its use by MenuItem a Biome design system component that will forward a `responsiveSizes` props that should not be forwarded to `img` tag.
ie:
```tsx
<MenuItem.FramedImage
circularFrame
use={(
<TokenImage src={icon} name={name} defaultImage={defaultTokenImage} />
)}
/>
```

[NO CHANGELOG][Wallet Widget] remove unexpected props from img component

---

packages/checkout/widgets-lib/src/locales/en.json
packages/checkout/widgets-lib/src/locales/ja.json
packages/checkout/widgets-lib/src/locales/ko.json
packages/checkout/widgets-lib/src/locales/zh.json
packages/checkout/widgets-lib/src/views/error/ErrorView.tsx

https://immutable.atlassian.net/browse/CM-866
Fix broken support links across the Checkout Widgets. The Support Hub no longer supports other languages so we have changed those links to the English ones.

fix: Update broken support link in Checkout Widgets

---

packages/checkout/widgets-lib/src/locales/ja.json
packages/checkout/widgets-lib/src/locales/ko.json
packages/checkout/widgets-lib/src/locales/zh.json
packages/checkout/widgets-lib/src/views/error/ErrorView.tsx

Change Support link in Checkout Widgets to one that auto-detects the user's language based on their browser settings.

fix: Use language agnostic Support link

---

packages/passport/sdk/src/Passport.int.test.ts
packages/passport/sdk/src/magicAdapter.test.ts
packages/passport/sdk/src/magicAdapter.ts

https://immutable.atlassian.net/browse/ID-2334
This PR removes the `preload` call from the Magic SDK. This was actioned previously, but the change was rolled back.
- Passport: Removed `preload` call from Magic SDK, as later versions of the Magic SDK trigger this call as part of the Magic constructor.

feat: ID-2334 Removed preload call from Magic SDK

---

.github/scripts/update-docs-link.sh

The docs site needs to link to the correct version number of the SDK Reference from the sidebar. This is not accessible using the existing `UnifiedSDKLink` component since the sidebar is part of the docusaurus configuration scripts, not the react app.
This change updates the SDK_VERSION parameter in the [sidebars/sidebar-docs.js](https://github.com/immutable/docs/blob/main/sidebars/sidebars-docs.js) file using the same technique as was used to update the SDK_VERSION in the UnifiedSDKLink component.
We will need to monitor this and make sure it works when the next release is published.

chore: update the SDK_VERSION number in the sidebar file when a release is cut

---

packages/passport/sdk/src/magicAdapter.ts
packages/passport/sdk/src/utils/lazyLoad.ts
packages/passport/sdk/src/utils/metrics.test.ts
packages/passport/sdk/src/utils/metrics.ts

This PR wraps the `magicAdapter.login` method with a call to `withMetricsAsync` so that we have better visibility into interactions with Magic.
- Passport: Added additional Magic tracking
- Passport: Updated `lazyLoad` to handle a hypothetical situation in which we do not add a listener before the `readystatechange` event is fired

feat: ID-2416 tracking changes

---

packages/checkout/widgets-lib/src/widgets/checkout/hooks/useEip6963Relayer.ts

* Includes static provider props from eip6963 events in post message payload

feat:[NO CHANGELOG][Checkout Widget]Sends provider static props with eip6963 calls.

---

packages/internal/generated-clients/templates/blockchain-data/apiInner.mustache

The manual step introduced to be compatible with swc can be automated by updating our internal custom generators

fix: Remove manual step in type generator by updating generator template

---

packages/blockchain-data/sdk/src/blockchain-data.ts

The blockchain data package exports custom generated types that we expect users to use, however the methods did not refer to the same types and instead referred to the old types causing a compilation error on usage. This PR fixes the methods to reflect the expected types
Request and response types for methods on blockchain data package

refactor: Assert custom types on blockchain data package

---

packages/passport/sdk-sample-app/src/components/zkevm/EthSendTransactionExamples/DefaultTransaction.tsx

In the Passport Sample App, the `eth_sendTransaction` Default Transaction example always hex encodes the string entered into the `Data` field. If you want to enter a already hex encoded data string, like one you would get from the orderbook fulfill order endpoint, for example, the data string gets double encoded and submitting the transaction will fail with the error: `Request: Error: Transaction failed to submit with status FAILED. Error message: transaction failed to build: execution reverted`.
This small fix checks if the string has a `0x` prefix and only encodes the data string if it doesn't have a `0x` prefix.
- Re-encoding hex strings in the Passport sample app send transaction example.

fix: Passport sample app default transaction example hex encoding data string

---

.github/workflows/dependency-review.yaml

Adds Dependency Review GitHub feature https://docs.github.com/en/code-security/supply-chain-security/understanding-your-software-supply-chain/about-dependency-review#about-dependency-review for new Critical vulnerabilities only.
No new PRs will be blocked yet. This will be running in the monitoring mode until we're happy that it works flawlessly.

ITSEC-2205 Add Dependency Review workflow

---

packages/checkout/widgets-lib/src/widgets/add-funds/AddFundsWidget.tsx
packages/checkout/widgets-lib/src/widgets/add-funds/context/AddFundsContext.ts

[NO CHANGELOG][Add Funds Widget] Initialise context values to null

---

packages/checkout/widgets-lib/src/widgets/add-funds/hooks/useRoutes.ts

Add and expose `resetRoutes` to be called from the main component to reset on every token/currency changes
Add `latestRequestIdRef` to track and manage multiple concurrent routes requests, ensuring that only the most recent request result is processed and applied to the state `routes`

[NO CHANGELOG] [Add Funds Widget]  Feat/add funds only set the latest route request

---

packages/checkout/sdk/src/types/config.ts
packages/checkout/sdk/src/widgets/definitions/events/addFunds.ts
packages/checkout/sdk/src/widgets/definitions/events/orchestration.ts
packages/checkout/sdk/src/widgets/definitions/types.ts
packages/checkout/widgets-lib/src/lib/orchestrationEvents.ts
packages/checkout/widgets-lib/src/widgets/add-funds/AddFundsWidget.tsx
packages/checkout/widgets-lib/src/widgets/add-funds/AddFundsWidgetEvents.ts

- Enables widget config
- Add success, fail events
- Add request add funds orchestration event

[NO CHANGELOG] [Checkout Widget] Add events required for integration

---

packages/game-bridge/src/index.ts

The game bridge call function switch statement default case does not return a callback to the game. A game calling the game bridge with an incorrect function name would never receive a response from the game bridge.
Add a callback to the game with an error message to indicate the function they are calling is invalid.
This is probably more of a fix for the Game SDK developers, but could help debug external developer issues too.
- Callback to game from game bridge when the `callFunction` default case is hit.

fix: add callback to game with invalid function error from the default case

---

packages/checkout/sdk/src/widgets/definitions/parameters/addFunds.ts
packages/checkout/widgets-lib/src/context/providers-context/ProvidersContext.tsx
packages/checkout/widgets-lib/src/lib/provider/utils.ts
packages/checkout/widgets-lib/src/widgets/add-funds/AddFundsRoot.tsx
packages/checkout/widgets-lib/src/widgets/add-funds/AddFundsWidget.tsx
packages/checkout/widgets-lib/src/widgets/add-funds/components/SelectedWallet.tsx
packages/checkout/widgets-lib/src/widgets/add-funds/views/AddFunds.tsx
packages/checkout/widgets-sample-app/src/components/ui/add-funds/addFunds.tsx

Adds the ability to set the toProvider and lock the deliver to wallet, by finding the given provider in injected providers.
If the given provider is not found, the deliver to input wont be lock and user will be able to select the deliver to wallet as usual

[NO CHANGELOG] [Add Funds Widget] CM-997 | Preset and lock deliver to wallet

---

examples/passport/telegram-mini-app/app/page.tsx
packages/game-bridge/src/index.ts
packages/passport/sdk/src/config/config.ts
packages/passport/sdk/src/types.ts
packages/passport/sdk/src/zkEvm/zkEvmProvider.ts

- Sets jsonRpcReferrer as optional param on Passport so when external partners use `crossSdkBridgeEnabled` the referrer isnt also set in `zkEvmProvider.ts`

refactor: ID-2589 Add json rpc referrer as optional param and set on game bridge

---

packages/checkout/widgets-lib/src/widgets/add-funds/views/AddFunds.tsx

Before IMX didn't have an icon, this PR fixes to fetch icon for native token:

[NO CHANGELOG] [Add Funds Widget] Fix to show imx token icon

---

.github/workflows/publish.yaml

Removing or preventing GitHub from attesting the code will cause a critical security incident - clarify in the comments.

Add a security warning comment to the attestations job

---

packages/checkout/widgets-lib/src/views/top-up/TopUpView.tsx
packages/checkout/widgets-lib/src/widgets/sale/SaleWidget.tsx
packages/checkout/widgets-lib/src/widgets/wallet/WalletWidget.tsx
packages/checkout/widgets-lib/src/widgets/wallet/context/WalletContext.test.ts
packages/checkout/widgets-lib/src/widgets/wallet/context/WalletContext.ts
packages/checkout/widgets-lib/src/widgets/wallet/views/WalletBalances.tsx

Remove logic to check whether `isAddTokensAvailable` based on `addTokens` config flag and geoblocking, redirect to Add Tokens widget from Wallet widget

[NO CHANGELOG] [Add Tokens Widget] Redirect to Add Tokens widget from Wallets widget

---

packages/checkout/widgets-lib/src/components/WalletDrawer/ConnectWalletDrawer.tsx
packages/checkout/widgets-lib/src/components/WalletDrawer/DeliverToWalletDrawer.tsx
packages/checkout/widgets-lib/src/widgets/add-tokens/components/RouteFees.tsx

When "from wallet" is already selected to be Passport, currently when we choose Passport for "to wallet", it disconnects the current Passport and asks the user to reconnect. 
This changes so that the "toWallet" reuses the same Passport as "from wallet".

[NO CHANGELOG] [Add Tokens Widget] Only disconnect Passport wallet for from wallet

---

packages/checkout/widgets-lib/src/widgets/add-tokens/functions/fetchChains.ts

Squid has advised to use `networkName` not `chainName`

[NO CHANGELOG] [Add Tokens Widget] Fix to use networkName instead of chainName

---

packages/passport/sdk/src/mocks/zkEvm/msw.ts
packages/passport/sdk/src/zkEvm/transactionHelpers.test.ts
packages/passport/sdk/src/zkEvm/transactionHelpers.ts

This PR fixes an issue with an error being thrown when `im_signEjectionTransaction` is called with an integer value of 0.
- Passport: Resolved an issue with `im_signEjectionTransaction` that would result in an error when an integer value of zero was provided as the nonce.
The changes to `msw.ts` resolve a number of errors that were being thrown when the tests in `Passport.int.test.ts` were run.

fix: ID-2791 Fix zero nonce issue for ejection transactions

---

packages/checkout/widgets-lib/src/components/WalletDrawer/ConnectWalletDrawer.tsx

Removing `changed your mind` drawer as this is not needed. This component was created 8 months ago when Passport has not yet implemented pop-up blocking retry overlay. Currently Passport shows an overlay when pop-up blocking happens.

[NO CHANGELOG] [Add Tokens Widget] Nuke changed your mind drawer

---

packages/internal/generated-clients/src/blockchain-data-openapi.json
packages/internal/generated-clients/src/blockchain-data/models/chain-with-details-all-of.ts
packages/internal/generated-clients/src/mr-openapi.json
packages/internal/generated-clients/src/multi-rollup/.openapi-generator/FILES
packages/internal/generated-clients/src/multi-rollup/domain/guardian-api.ts
packages/internal/generated-clients/src/multi-rollup/models/chain-with-details-all-of.ts
packages/internal/generated-clients/src/multi-rollup/models/evmmessage.ts
packages/internal/generated-clients/src/multi-rollup/models/fulfillable-order.ts
packages/internal/generated-clients/src/multi-rollup/models/fulfillment-data-request.ts
packages/internal/generated-clients/src/multi-rollup/models/index.ts
packages/internal/generated-clients/src/multi-rollup/models/seaport-erc1155-collection-item.ts
packages/internal/generated-clients/src/multi-rollup/models/seaport-erc721-collection-item.ts
packages/internal/generated-clients/src/multi-rollup/models/unfulfillable-order.ts
packages/internal/generated-clients/src/multi-rollup/models/validation-result.ts
packages/internal/generated-clients/src/multi-rollup/models/validation-simulation-failed-results.ts
packages/internal/generated-clients/src/multi-rollup/models/validation-status.ts
packages/x-client/src/utils/formatError.test.ts

Regenerate openapi spec for blockchain data package - update chains endpoint response to include `minter_address` and `operator_allowlist_address`
Non breaking additive change
Chains endpoint response:
- `minter_address`: The address of the minter used in the Minting API - https://docs.immutable.com/products/zkEVM/minting/minting-api#minting-api-prerequisites
- `operator_allowlist_address`: The address of the Operator Allowlist - https://docs.immutable.com/products/zkevm/minting/royalties/allowlist-spec/

refactor: Update chains endpoint response

---

packages/checkout/widgets-lib/src/widgets/add-tokens/AddTokensWidget.tsx
packages/checkout/widgets-lib/src/widgets/add-tokens/hooks/useRiskAssessment.ts
packages/checkout/widgets-lib/src/widgets/add-tokens/views/AddTokens.tsx

feat: Check if addresses are sanctioned when adding funds

---

packages/checkout/widgets-lib/src/widgets/add-tokens/functions/amountValidation.ts
packages/checkout/widgets-lib/src/widgets/add-tokens/views/AddTokens.tsx

Fix some edge cases:
- the user shouldn’t be able to enter a first `.` only if there is a number before it
- no `-` is allowed, currently the input doesn’t show that this is an error
- `.01111` should be invalid, currently the input doesn’t show that this is an error
- they should be able to remove all input, currently when all is removed it defaults to 0
- only pulsate if the amount is valid, otherwise let them fix it first before pulsating the next step again

[NO CHANGELOG] [Add tokens Widget] Fix/add tokens invalid input

---

packages/checkout/widgets-lib/src/components/WalletDrawer/ConnectWalletDrawer.tsx
packages/checkout/widgets-lib/src/components/WalletDrawer/DeliverToWalletDrawer.tsx
packages/checkout/widgets-lib/src/components/WalletDrawer/PayWithWalletDrawer.tsx
packages/checkout/widgets-lib/src/lib/connectEIP6963Provider.ts
packages/checkout/widgets-lib/src/widgets/connect/components/WalletList.tsx

Risk assessments are done before a transaction occurs, so this check isn't needed anymore.

chore: Remove risk assessment check from Connect widget

---

packages/passport/sdk/src/Passport.ts
packages/passport/sdk/src/authManager.ts
packages/passport/sdk/src/zkEvm/zkEvmProvider.ts

- Handle unknown or invalid refresh token error when initialising a ZkEvmProvider

fix: ID-2650 Handle unknown or invalid refresh token error

---

packages/checkout/widgets-lib/src/widgets/add-tokens/hooks/useExecute.ts

`tx.wait()` is taking a lot longer to return, this is likely due to the RPC of our chain not having websockets enabled. This simple function polls every 1 second for the tx receipt and also checks the status (which wasn't being checked before).
https://github.com/user-attachments/assets/a3bd99b3-4cfa-4ab4-a13f-b701c0c166ca

ID-2747 - Adding waitForReceipt function to track when tx confirms

---

packages/checkout/widgets-lib/src/components/WalletDrawer/ConnectWalletDrawer.tsx
packages/checkout/widgets-lib/src/components/WalletDrawer/DeliverToWalletDrawer.tsx

The user is being identified through Segment twice, one for each connection. In case the destination wallet is different than the source, tracking goes off as the anonymous ID is re-generated.
Identify should only be called once, from the source wallet.

fix: Skip identifyUser call when connecting destination wallet

---

packages/checkout/widgets-lib/src/widgets/add-tokens/context/AddTokensContext.tsx
packages/checkout/widgets-lib/src/widgets/add-tokens/views/AddTokens.tsx

When the result for the geoblock is false, `isSwapAvailable` changes from `false` to `true`, triggering this event twice.

Wait for geoblock results before sending Segment event

---

packages/checkout/widgets-lib/package.json
packages/checkout/widgets-lib/src/components/WalletDrawer/ConnectWalletDrawer.tsx
packages/checkout/widgets-lib/src/lib/analytics/identifyUser.test.ts
packages/checkout/widgets-lib/src/lib/analytics/identifyUser.ts
sdk/package.json
yarn.lock

When `identify` is called more than once, the `anonynousId` property gets refreshed. This change will ensure that the ID doesn't change anymore.

feat: Ensure anonymousId is kept across multiple identify calls

---

packages/checkout/widgets-lib/src/lib/constants.ts
packages/checkout/widgets-lib/src/lib/utils.test.ts
packages/checkout/widgets-lib/src/lib/validations/amountInputValidations.test.ts
packages/checkout/widgets-lib/src/lib/validations/widgetValidators.test.ts
packages/checkout/widgets-lib/src/widgets/add-tokens/functions/getFormattedNumber.ts
packages/checkout/widgets-lib/src/widgets/add-tokens/views/AddTokens.tsx
packages/checkout/widgets-lib/src/widgets/add-tokens/views/Review.tsx
packages/checkout/widgets-lib/src/widgets/sale/functions/fundingBalanceFees.test.ts
packages/checkout/widgets-lib/src/widgets/swap/functions/swapConversionRate.test.ts

- Fix 5 decimal points across the board
- Fix bug when input is too small and parseFloat returns a scientific notation

[NO CHANGELOG] [Commerce Widget] Fix/add tokens amounts & update decimals 

---

packages/checkout/widgets-lib/src/widgets/add-tokens/views/Review.tsx

Add to send immutableZkEVMTxHash for immutable zkEVM chain
for other chains txHash

[NO CHANGELOG] [Add Tokens Widget] fix: Add immutableZkEVMTxHash success track event 

---

packages/checkout/widgets-lib/src/widgets/add-tokens/functions/amountValidation.ts

When inputting a decimal, some users will start with a dot instead of a zero. That case was invalid, so we're prepending a zero now.

chore: Prepend zero to decimal amounts when dot is the first input

---

packages/checkout/widgets-lib/src/components/WalletDrawer/DeliverToWalletDrawer.tsx
packages/checkout/widgets-lib/src/components/WalletDrawer/PayWithWalletDrawer.tsx
packages/checkout/widgets-lib/src/widgets/add-tokens/views/AddTokens.tsx
packages/checkout/widgets-sample-app/src/components/ui/add-tokens/addTokens.tsx

Given the wallet being funded is most likely to be our target user, we're shifting the `identify` call to only happen once the "to" wallet is filled. The `identify` call should also happen when a `toProvider` is passed on the initial widget config.

fix: Move identify call to destination wallet on Add Tokens flow

---

.github/workflows/publish.yaml

Fix typo, as the widgets access the value `timestamp` in `last_updated.json` file not `last_updated`.

Fix typo in last_updated.json

---

packages/passport/sdk/src/authManager.test.ts
packages/passport/sdk/src/authManager.ts

This PR improves the refresh token error logging in Passport.
- Passport: Improved refresh token error logging.

chore: ID-3113 Improve refresh token error logging

---

packages/passport/sdk/src/zkEvm/sessionActivity/sessionActivity.ts

Change session activity to use local date so that D1 makes more sense in user context.

fix: change session activity to use local date

---

.github/workflows/publish.yaml
packages/checkout/sdk/src/sdk.ts
packages/checkout/sdk/src/widgets/version.test.ts
packages/checkout/sdk/src/widgets/version.ts

This PR enhances the widgets autoupdating strategy by removing the dependency on the NPM registry endpoint `https://registry.npmjs.org/@imtbl/sdk/latest`. The new approach uses a dedicated `version.json` file created during the publishing workflow. 
Currently, we rely on the NPM registry endpoint `https://registry.npmjs.org/@imtbl/sdk/latest` to get the specific latest version. This solves our browser and CDN caching issues for the `@latest` version but requires anyone using the widgets to whitelist `registry.npmjs.org` in CSP. The browser and CDN caching issue will persist if the app's CSP policy is blocking the `registry.npmjs.org`. 
The workflow now creates the `version.json` file and uploads it to `dist`.  It waits for the NPM to propagate the latest version successfully, then purges …

refactor: use version.json for autoupdating & remove dependency on npm registry for checking for latest version

---

.github/CODEOWNERS

Adds Security as approvers in CODEOWNERS to `.github`, along with the SDK team

chore: add Security to .github as approvers

---

.github/workflows/publish.yaml

- Move the `Generate version.json` step to be after the `Build` step as `./sdk/dist/` directory is created during the `Build` step
This PR is related to https://github.com/immutable/ts-immutable-sdk/pull/2471

fix: Move version.json generation to be after build step

---

.github/workflows/publish-docs.yaml

Refersh dependency cache for publish docs action in hope to fix https://github.com/immutable/ts-immutable-sdk/actions/runs/12642926453/job/35228101920#step:12:289

chore: bust cache for publish docs action

---

.github/workflows/publish-docs.yaml

Reverts immutable/ts-immutable-sdk#2487
This is to re-enable cache for documentation publish action

Revert "chore: bust cache for publish docs action"

---

.github/workflows/publish-docs.yaml

Add concurrency group for publish docs to avoid race conditions like [this](https://github.com/immutable/ts-immutable-sdk/actions/runs/12664314204/job/35292257860)

fix: add-concurrency-group-for-publish-docs

---

packages/checkout/widgets-lib/src/lib/squid/functions/verifyAndSwitchChain.ts
packages/checkout/widgets-lib/src/lib/squid/hooks/useExecute.ts
packages/checkout/widgets-lib/src/widgets/add-tokens/hooks/useErrorHandler.ts
packages/checkout/widgets-lib/src/widgets/add-tokens/views/Review.tsx

Refactor `useExecute` hook to be used in both Add Tokens and Purchase widgets.
- Move Add Tokens error handling out of `useExecute` by providing `onTransactionError` callback
- Move Add Tokens event tracking out of `useExecute`

refactor: generalise useExecute hook

---

packages/checkout/widgets-lib/src/widgets/add-tokens/AddTokensWidget.tsx
packages/checkout/widgets-lib/src/widgets/add-tokens/components/TokenDrawerMenu.tsx
packages/checkout/widgets-lib/src/widgets/add-tokens/hooks/useError.tsx
packages/checkout/widgets-lib/src/widgets/add-tokens/hooks/useErrorHandler.ts
packages/checkout/widgets-lib/src/widgets/add-tokens/hooks/useHandoverConfig.tsx
packages/checkout/widgets-lib/src/widgets/add-tokens/views/AddTokens.tsx
packages/checkout/widgets-lib/src/widgets/add-tokens/views/Review.tsx

- Refactor to move the logic to show handover screens from the `Review` component into `useHandoverConfig`
- Move `useError` from common back to Add Tokens as it contains logic specific to Add Tokens

refactor: move handover logic into useHandoverConfig

---

packages/checkout/widgets-lib/src/widgets/purchase/PurchaseWidget.tsx
packages/checkout/widgets-lib/src/widgets/purchase/context/PurchaseContext.tsx

This data will be used by the Purchase view.

feat: Add Squid SDK, tokens and chains to Purchase context

---

packages/checkout/widgets-lib/src/lib/hooks/useQuoteOrder.ts
packages/checkout/widgets-lib/src/lib/primary-sales.ts
packages/checkout/widgets-lib/src/widgets/purchase/PurchaseWidget.tsx
packages/checkout/widgets-lib/src/widgets/purchase/components/PurchaseItemHero.tsx
packages/checkout/widgets-lib/src/widgets/purchase/context/PurchaseContext.tsx
packages/checkout/widgets-lib/src/widgets/purchase/views/Purchase.tsx

We're now fetching the final purchase details from the backend, converting any amounts to fiat, and displaying them in the Hero component.

feat: Fetch purchase price details from the Primary Sales API

---

packages/orderbook/.eslintrc.cjs
packages/orderbook/src/api-client/api-client.test.ts
packages/orderbook/src/seaport/components.ts
packages/orderbook/src/seaport/lib/bulk-orders.ts
packages/orderbook/src/seaport/map-to-immutable-order.ts
packages/orderbook/src/seaport/map-to-seaport-order.ts
packages/orderbook/src/seaport/seaport.test.ts
packages/orderbook/src/seaport/seaport.ts
packages/orderbook/src/seaport/transaction.ts
packages/orderbook/src/seaport/types.ts
packages/orderbook/src/types.ts
packages/orderbook/src/utils.ts

This PR resolves an issue with Seaport imports when `@imtbl/orderbook` has been imported in an ESM environment, e.g: [here](https://github.com/immutable/ts-immutable-sdk/issues/2472). Note that this issue does not appear to occur in _all_ ESM environments. Rather than importing types from a relative path within seaport-js, we're now pulling out & re-exporting the types that are easily accessible, and duplicating the types that are less-easily accessible and less likely to cause issues with Typescript.
Related PR [here](https://github.com/immutable/ts-immutable-sdk/pull/384).
- Orderbook: Updated seaport-js imports to resolve an issue in ESM environments

fix: ID-3186 Resolve @imtbl/orderbook Seaport module issue 

---

packages/checkout/sdk/src/config/tokensFetcher.ts

- IMX currently not showing up in the bridge widget: Small fix to add it as native and therefor supported in the bridge

fix: marking IMX as token valid for native bridge

---

packages/checkout/widgets-lib/src/widgets/swap/GeoblockLoader.tsx
packages/checkout/widgets-lib/src/widgets/swap/SwapWidget.tsx
packages/checkout/widgets-lib/src/widgets/swap/SwapWidgetRoot.tsx

The geo-block check was being skipped by the Commerce widget. By bringing the wrapper into `SwapWidget` rather than `SwapWidgetRoot`, the check is now included when using the Commerce widget.

chore: Implement geoblock for swaps on Commerce widget

---

packages/checkout/widgets-lib/src/widgets/swap/components/SwapForm.tsx

Track different events on swap form interactions. There were no events on the to and from fields and input changes - so it was hard to know the drop off as there only final event on the swap button. 
Also added an event for the "unable to swap" modal popups for any kind of swap error

chore: Track events on different swap form interactions

---

packages/checkout/widgets-lib/src/widgets/swap/components/SwapForm.tsx
packages/internal/dex/sdk/src/constants/tokens/immutable-mainnet.ts

Add USDC to "common routing tokens" allowing it to be considered as a hop for swaps.
Further justification for this is that we recommend games set up a USDC LP for their token: https://docs.immutable.com/guides/zkevm/game-currencies/liquidity-pools/#set-up-your-liquidity-pool-with-quickswap
Also added USDT as some tokens only have USDT pools e.g. https://quickswap.exchange/#/analytics/v3/token/0x699797abcdc2e20165fE4bAC5efbAa652490E6E2
Ran some tests locally and adding two more common routing tokens only increased the quoting time by about 50ms.

feat: GFI-82: Allow USDC Swap Hops

---

packages/internal/dex/sdk/src/constants/router.ts
packages/internal/dex/sdk/src/lib/router.ts

Increasing the max number of pools used in a swap to 3. This will allow swaps between IMX and VDT (for example) where the pools necessary are
IMX / USDC
USDC / USDT
USDT / VDT

GFI-87: Increase max swap hops to 3

---

packages/checkout/widgets-lib/src/components/FormComponents/SelectForm/SelectForm.tsx
packages/checkout/widgets-lib/src/components/FormComponents/SelectInput/SelectInput.tsx
packages/checkout/widgets-lib/src/widgets/bridge/components/BridgeForm.tsx
packages/checkout/widgets-lib/src/widgets/swap/components/SwapForm.tsx

We track when the user chooses a token - event for that is checkoutSwapSwapCoins_SelectFromSelect and checkoutSwapSwapCoins_SelectToSelect, but we don't track the interaction before that which is opening the select menu. This PR tracks that.

build(checkout): GFI-96: Track select token clicks

---

packages/checkout/widgets-lib/src/widgets/swap/views/ApproveERC20Onboarding.tsx

Currently we track these two screens with the same event, making it difficult to represent the user flow accurately in a funnel.
Use different events for each.

build(checkout): Track spending approval separate from swap approval

---

packages/passport/sdk/src/magic/magicAdapter.test.ts
packages/passport/sdk/src/magic/magicAdapter.ts

- Check isLoggedIn before calling loginWithOIDC to prevent unnecessary calls to the Magic OIDC endpoint

chore(passport): Check isLoggedIn before calling loginWithOIDC

---

packages/passport/sdk-sample-app/src/pages/login/redirect-callback.ts

Add rule to validate if application is using base_path configuration before forwarding using location.href in login redirect-callback.

fix(passport): Fix location.href in redirect-callback to envs that use the base_path configuration

---

packages/passport/sdk-sample-app/src/pages/login/redirect-callback.ts

Fix location.href to redirect callback to remove unappropriated `/`.

fix(passport): Fix location.href to redirect callback

---

packages/passport/sdk/src/zkEvm/walletHelpers.test.ts
packages/passport/sdk/src/zkEvm/walletHelpers.ts

Ethers V6 has changed the error type which is thrown when the Passport smart contract is not yet deployed and a readNonce call is made.
* Fixed an issue preventing new users from having their Passport smart contract wallet deployed

fix(passport): Use correct ethers v6 error type

---

packages/passport/sdk/src/zkEvm/walletHelpers.test.ts
packages/passport/sdk/src/zkEvm/walletHelpers.ts

Handles a BAD_DATA response inside a UNKNOWN_ERROR error.
Related PR: https://github.com/immutable/ts-immutable-sdk/pull/2561

fix(passport): ID-3274: Handle nonce error

---

packages/passport/sdk/src/Passport.ts
packages/passport/sdk/src/magic/magicProviderProxyFactory.test.ts
packages/passport/sdk/src/magic/magicProviderProxyFactory.ts

fixes an issue where calling `eth_requestAccounts` triggers the Magic login UI overlay

fix(passport): prevent eth_requestAccounts from being called on Magic RPC

---

.github/scripts/check-docs-deployed.sh
.github/scripts/check-docs-version.sh
.github/scripts/push-docs.sh
.github/scripts/update-docs-link.sh
.github/workflows/publish-docs.yaml

Changed the pipeline to replace existing SDK reference instead of pushing new releases. 
This will make the Docs Site's SDK-reference less clunky and will only contain the latest version of v2 and v1 instead of all versions.
NOTE: This is not done and some more changes needs to be done(remove hard codes, changing target branch to main, and commented out jobs)
JIRA: https://immutable.atlassian.net/browse/DVR-325

FIX: DVR-236 | Pipeline changes to replace sdk reference instead of pushing

---

packages/checkout/widgets-lib/src/widgets/bridge/components/WalletAndNetworkSelector.tsx

To replicate:
1. Go to https://checkout-playground.sandbox.immutable.com/ethereum-bridge/
2. Choose Metamask as the source wallet
3. Change your chain in Metamask to something else
4. Try to go ahead with the bridge
5. On the Switch to Sepolia step, nothing will happen and an error will be logged.
In Ethers v6, if the user changes networks, the BrowserProvider should be recreated. That's the ideal solution. However a workaround is to pass "any" for the network when creating the provider and this will also allow the network to be switched without error.

fix(checkout): Fix network switching bug in bridge

---

packages/passport/sdk/src/magic/magicAdapter.test.ts
packages/passport/sdk/src/magic/magicAdapter.ts

Reverts immutable/ts-immutable-sdk#2533
This revert exercise is the first step in the ongoing investigation to support the case where Passport allows multiple user accounts to be used across different Passport clients within the same browser instance.
This will result in increased number of calls to `loginWithOIDC` but will resolve the situation where users end up with an `Authorisation Error` when attempting to transact with a Passport wallet.
[NR chart](https://onenr.io/0BR6oLnE0jO) showing uptick in error rate in the last 30 days

chore(passport): ID-3354: Revert "chore(passport): Check isLoggedIn before calling loginWithOIDC"

---

packages/x-client/src/utils/stark/starkCurve.ts
packages/x-provider/src/imx-wallet/imxWallet.ts

Fixed signature discrepancies between ethers.js v5 and v6 when signing messages containing special characters, ensuring consistent behaviour across versions when deriving starkex key pair.
Explicitly encode the message using `ethers.toUtf8Bytes()` before passing it to signMessage() to ensure consistent UTF-8 encoding in both ethers.js v5 and v6.
Fixed issue where signing a message with non-ASCII characters (e.g., curly apostrophes) might produce different signatures between ethers.js v5 and v6 due to implicit encoding differences.

fix(immutable-x): Enforce utf8 encoding when deriving starkex key pair

---

packages/checkout/widgets-lib/package.json
packages/checkout/widgets-lib/src/lib/utils.test.ts
packages/checkout/widgets-lib/src/lib/utils.ts
packages/checkout/widgets-lib/src/widgets/swap/components/Fees.tsx
packages/checkout/widgets-lib/src/widgets/swap/components/SwapForm.tsx
packages/checkout/widgets-sample-app/src/components/ui/swap/swap.tsx
packages/checkout/widgets-sample-app/src/utils/passport.ts
pnpm-lock.yaml

Two bugs on the swaps widget relating to fees.
* For Passport, no fees were being shown at all
* For EOA, the secondary fees were excluded from the total.
Now:
EOA:
Passport:

fix(checkout): Show correct swap fees

---

packages/checkout/widgets-lib/src/widgets/transfer/TransferForm.tsx
packages/checkout/widgets-lib/src/widgets/transfer/TransferWidget.tsx

Two changes:
1. When clicking "max" - it puts in the full amount so that dust is not left in the wallet.
2. Once transfer completes, the balances are refreshed so that they reflect the transfer that just happened.

fix(checkout): Allow all decimals for max transfer

---

.github/scripts/version-up.sh

This PR updates the publish workflow's version selection script to match on version tags that have the `prerelease-` prefix. Will fix [this](https://github.com/immutable/ts-immutable-sdk/actions/runs/14255426485/job/39957157753) NPM publish error.

chore(operations): ID-3423 fix v1 publish workflow

---

packages/checkout/sdk/src/network/network.test.ts
packages/checkout/sdk/src/network/network.ts
packages/checkout/widgets-lib/src/widgets/connect/views/SwitchNetworkZkEVM.tsx

This was a regression in v2 of the SDK, due to the changes in the way Ethers does error handling.

fix(checkout): Correctly handle adding a new network

---

packages/game-bridge/src/index.ts

Add extra params support when init passport in the game bridge. This is in preparation of custom login UI inside GameSDKs.
Game Bridge now supports the `extraParams` when initialising passport client. Because `extraParams` needs to be changed every user clicks on a different login option, an additional change is introduced to re-initialise passport client when configuration changes.

feat(passport): Add extra params support when init passport in the game bridge

---

packages/checkout/widgets-lib/src/widgets/immutable-commerce/hooks/useWidgetEvents.ts

The `WALLETCONNECT_PROVIDER_UPDATED` event was not being mapped to a commerce connect event throwing an error for an unknown type. This event was not comsumed so dropped this event for commerce widget and the updated provider is available via success event.

fix(checkout): commerce widget error

---

packages/passport/sdk/src/Passport.test.ts
packages/passport/sdk/src/Passport.ts

Calling the `login` method twice can result in a `No matching state found in storage` error once the user authenticates. This PR solves this issue by adding debounce logic to the `login` method.
- Passport: Improved how we handle multiple calls to the login method

feat(passport): ID-3764 Debounce login

---

packages/passport/sdk/src/authManager.test.ts
packages/passport/sdk/src/authManager.ts

Revoke refresh token on logout

[ID-3716] feat: revoke refresh token on logout

---

packages/passport/sdk/src/zkEvm/relayerClient.test.ts
packages/passport/sdk/src/zkEvm/relayerClient.ts

Improved JSON parsing error message in `postToRelayer` to address `SyntaxError: Unexpected end of JSON`.
[ID-3834](https://immutable.atlassian.net/browse/ID-3834?atlOrigin=eyJpIjoiMzUwN2UzNTY2ZTU3NDc3NWIzOTNjOTMwZThmMDRiZWUiLCJwIjoiaiJ9)
[ID-3834]: https://immutable.atlassian.net/browse/ID-3834?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore(passport): improve passport post to relayer error message

---

packages/game-bridge/src/index.ts
packages/passport/sdk/src/Passport.ts
packages/passport/sdk/src/authManager.test.ts
packages/passport/sdk/src/authManager.ts

Added get logout URL function for game SDKs.
[ID-3845](https://immutable.atlassian.net/browse/ID-3845)
[ID-3845]: https://immutable.atlassian.net/browse/ID-3845?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(passport): game sdk pkce logout url

---

packages/passport/sdk/src/zkEvm/relayerClient.test.ts
packages/passport/sdk/src/zkEvm/relayerClient.ts
packages/passport/sdk/src/zkEvm/transactionHelpers.test.ts
packages/passport/sdk/src/zkEvm/transactionHelpers.ts

* Fix `getFeeOption` undefined error when `imGetFeeOptions` returns an invalid response
* Check `postToRelayer` error
[ID-3849](https://immutable.atlassian.net/browse/ID-3849)
[ID-3849]: https://immutable.atlassian.net/browse/ID-3849?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(passport): undefined fee options

---

packages/game-bridge/src/index.ts
packages/passport/sdk-sample-app/src/components/PassportMethods.tsx
packages/passport/sdk-sample-app/src/context/PassportProvider.tsx
packages/passport/sdk/src/Passport.ts
packages/passport/sdk/src/authManager.test.ts
packages/passport/sdk/src/authManager.ts
packages/passport/sdk/src/config/config.ts
packages/passport/sdk/src/types.ts

- Add support for direct login methods (Google, Apple, Facebook) in TS SDK and Game Bridge. This allow users to skip the standard login page to redirect directly to their preferred authenticated provider
- Remove `extraQueryParams` which was used as a generic way of passing the direct login method. This required re-initialising the passport whenever the login method changed. We now pass the direct login method when login happens
[ID-3818](https://immutable.atlassian.net/browse/ID-3818) [ID-3832](https://immutable.atlassian.net/browse/ID-3832)
[ID-3818]: https://immutable.atlassian.net/browse/ID-3818?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(passport, gamebridge): add support for direct login methods (google, apple, facebook) in ts sdk and game bridge

---

packages/checkout/sdk-sample-app/src/components/CheckConnection.tsx
packages/checkout/sdk-sample-app/src/components/GetAllBalances.tsx
packages/checkout/sdk-sample-app/src/components/GetBalance.tsx
packages/checkout/sdk-sample-app/src/components/SendTransaction.tsx
packages/checkout/sdk-sample-app/src/components/SwitchNetwork.tsx
packages/checkout/sdk-sample-app/src/pages/ConnectWidget.tsx
packages/checkout/sdk/src/network/network.test.ts
packages/checkout/sdk/src/network/network.ts

Fixes the error handling case upon receving a Metamask error when switching to an unrecognized network is detected, in order to add that network and then switch to it. 
The expected error shape has been added to with an `||`, to safely handle both error shapes if they may occur.
Allow again users who do not have zkEVM network in their wallet to connect more smoothly.
- Metamask error handling for unrecogized chain error
- Connect flow for users who have not yet added zkEVM network to their wallet

fix(checkout-sdk): Unrecognized chain error handling

---

packages/passport/sdk/src/Passport.int.test.ts
packages/passport/sdk/src/authManager.test.ts
packages/passport/sdk/src/authManager.ts
packages/passport/sdk/src/utils/token.test.ts
packages/passport/sdk/src/utils/token.ts

[ID-3828](https://immutable.atlassian.net/browse/ID-3828)
- Force token refresh if access token is going to expire (within 30 secs).
[ID-3828]: https://immutable.atlassian.net/browse/ID-3828?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(passport): update access token expiry check

---

packages/passport/sdk/src/authManager.test.ts
packages/passport/sdk/src/authManager.ts

This PR resolves an issue with the logout method not clearing the application session when silent logout mode is being used.  Calling `eth_requestAccounts` on the zkEVM provider after calling logout would continue to return the user's wallet address until the logout method is called a second time.
This can be reproduced in the Passport SDK sample app.
- Passport: Fixed an issue with the logout method not clearing the application session when silent logout mode is being used

fix(passport): ID-3874 Fix logout issue

---

packages/passport/sdk/src/Passport.ts
packages/passport/sdk/src/authManager.test.ts
packages/passport/sdk/src/authManager.ts

Windows does not reliably trigger custom URL protocols on redirect. To improve logout behaviour for Game SDKs, a dedicated Passport logout URL with a manual redirect link was added.
This PR updates the Passport package to use the dedicated logout URL for Game SDKs.
[ID-3873](https://immutable.atlassian.net/browse/ID-3873)
[ID-3873]: https://immutable.atlassian.net/browse/ID-3873?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(passport): logout endpoint for game sdks

---

packages/passport/sdk/src/Passport.ts
packages/passport/sdk/src/authManager.ts

Add a `storeTokens` function for Game SDKs to store tokens received from the token exchange for BYOA customers.
[ID-3871]()
[ID-3871]: https://immutable.atlassian.net/browse/ID-3871?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(passport): store tokens

---

packages/checkout/sdk/src/api/blockscout/blockscout.ts
packages/checkout/sdk/src/api/blockscout/blockscoutType.ts

Fixes an issue with blockscout api having changed recently where they are not sending the `token.address` field on L1.
It was affecting the bridge, balances component where none of the ERC20s were visible because we relied on the address field. The fix is populating that field with `address_hash` so rest of the components can just use that

feat(checkout): use address_hash to fill out address field

---

packages/checkout/sdk/src/api/blockscout/blockscout.test.ts
packages/checkout/sdk/src/api/blockscout/blockscout.ts
packages/checkout/sdk/src/api/blockscout/blockscoutType.ts

The API response structure has changed from blockscout so need to represent the change in the type more accurately. But at the same time transform those changed properties to what it was so the consumers don't need to change anything or break the existing usage.

feat(checkout): Create new types for API response to represent the response structure correctly

---

packages/checkout/sdk/src/api/blockscout/blockscout.ts

Patches a breaking change from blockscout API to reutrn the erc20 balances in the expected structure to consumers

Fix(checkout): Breaking API change fix for ERC20 balances

---

packages/passport/sdk-sample-app/src/components/Message.tsx
packages/passport/sdk/src/Passport.int.test.ts
packages/passport/sdk/src/authManager.test.ts
packages/passport/sdk/src/authManager.ts

This PR mitigates an issue caused by the third-party OIDC library we use that results in the `login` promise not rejecting when the user closes the login popup. See [here](https://github.com/authts/oidc-client-ts/issues/2043) for more info.
- Passport: Fixed an issue with calls to `login`, `eth_requestAccounts`, and `connectImx` not rejecting when the user closes the login popup.

fix(passport): ID-3950 Fix login calls not rejecting

---

packages/checkout/sdk/src/index.ts
packages/checkout/sdk/src/riskAssessment/common.ts
packages/checkout/sdk/src/riskAssessment/index.ts
packages/checkout/sdk/src/riskAssessment/riskAssessment.test.ts
packages/checkout/sdk/src/riskAssessment/riskAssessmentV2.test.ts
packages/checkout/sdk/src/riskAssessment/riskAssessmentV2.ts
packages/checkout/widgets-lib/src/widgets/swap/SwapWidget.tsx
packages/checkout/widgets-lib/src/widgets/swap/components/SwapForm.tsx
packages/checkout/widgets-lib/src/widgets/swap/context/SwapContext.ts

- Added seperate call to V2 sanctions API in risk assessment lib
- Updated swaps widget to call new sanctions check as part of the Swap flow 
- Now that the check is being consumed as soon as it is done, there is no need to store the result in state and we can therefore remove

feat(checkout): update swap widget to use sanctions v2 check

---

packages/checkout/widgets-lib/src/widgets/bridge/components/BridgeForm.tsx

feat(checkout-widgets): Include token address and amount in bridge risk assessments

---

packages/checkout/widgets-lib/src/widgets/sale/context/SaleContextProvider.tsx
packages/checkout/widgets-lib/src/widgets/sale/views/OrderSummary.tsx
packages/checkout/widgets-lib/src/widgets/sale/views/PaymentMethods.tsx

Primary sales widget current behaviour:
- Perform a wallet based (V1) sanctions check on widget mount
- Check sanction result and error out if sanctioned
- when a uses selects credit or debit payment type
- when a user proceeeds to buy with a token
This PR: 
- upgrades the second case to use the V2 sanctions endpoint as the token details are known
- calculate the sale amount using the same displayed price calculations as done in the UI for the OrderItems list
- removes the first case as we can safely rely on the third party provider (transak) checks of their own
- remove risk assessment from context state as it is no longer used
Uses the correct total sale price regardless of whether balance is sufficient or not

chore(checkout): update primary sale widget to use sanctions v2 endpoint

---

.github/workflows/pr.yaml

We no longer need to run these func-tests on imx sandbox, they put unncessary load on things and are not useful to us.

ci(all): SRE-3054: Only run zkevm func-tests

---

packages/passport/sdk/src/Passport.ts
packages/passport/sdk/src/index.ts
packages/passport/sdk/src/types.ts

This PR exposes the types for Passport's `connectEvm` & `login` methods.
- Passport: Exposed the types for `connectEvm` & `login`.

fix(passport): ID-3991: Expose method argument types

---

packages/checkout/sdk/src/fiatRamp/fiatRamp.ts
packages/checkout/sdk/src/sdk.ts
packages/checkout/sdk/src/types/fiatRamp.ts
packages/checkout/sdk/src/widgets/definitions/configurations/onramp.ts
packages/checkout/widgets-lib/src/widgets/immutable-commerce/CommerceWidget.tsx
packages/checkout/widgets-lib/src/widgets/on-ramp/OnRampWidget.tsx
packages/checkout/widgets-lib/src/widgets/on-ramp/OnRampWidgetRoot.tsx
packages/checkout/widgets-lib/src/widgets/on-ramp/views/OnRampMain.tsx

Made on-ramp widget features customisable: title, menu icon
Jira: https://immutable.atlassian.net/browse/GFI-1187
Example of removed icon and title
1ed-aad2-44d4-8cdd-608689326afb" />

feat(checkout-widgets): Make on-ramp widget title and menu icon customisable

---

packages/passport/sdk/src/authManager.test.ts
packages/passport/sdk/src/authManager.ts
packages/passport/sdk/src/confirmation/embeddedLoginPrompt.test.ts
packages/passport/sdk/src/confirmation/embeddedLoginPrompt.ts

https://immutable.atlassian.net/browse/ID-3991
This PR passes the `anonymousId` to the embedded login prompt to make tracking easier.
- Passport: Improved tracking when using the embedded login prompt

feat(passport): ID-3991-login-prompt-anonymousId

---

packages/passport/sdk-sample-app/src/components/imx/Trade.tsx
packages/passport/sdk-sample-app/src/components/zkevm/Request.tsx

This PR fixes the `fulfillAvailableAdvancedOrders` example in the Passport SDK sample app.
- Passport sample app: Fixed `fulfillAvailableAdvancedOrders` example

chore(passport): Fix Seaport fulfillAvailableAdvancedOrders in Passport SDK sample app
